Pull from Indie BI Cumulative Details by Product chart

In [2]:
import pandas as pd
import glob
import os
import warnings

warnings.filterwarnings("ignore")

In [3]:


# Define folder path
folder_path = "units/cume_units.xlsx"


# Read all files into DataFrames and add filename column
df = pd.read_excel(folder_path, skiprows=2)

In [4]:
df['product'].unique()

array(['What Remains of Edith Finch',
       'What Remains of Edith Finch - Original Soundtrack', 'Gorogoa',
       'Gorogoa - Original Soundtrack', 'Donut County',
       'Donut County - Original Soundtrack', 'Gone Home', 'Ashen',
       'Flower', 'Outer Wilds', 'Journey', 'Telling Lies',
       'Telling Lies - Original Soundtrack',
       'Ashen - Nightstorm Isle DLC', 'Sayonara Wild Hearts', 'Wattam',
       'Ashen - Original Soundtrack',
       'Sayonara Wild Hearts - Original Soundtrack',
       'Kentucky Route Zero: TV Edition', 'Florence',
       'Florence - Original Soundtrack', 'If Found...',
       'If Found... - Original Soundtrack',
       'Outer Wilds - Original Soundtrack', 'Due Process',
       'The Unfinished Swan', 'I Am Dead',
       'I Am Dead - Original Soundtrack', 'The Pathless',
       'Due Process - Original Soundtrack',
       'Wattam - Original Soundtrack', 'Maquette', 'Mundaun', 'Last Stop',
       'Last Stop - Original Soundtrack', 'Twelve Minutes',
       'Twelve Minutes - Original Soundtrack', 'The Artful Escape',
       'The Artful Escape - Original Soundtrack',
       'Outer Wilds - Archaeologist Edition BUNDLE',
       'Outer Wilds - Echoes of the Eye DLC',
       'The Pathless - Original Soundtrack', 'Solar Ash', 'A Memoir Blue',
       'A Memoir Blue - Original Soundtrack', 'Neon White', 'Stray',
       'Neon White - Original Soundtrack', 'Stray - Original Soundtrack',
       'Hohokum', 'Hindsight', 'Hindsight - Original Soundtrack',
       'Solar Ash - Original Soundtrack', 'Storyteller',
       'Storyteller - Original Soundtrack', 'Cocoon', 'Thirsty Suitors',
       'Thirsty Suitors - Original Soundtrack', 'Cocoon - Soundtrack',
       'Open Roads', 'Lorelei and the Laser Eyes',
       'Lorelei and the Laser Eyes - Original Soundtrack', 'Flock',
       'Flock - Original Soundtrack', 'Wanderstop',
       'Wanderstop - Soundtrack'], dtype=object)

In [5]:
df = df.rename({"Cumulative Selected Measure":"units"}, axis=1)

In [6]:
df.drop_duplicates(subset='product', keep='last').tail(25)

            Date                                            product    units
93922 2025-03-19                               Sayonara Wild Hearts   304798
93923 2025-03-19         Sayonara Wild Hearts - Original Soundtrack    11305
93924 2025-03-19                                          Solar Ash   113680
93925 2025-03-19                    Solar Ash - Original Soundtrack     1064
93926 2025-03-19                                        Storyteller   561188
93927 2025-03-19                  Storyteller - Original Soundtrack     8569
93928 2025-03-19                                              Stray  5695732
93929 2025-03-19                        Stray - Original Soundtrack    78066
93930 2025-03-19                                       Telling Lies   162028
93931 2025-03-19                 Telling Lies - Original Soundtrack     1285
93932 2025-03-19                                  The Artful Escape    57748
93933 2025-03-19            The Artful Escape - Original Soundtrack     1559
93934 2025-03-19                                       The Pathless   194297
93935 2025-03-19                 The Pathless - Original Soundtrack     1509
93936 2025-03-19                                The Unfinished Swan   130762
93937 2025-03-19                                    Thirsty Suitors    12555
93938 2025-03-19              Thirsty Suitors - Original Soundtrack      262
93939 2025-03-19                                     Twelve Minutes   364571
93940 2025-03-19               Twelve Minutes - Original Soundtrack     3344
93941 2025-03-19                                         Wanderstop    40727
93942 2025-03-19                            Wanderstop - Soundtrack     1552
93943 2025-03-19                                             Wattam    91793
93944 2025-03-19                       Wattam - Original Soundtrack     1014
93945 2025-03-19                        What Remains of Edith Finch  2371869
93946 2025-03-19  What Remains of Edith Finch - Original Soundtrack    38760

In [7]:
df['release_date'] = pd.to_datetime(df['Date'])

In [8]:
df['release_date'] = df.groupby('product')['release_date'].transform('min')

In [9]:
df["DAR"] = (df["Date"] - df["release_date"]).dt.days
#df_combined["DAR"] = df_combined["DAR"].clip(lower=0)

df["Weeks_from_Release"] = (df["DAR"] // 30) + 1  # Week 1 starts at 0-7 days

#df = df.query("0 <= Weeks_from_Release <=12")

df = df.query("'1/1/2015' <= release_date <='1/1/2026'")

df = df.groupby(["product", "Weeks_from_Release"], as_index=False)["units"].max()

In [10]:
df

,product,Weeks_from_Release,units
0,A Memoir Blue,1,3864
1,A Memoir Blue,2,4819
2,A Memoir Blue,3,7520
3,A Memoir Blue,4,8725
4,A Memoir Blue,5,9578
...,...,...,...
3159,What Remains of Edith Finch - Original Soundtrack,93,38093
3160,What Remains of Edith Finch - Original Soundtrack,94,38304
3161,What Remains of Edith Finch - Original Soundtrack,95,38453
3162,What Remains of Edith Finch - Original Soundtrack,96,38723
3163,What Remains of Edith Finch - Original Soundtrack,97,38760

In [11]:
title = 'Wanderstop'
current_cume = df.query("product==@title")['units'].values[0]

In [12]:
ranked_df = df.query("Weeks_from_Release ==1").sort_values(by='units', ascending=False)

In [13]:
range = 0.25

high_end = current_cume * (1 + range)
low_end = current_cume * (1 - range)

In [14]:
low_end

30545.25

In [15]:
ranked_df.query("@low_end < units <@high_end")

                          product  Weeks_from_Release  units
1392                      Journey                   1  50401
2849                   Wanderstop                   1  40727
1819                  Outer Wilds                   1  34607
2321  Stray - Original Soundtrack                   1  31919

In [16]:
complist = [
'What Remains of Edith Finch','Flock','Wanderstop','Open Roads', 'Lorelei and the Laser Eyes','Storyteller', 'Cocoon',
    
]

In [17]:
ranked_df.query("product==@complist")

                          product  Weeks_from_Release  units
2236                  Storyteller                   1  77170
2849                   Wanderstop                   1  40727
1617   Lorelei and the Laser Eyes                   1  21612
284                        Cocoon                   1  13876
1807                   Open Roads                   1   7358
590                         Flock                   1   4411
2969  What Remains of Edith Finch                   1   2888