Pull from Indie BI Cumulative Details by Product chart

In [1]:
import pandas as pd
import glob
import os
import warnings

warnings.filterwarnings("ignore")

In [2]:


# Define folder path
folder_path = "units/cume_units.xlsx"


# Read all files into DataFrames and add filename column
df = pd.read_excel(folder_path, skiprows=2)

In [3]:
folder_path = "units/cume_revenues.xlsx"


revs  = pd.read_excel(folder_path, skiprows=2)

In [4]:
df['product'].unique()

array(['What Remains of Edith Finch',
       'What Remains of Edith Finch - Original Soundtrack', 'Gorogoa',
       'Gorogoa - Original Soundtrack', 'Donut County',
       'Donut County - Original Soundtrack', 'Gone Home', 'Ashen',
       'Flower', 'Outer Wilds', 'Journey', 'Telling Lies',
       'Telling Lies - Original Soundtrack',
       'Ashen - Nightstorm Isle DLC', 'Sayonara Wild Hearts', 'Wattam',
       'Ashen - Original Soundtrack',
       'Sayonara Wild Hearts - Original Soundtrack',
       'Kentucky Route Zero: TV Edition', 'Florence',
       'Florence - Original Soundtrack', 'If Found...',
       'If Found... - Original Soundtrack',
       'Outer Wilds - Original Soundtrack', 'Due Process',
       'The Unfinished Swan', 'I Am Dead',
       'I Am Dead - Original Soundtrack', 'The Pathless',
       'Due Process - Original Soundtrack',
       'Wattam - Original Soundtrack', 'Maquette', 'Mundaun', 'Last Stop',
       'Last Stop - Original Soundtrack', 'Twelve Minutes',
       'Twelve Minutes - Original Soundtrack', 'The Artful Escape',
       'The Artful Escape - Original Soundtrack',
       'Outer Wilds - Archaeologist Edition BUNDLE',
       'Outer Wilds - Echoes of the Eye DLC',
       'The Pathless - Original Soundtrack', 'Solar Ash', 'A Memoir Blue',
       'A Memoir Blue - Original Soundtrack', 'Neon White', 'Stray',
       'Neon White - Original Soundtrack', 'Stray - Original Soundtrack',
       'Hohokum', 'Hindsight', 'Hindsight - Original Soundtrack',
       'Solar Ash - Original Soundtrack', 'Storyteller',
       'Storyteller - Original Soundtrack', 'Cocoon', 'Thirsty Suitors',
       'Thirsty Suitors - Original Soundtrack', 'Cocoon - Soundtrack',
       'Open Roads', 'Lorelei and the Laser Eyes',
       'Lorelei and the Laser Eyes - Original Soundtrack', 'Flock',
       'Flock - Original Soundtrack', 'Wanderstop',
       'Wanderstop - Soundtrack'], dtype=object)

In [5]:
revs

,Date,product,Cumulative Selected Measure
0,2017-03-14,What Remains of Edith Finch,2673.49
1,2017-03-15,What Remains of Edith Finch,7086.67
2,2017-03-16,What Remains of Edith Finch,9976.77
3,2017-03-17,What Remains of Edith Finch,11789.20
4,2017-03-18,What Remains of Edith Finch,14156.59
...,...,...,...
93942,2025-03-19,Wanderstop - Soundtrack,11284.41
93943,2025-03-19,Wattam,1062198.57
93944,2025-03-19,Wattam - Original Soundtrack,4811.15
93945,2025-03-19,What Remains of Edith Finch,18556513.58
93946,2025-03-19,What Remains of Edith Finch - Original Soundtrack,91294.11

In [6]:
df = df.rename({"Cumulative Selected Measure":"units"}, axis=1)

In [7]:
df.drop_duplicates(subset='product', keep='last').tail(25)

            Date                                            product    units
93922 2025-03-19                               Sayonara Wild Hearts   304840
93923 2025-03-19         Sayonara Wild Hearts - Original Soundtrack    11307
93924 2025-03-19                                          Solar Ash   113708
93925 2025-03-19                    Solar Ash - Original Soundtrack     1065
93926 2025-03-19                                        Storyteller   561367
93927 2025-03-19                  Storyteller - Original Soundtrack     8573
93928 2025-03-19                                              Stray  5697403
93929 2025-03-19                        Stray - Original Soundtrack    78111
93930 2025-03-19                                       Telling Lies   162054
93931 2025-03-19                 Telling Lies - Original Soundtrack     1285
93932 2025-03-19                                  The Artful Escape    57763
93933 2025-03-19            The Artful Escape - Original Soundtrack     1559
93934 2025-03-19                                       The Pathless   194359
93935 2025-03-19                 The Pathless - Original Soundtrack     1510
93936 2025-03-19                                The Unfinished Swan   130807
93937 2025-03-19                                    Thirsty Suitors    12560
93938 2025-03-19              Thirsty Suitors - Original Soundtrack      262
93939 2025-03-19                                     Twelve Minutes   364642
93940 2025-03-19               Twelve Minutes - Original Soundtrack     3345
93941 2025-03-19                                         Wanderstop    41028
93942 2025-03-19                            Wanderstop - Soundtrack     1565
93943 2025-03-19                                             Wattam    91811
93944 2025-03-19                       Wattam - Original Soundtrack     1015
93945 2025-03-19                        What Remains of Edith Finch  2372706
93946 2025-03-19  What Remains of Edith Finch - Original Soundtrack    38767

In [8]:
df['release_date'] = pd.to_datetime(df['Date'])

df['release_date'] = df.groupby('product')['release_date'].transform('min')

df["DAR"] = (df["Date"] - df["release_date"]).dt.days
#df_combined["DAR"] = df_combined["DAR"].clip(lower=0)

df["Weeks_from_Release"] = (df["DAR"] // 30) + 1  # Week 1 starts at 0-7 days

#df = df.query("0 <= Weeks_from_Release <=12")

df = df.query("'1/1/2015' <= release_date <='1/1/2026'")

df = df.groupby(["product", "Weeks_from_Release"], as_index=False)["units"].max()

In [9]:
title = 'Wanderstop'

In [10]:
current_cume = df.query("product==@title")['units'].values[0]

In [11]:
df.query("product==@title")

         product  Weeks_from_Release  units
2849  Wanderstop                   1  41028

In [12]:
ranked_df = df.query("Weeks_from_Release ==1").sort_values(by='units', ascending=False)

In [13]:
range = 0.25

high_end = current_cume * (1 + range)
low_end = current_cume * (1 - range)

In [14]:
low_end

30771.0

In [15]:
df_filtered = ranked_df[~ranked_df['product'].str.contains('Soundtrack', case=False, na=False)]

In [16]:
df_filtered.query("@low_end < units <@high_end")

          product  Weeks_from_Release  units
1392      Journey                   1  50401
2849   Wanderstop                   1  41028
1819  Outer Wilds                   1  34607

In [17]:
complist = [
'What Remains of Edith Finch','Flock','Wanderstop','Open Roads', 'Lorelei and the Laser Eyes','Storyteller', 'Cocoon',
    
]

In [18]:
ranked_df.query("product==@complist")

                          product  Weeks_from_Release  units
2236                  Storyteller                   1  77170
2849                   Wanderstop                   1  41028
1617   Lorelei and the Laser Eyes                   1  21612
284                        Cocoon                   1  13876
1807                   Open Roads                   1   7358
590                         Flock                   1   4411
2969  What Remains of Edith Finch                   1   2888

# Average Sales Price

In [20]:


# Define folder path
folder_path = "units/cume_units.xlsx"


# Read all files into DataFrames and add filename column
units = pd.read_excel(folder_path, skiprows=2)

units = units.rename({"Cumulative Selected Measure":"units"}, axis=1)

In [21]:
units

            Date                                            product    units
0     2017-03-14                        What Remains of Edith Finch      165
1     2017-03-15                        What Remains of Edith Finch      438
2     2017-03-16                        What Remains of Edith Finch      614
3     2017-03-17                        What Remains of Edith Finch      726
4     2017-03-18                        What Remains of Edith Finch      871
...          ...                                                ...      ...
93942 2025-03-19                            Wanderstop - Soundtrack     1565
93943 2025-03-19                                             Wattam    91811
93944 2025-03-19                       Wattam - Original Soundtrack     1015
93945 2025-03-19                        What Remains of Edith Finch  2372706
93946 2025-03-19  What Remains of Edith Finch - Original Soundtrack    38767

[93947 rows x 3 columns]

In [22]:

revs = revs.rename({"Cumulative Selected Measure":"revenue"}, axis=1)

revs

,Date,product,revenue
0,2017-03-14,What Remains of Edith Finch,2673.49
1,2017-03-15,What Remains of Edith Finch,7086.67
2,2017-03-16,What Remains of Edith Finch,9976.77
3,2017-03-17,What Remains of Edith Finch,11789.20
4,2017-03-18,What Remains of Edith Finch,14156.59
...,...,...,...
93942,2025-03-19,Wanderstop - Soundtrack,11284.41
93943,2025-03-19,Wattam,1062198.57
93944,2025-03-19,Wattam - Original Soundtrack,4811.15
93945,2025-03-19,What Remains of Edith Finch,18556513.58
93946,2025-03-19,What Remains of Edith Finch - Original Soundtrack,91294.11

In [23]:
combined = pd.merge(units, revs, on=["product", 'Date'])

In [24]:
combined['avg_price'] = combined['revenue'] / combined['units']

In [25]:
combined.query("product=='Stray'")

            Date product    units       revenue  avg_price
35245 2022-06-02   Stray    13946  3.063829e+05  21.969233
35292 2022-06-03   Stray    36669  7.776848e+05  21.208236
35339 2022-06-04   Stray    51053  1.068529e+06  20.929790
35386 2022-06-05   Stray    63298  1.319098e+06  20.839489
35433 2022-06-06   Stray    73428  1.518895e+06  20.685503
...          ...     ...      ...           ...        ...
93664 2025-03-15   Stray  5682209  1.306722e+08  22.996729
93730 2025-03-16   Stray  5688055  1.307725e+08  22.990725
93796 2025-03-17   Stray  5692243  1.308404e+08  22.985731
93862 2025-03-18   Stray  5696130  1.309041e+08  22.981227
93928 2025-03-19   Stray  5697403  1.309226e+08  22.979343

[1022 rows x 5 columns]

In [26]:
combined.groupby(by='product')[['units', 'revenue', 'avg_price']].max().to_csv("lifetime_units_and_rev.csv")

In [27]:
combined['release_date'] = pd.to_datetime(combined['Date'])

combined['release_date'] = combined.groupby('product')['release_date'].transform('min')

combined["DAR"] = (combined["Date"] - combined["release_date"]).dt.days
#df_combined["DAR"] = df_combined["DAR"].clip(lower=0)

combined["Weeks_from_Release"] = (combined["DAR"] // 30) + 1  # Week 1 starts at 0-7 days

#df = df.query("0 <= Weeks_from_Release <=12")

combined = combined.query("'1/1/2015' <= release_date <='1/1/2025'")

combined = combined.groupby(["product", "Weeks_from_Release"], as_index=False)["avg_price"].max()

In [28]:
combined['price_delta'] = combined.groupby('product')['avg_price'].diff()

In [29]:
import numpy as np

conditions = [
    (combined['Weeks_from_Release'] > 0) & (combined['Weeks_from_Release'] <= 12),   # 1-12 months (first year)
    (combined['Weeks_from_Release'] > 12) & (combined['Weeks_from_Release'] <= 24), # 13-24 months (second year)
    (combined['Weeks_from_Release'] > 24)  # 24+ months (3+ years)
]

choices = ['First Year', 'Second Year', '3+ Years']

combined['TIER'] = np.select(conditions, choices, default='Unknown')  # 'Unknown' if it doesn't fit any condition

In [30]:
combined.groupby('TIER').avg_price.mean().sort_values()

TIER
3+ Years        8.914055
Second Year    11.119293
First Year     12.876770
Name: avg_price, dtype: float64

In [31]:
combined.groupby('TIER').price_delta.mean().sort_values()

TIER
First Year    -0.145552
Second Year   -0.111278
3+ Years      -0.046001
Name: price_delta, dtype: float64