In [1]:
import pandas as pd
## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [2]:

db = client['project_evaluations']

collection = db['games']

In [3]:
from datetime import datetime

query_docs = collection.find({
    "first_release_date": {"$gt": datetime(2024, 1, 1)},
    "steam_id": {"$exists": True, "$ne": None},
        "idg_owners_est": {"$exists": False}


})

In [4]:
from datetime import datetime

query_docs = collection.find({
    "idg_owners_est": {"$exists": True}})

In [5]:
df = pd.DataFrame(query_docs)

In [6]:
pd.json_normalize(df['idg_owners_est']).sum() / pd.json_normalize(df['idg_owners_est']).sum().sum()

Steam             0.511582
PS4               0.192465
XBO               0.150917
WindowsOneCore    0.007031
PS5               0.132695
XBS               0.005311
dtype: float64

In [7]:
owners_col = pd.json_normalize(df['idg_owners_est'])

In [8]:
owners_col['total_owners'] = owners_col.sum(axis=1)

In [28]:
owners_col / 1_000

        Steam    PS4    XBO  WindowsOneCore  PS5  XBS  total_owners
0      1164.0    NaN    NaN             NaN  NaN  NaN        1164.0
1      3339.0  522.0  381.0             NaN  NaN  NaN        4242.0
2       635.0    NaN    NaN             NaN  NaN  NaN         635.0
3       781.0    NaN    NaN             NaN  NaN  NaN         781.0
4         NaN    NaN    NaN             NaN  NaN  NaN           0.0
...       ...    ...    ...             ...  ...  ...           ...
23415     NaN    NaN    NaN             NaN  NaN  NaN           0.0
23416     NaN    NaN    NaN             NaN  NaN  NaN           0.0
23417     NaN    NaN    NaN             NaN  NaN  NaN           0.0
23418     NaN    NaN    NaN             NaN  NaN  NaN           0.0
23419     NaN    NaN    NaN             NaN  NaN  NaN           0.0

[23420 rows x 7 columns]

In [10]:
combined = pd.concat([df, owners_col], axis=1)

In [30]:
combined.sort_values(by='total_owners', ascending=False).head(10)

,_id,checksum,name,game_modes,first_release_date,genres,storyline,summary,themes,involved_companies,...,time_to_beat_hastily,time_to_beat_normally,Gamalytic_Updated,Steam,PS4,XBO,WindowsOneCore,PS5,XBS,total_owners
10743,1020,c099f3d2-14f0-57f3-ca2d-068855babca4,Grand Theft Auto V,"[Single player, Multiplayer, Co-operative]",2013-09-17,"[Shooter, Racing, Adventure]",Los Santos: a sprawling sun-soaked metropolis ...,Grand Theft Auto V is a vast open world game s...,"[Action, Comedy, Sandbox, Open world]","[Take-Two Interactive, Rockstar Games, Rocksta...",...,NaN,NaN,2025-06-30 07:14:43.005030,42367000.0,91040000.0,41874000.0,58000.0,25440000.0,10760000.0,211539000.0
3420,114795,11502eeb-9ec4-0150-25ad-f6eadd255563,Apex Legends,"[Multiplayer, Co-operative, Battle Royale]",2019-02-04,"[Shooter, Tactical]",A WORLD WHERE ANYTHING GOES\n\nThe Frontier Wa...,"Conquer with character in Apex Legends, a free...","[Action, Science fiction]","[Respawn Entertainment, 128109]",...,NaN,NaN,2025-06-30 07:14:43.005030,47423000.0,52706000.0,27937000.0,NaN,22160000.0,NaN,150226000.0
1205,1372,03ec69e8-80ed-2bb5-cc67-ec0e2245691d,Counter-Strike: Global Offensive,[Multiplayer],2012-08-21,"[Shooter, Tactical]",NaN,Counter-Strike: Global Offensive expands upon ...,"[Action, Warfare]","[cyreides, Hidden Path Entertainment]",...,NaN,NaN,2025-06-30 07:14:43.005030,123662000.0,NaN,NaN,NaN,NaN,NaN,123662000.0
11048,27789,b6c002d3-3ec1-7089-53cb-788bab72d896,PUBG: Battlegrounds,"[Single player, Multiplayer, Co-operative, Bat...",2017-12-20,[Shooter],"PLAYERUNKNOWN, aka Brendan Greene, is a pionee...",PUBG: Battlegrounds is a battle royale shooter...,"[Action, Warfare]","[Bluehole Studio, Microsoft Studios, 58863, 16...",...,NaN,NaN,2025-06-30 07:14:43.005030,85381000.0,7679000.0,19323000.0,NaN,NaN,NaN,112383000.0
5297,207393,112a8eec-f2c7-ec61-d11a-cccb9f3c13f1,NBA 2K23,"[Single player, Multiplayer, Co-operative]",2022-09-08,"[Simulator, Sport]",NaN,Rise to the occasion in NBA 2K23. Showcase you...,[Non-fiction],"[2K Games, Visual Concepts]",...,118560.0,NaN,2025-06-30 07:14:43.005030,1768000.0,17690000.0,3182000.0,NaN,75490000.0,3529000.0,101659000.0
10111,25657,27f42404-0beb-f488-5954-9f680e95f269,Destiny 2,"[Single player, Multiplayer, Co-operative, Mas...",2017-09-06,"[Shooter, Role-playing (RPG), Adventure]",Humanity's last safe city has fallen to an ove...,Dive into the world of Destiny 2 to explore th...,"[Action, Fantasy, Science fiction, Open world,...","[Activision, High Moon Studios, Vicarious Visi...",...,NaN,NaN,2025-06-30 07:14:43.005030,47221000.0,21677000.0,18610000.0,NaN,13645000.0,NaN,101153000.0
22759,119313,1b2f74be-043a-f083-c3c4-7dfe8bd12722,Fall Guys,"[Multiplayer, Co-operative, Battle Royale]",2020-08-04,"[Platform, Racing, Indie]",NaN,Fall Guys flings hordes of contestants togethe...,"[Action, Comedy, Party]","[Mediatonic, Epic Games, Wushu Studios, Devolv...",...,NaN,NaN,NaN,17402000.0,45186000.0,19061000.0,NaN,18304000.0,NaN,99953000.0
9584,256092,ea6e1e8e-274b-dc06-894e-c65d4a6f22c5,EA Sports FC 24,"[Single player, Multiplayer, Co-operative]",2023-09-29,"[Simulator, Sport]",NaN,EA SPORTS FC 24 is the ultimate football simul...,[Non-fiction],"[EA Romania, 248832, 248833]",...,NaN,NaN,2025-06-30 07:14:43.005030,2112000.0,13746000.0,2252000.0,NaN,80934000.0,NaN,99044000.0
10755,7360,6e503017-063d-d93c-8f19-7af4aba68c64,Tom Clancy's Rainbow Six Siege X,"[Single player, Multiplayer, Co-operative]",2015-12-01,"[Shooter, Tactical]",NaN,Inspired by the reality of counter terrorist o...,"[Action, Warfare]","[Ubisoft Montreal, Ubisoft Entertainment, 316501]",...,NaN,NaN,2025-06-30 07:14:43.005030,32358000.0,20368000.0,31515000.0,NaN,13473000.0,NaN,97714000.0
22273,154986,04c7ad5a-6e0e-8719-b654-60b27d33eac8,FIFA 22,"[Single player, Multiplayer, Co-operative, Spl...",2021-10-01,"[Simulator, Sport]",NaN,"Powered by Football, FIFA 22 brings the game e...","[Action, Non-fiction]","[EA Sports, EA Vancouver, EA Romania]",...,36000.0,36000.0,2025-06-30 07:14:43.005030,2144000.0,30268000.0,4416000.0,NaN,54376000.0,2106000.0,93310000.0