https://docs.google.com/spreadsheets/d/1XNp2FBsnFsUoqwEN5b1FXloYbjMMkNc9Re8G4gVCg8U/edit?gid=0#gid=0

In [1]:
import pandas as pd
import glob
import os
import warnings

warnings.filterwarnings("ignore")



# Define folder path
folder_path = "units/cume_units.xlsx"


# Read all files into DataFrames and add filename column
df = pd.read_excel(folder_path, skiprows=2)

folder_path = "units/cume_revenues.xlsx"


df  = pd.read_excel(folder_path, skiprows=2)

folder_path = "units/cume_wishlists.xlsx"


df  = pd.read_excel(folder_path, skiprows=2)

In [31]:
df.query("product =='The Lost Wild'")

Empty DataFrame
Columns: [Date, product, Cumulative Selected Measure]
Index: []

In [3]:
folder_path = "wishlists/Annapurna Interactive Historical Revenues - releases_dates.csv"
dates  = pd.read_csv(folder_path)
dates = dates.dropna(subset='pc_release_date')
dates['pc_release_date'] = pd.to_datetime(dates['pc_release_date'])
release_date_dict = dates.groupby('product')['pc_release_date'].min().to_dict()

In [20]:
dates

                            product pc_release_date
0                           Faraway      2025-12-31
1                           Mixtape      2025-12-31
2                     The Lost Wild      2026-11-01
3                       Wheel World      2025-07-23
4                        BattleSage      2025-06-30
5                            to a T      2025-05-28
6                         Skin Deep      2025-04-30
7          Lushfoil Photography Sim      2025-04-15
8                        Wanderstop      2025-03-11
9                           Morsels      2025-02-28
10                            Flock      2024-07-16
11       Lorelei and the Laser Eyes      2024-05-16
12                       Open Roads      2024-03-28
13                  Thirsty Suitors      2023-11-02
14                           Cocoon      2023-09-29
15                      Storyteller      2023-03-23
16                        Solar Ash      2022-12-08
17                        Hindsight      2022-08-04
18                          Hohokum      2022-07-28
19                            Stray      2022-07-19
20                       Neon White      2022-06-16
21                    A Memoir Blue      2022-03-24
22                     The Pathless      2021-11-16
23                The Artful Escape      2021-09-09
24                   Twelve Minutes      2021-08-19
25                        Last Stop      2021-07-22
26                          Mundaun      2021-03-16
27                         Maquette      2021-03-02
28                           Wattam      2020-12-18
29                      Due Process      2020-11-03
30                        I Am Dead      2020-10-08
31              The Unfinished Swan      2020-09-10
32                      Outer Wilds      2020-06-18
33                          Journey      2020-06-11
34                      If Found...      2020-05-19
35                         Florence      2020-02-13
36  Kentucky Route Zero: TV Edition      2020-01-28
37             Sayonara Wild Hearts      2019-12-12
38                            Ashen      2019-12-09
39                     Telling Lies      2019-08-23
40                           Flower      2019-02-14
41                     Donut County      2018-08-28
42                          Gorogoa      2017-12-14
43      What Remains of Edith Finch      2017-04-25
46                      Bounty Star      2025-10-07
52                 No Goblin Game 3      2026-02-10
53                    LEGO Voyagers      2025-09-30
54                      Snap & Grab      2026-02-10

In [4]:
df = df.rename({"Cumulative Selected Measure":"units"}, axis=1)

In [5]:
df["percent_of_max"] = df["units"] / df.groupby("product")["units"].transform("max")

In [6]:
df['release_date'] = df['product'].map(release_date_dict)

In [28]:
df.query("product =='The Lost Wild'")

Empty DataFrame
Columns: [Date, product, Cumulative Selected Measure]
Index: []

In [7]:
export_df = df.sort_values(by='units', ascending=False).drop_duplicates(subset='product',keep='first')

In [8]:
export_df

,Date,product,units,percent_of_max,release_date
63332,2025-06-27,Stray,1.517113e+08,1.0,2022-07-19
63325,2025-06-27,Outer Wilds,5.026657e+07,1.0,2020-06-18
63342,2025-06-27,What Remains of Edith Finch,1.997536e+07,1.0,2017-04-25
63273,2025-06-26,Journey,1.032946e+07,1.0,2020-06-11
63327,2025-06-27,Outer Wilds - Echoes of the Eye DLC,1.017520e+07,1.0,NaT
63301,2025-06-27,Ashen,9.971470e+06,1.0,2019-12-09
63323,2025-06-27,Neon White,9.124186e+06,1.0,2022-06-16
63305,2025-06-27,Donut County,7.764400e+06,1.0,2018-08-28
63331,2025-06-27,Storyteller,6.724205e+06,1.0,2023-03-23
63339,2025-06-27,Twelve Minutes,6.519146e+06,1.0,2021-08-19
63311,2025-06-27,Gorogoa,6.471803e+06,1.0,2017-12-14
63335,2025-06-27,The Pathless,5.041303e+06,1.0,2021-11-16
63326,2025-06-27,Outer Wilds - Archaeologist Edition BUNDLE,4.960887e+06,1.0,NaT
63304,2025-06-27,Cocoon,4.833352e+06,1.0,2023-09-29
63330,2025-06-27,Solar Ash,3.219865e+06,1.0,2022-12-08
63317,2025-06-27,Kentucky Route Zero: TV Edition,2.790198e+06,1.0,2020-01-28
63328,2025-06-27,Sayonara Wild Hearts,2.710087e+06,1.0,2019-12-12
42892,2024-01-18,Due Process,2.313704e+06,1.0,2020-11-03
63319,2025-06-27,Lorelei and the Laser Eyes,2.274799e+06,1.0,2024-05-16
63308,2025-06-27,Florence,2.013527e+06,1.0,2020-02-13
63333,2025-06-27,Telling Lies,1.807348e+06,1.0,2019-08-23
63340,2025-06-27,Wanderstop,1.696438e+06,1.0,2025-03-11
63341,2025-06-27,Wattam,1.073781e+06,1.0,2020-12-18
63310,2025-06-27,Gone Home,1.014378e+06,1.0,NaT
63266,2025-06-26,Flower,9.640699e+05,1.0,2019-02-14
63279,2025-06-26,Mundaun,8.313341e+05,1.0,2021-03-16
63334,2025-06-27,The Artful Escape,8.265799e+05,1.0,2021-09-09
63293,2025-06-26,The Unfinished Swan,7.904126e+05,1.0,2020-09-10
63271,2025-06-26,I Am Dead,6.853868e+05,1.0,2020-10-08
63302,2025-06-27,Ashen - Nightstorm Isle DLC,6.473353e+05,1.0,NaT
63321,2025-06-27,Maquette,5.604902e+05,1.0,2021-03-02
63315,2025-06-27,If Found...,5.177562e+05,1.0,2020-05-19
63217,2025-06-25,Ashen Definitive Edition,4.400673e+05,1.0,NaT
63320,2025-06-27,Lushfoil Photography Sim,4.205115e+05,1.0,2025-04-15
63329,2025-06-27,Skin Deep,4.056447e+05,1.0,2025-04-30
63318,2025-06-27,Last Stop,3.939399e+05,1.0,2021-07-22
63294,2025-06-26,Thirsty Suitors,3.277885e+05,1.0,2023-11-02
63281,2025-06-26,Open Roads,3.234052e+05,1.0,2024-03-28
63257,2025-06-26,A Memoir Blue,1.890149e+05,1.0,2022-03-24
63264,2025-06-26,Flock,1.641740e+05,1.0,2024-07-16
63295,2025-06-26,to a T,1.251133e+05,1.0,2025-05-28
63312,2025-06-27,Hindsight,1.191022e+05,1.0,2022-08-04
63270,2025-06-26,Hohokum,7.771402e+04,1.0,2022-07-28

In [9]:
export_df[['product', 'units']].to_clipboard(index=False)