https://docs.google.com/spreadsheets/d/1XNp2FBsnFsUoqwEN5b1FXloYbjMMkNc9Re8G4gVCg8U/edit?gid=0#gid=0

In [1]:
import pandas as pd
import glob
import os
import warnings

warnings.filterwarnings("ignore")

In [2]:
from pymongo import UpdateOne

## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [3]:
db = client['ai_sales_data']
collection = db['units']

In [4]:
docs = collection.find({})

In [5]:
df = pd.DataFrame(docs)

In [6]:
df['cumulative_units'] = df.groupby('product')['units'].cumsum()
df['cumulative_rev'] = df.groupby('product')['revenue'].cumsum()

In [7]:
folder_path = "wishlists/Annapurna Interactive Historical Revenues - releases_dates.csv"
dates  = pd.read_csv(folder_path)
dates = dates.dropna(subset='pc_release_date')
dates['pc_release_date'] = pd.to_datetime(dates['pc_release_date'])
release_date_dict = dates.groupby('product')['pc_release_date'].min().to_dict()

In [8]:
dates

                            product pc_release_date
0                           Faraway      2025-12-31
1                           Mixtape      2025-12-31
2                     The Lost Wild      2026-11-01
3                       Wheel World      2025-07-23
4                        BattleSage      2025-06-30
5                            to a T      2025-05-28
6                         Skin Deep      2025-04-30
7          Lushfoil Photography Sim      2025-04-15
8                        Wanderstop      2025-03-11
9                           Morsels      2025-02-28
10                            Flock      2024-07-16
11       Lorelei and the Laser Eyes      2024-05-16
12                       Open Roads      2024-03-28
13                  Thirsty Suitors      2023-11-02
14                           Cocoon      2023-09-29
15                      Storyteller      2023-03-23
16                        Solar Ash      2022-12-08
17                        Hindsight      2022-08-04
18                          Hohokum      2022-07-28
19                            Stray      2022-07-19
20                       Neon White      2022-06-16
21                    A Memoir Blue      2022-03-24
22                     The Pathless      2021-11-16
23                The Artful Escape      2021-09-09
24                   Twelve Minutes      2021-08-19
25                        Last Stop      2021-07-22
26                          Mundaun      2021-03-16
27                         Maquette      2021-03-02
28                           Wattam      2020-12-18
29                      Due Process      2020-11-03
30                        I Am Dead      2020-10-08
31              The Unfinished Swan      2020-09-10
32                      Outer Wilds      2020-06-18
33                          Journey      2020-06-11
34                      If Found...      2020-05-19
35                         Florence      2018-02-14
36  Kentucky Route Zero: TV Edition      2020-01-28
37             Sayonara Wild Hearts      2019-12-12
38                            Ashen      2018-12-07
39                     Telling Lies      2019-08-23
40                           Flower      2019-02-14
41                     Donut County      2018-08-28
42                          Gorogoa      2017-12-14
43      What Remains of Edith Finch      2017-04-25
46                      Bounty Star      2025-10-07
52                 No Goblin Game 3      2026-02-10
53                    LEGO Voyagers      2025-09-30
54                      Snap & Grab      2026-02-10

In [9]:
df.groupby("product")[['cumulative_units']].max().to_clipboard()

In [44]:
df.groupby("product")[['cumulative_rev']].max().sort_values(by='cumulative_rev')/1_000_000

                                       cumulative_rev
product
Skin Deep - Soundtrack Edition               0.000041
Hindsight - Original Soundtrack              0.000780
Flock - Original Soundtrack                  0.000808
Last Stop - Original Soundtrack              0.001466
Thirsty Suitors - Original Soundtrack        0.001747
...                                               ...
Journey                                     10.442315
Outer Wilds - Echoes of the Eye DLC         10.509190
What Remains of Edith Finch                 20.237524
Outer Wilds                                 51.896159
Stray                                      153.843208

[72 rows x 1 columns]

In [11]:
df.groupby("product")[['cumulative_rev']].max().to_clipboard()

In [12]:
wl_df = pd.read_excel("units/cume_wishlists.xlsx", skiprows=2)#.sort_values('Date').drop_duplicates("product", keep='last').reset_index()

In [13]:
wl_df.rename({"Selected Measure":"wishlist_adds"}, axis=1, inplace=True)

In [14]:
wl_df['cumulative_adds'] = wl_df.groupby('product')['wishlist_adds'].cumsum()

In [15]:
wl_df.query("product=='The Lost Wild'")

,Day,product,wishlist_adds,Blank Measure,cumulative_adds
39,2018-01-01,The Lost Wild,0,NaN,0
89,2018-01-02,The Lost Wild,0,NaN,0
139,2018-01-03,The Lost Wild,0,NaN,0
189,2018-01-04,The Lost Wild,0,NaN,0
239,2018-01-05,The Lost Wild,0,NaN,0
...,...,...,...,...,...
143961,2025-07-17,The Lost Wild,228,NaN,470417
144017,2025-07-18,The Lost Wild,212,NaN,470629
144073,2025-07-19,The Lost Wild,193,NaN,470822
144127,2025-07-20,The Lost Wild,216,NaN,471038
144179,2025-07-21,The Lost Wild,37,NaN,471075

In [16]:
wl_df['release_date'] = wl_df['product'].map(release_date_dict)

In [17]:
# Ensure both columns are datetime
wl_df['Day'] = pd.to_datetime(wl_df['Day'])
wl_df['release_date'] = pd.to_datetime(wl_df['release_date'])

# Calculate the difference in days
wl_df['dar'] = (wl_df['Day'] - wl_df['release_date']).dt.days //7

In [18]:
wl_df.query("dar<=0").drop_duplicates(subset='product', keep='last')[['product','cumulative_adds']]

                                product  cumulative_adds
2511                           Florence                0
12262                      Donut County            87898
17406                             Ashen            74384
20936                            Flower            89959
30652                      Telling Lies           154055
36308              Sayonara Wild Hearts            82597
38714   Kentucky Route Zero: TV Edition            19232
44536                       If Found...            21447
45733                           Journey           363115
46108                       Outer Wilds           634983
50488               The Unfinished Swan            81193
51919                         I Am Dead            47830
53262                       Due Process           125247
55641                            Wattam            47721
59466                          Maquette            65485
60197                           Mundaun            27874
66847                         Last Stop            44705
68327                    Twelve Minutes           564909
69413                 The Artful Escape            53715
73007                      The Pathless            90147
79748                     A Memoir Blue            23545
84229                        Neon White           248082
85988                             Stray          4196390
86443                           Hohokum            29407
86813                         Hindsight            27442
93512                         Solar Ash           184399
99078                       Storyteller           238553
109117                           Cocoon           189887
110957                  Thirsty Suitors            60432
118733                       Open Roads           132603
121323       Lorelei and the Laser Eyes            88633
124543                            Flock            69582
136679                          Morsels            40269
137294                       Wanderstop           403622
139160         Lushfoil Photography Sim           224188
139982                        Skin Deep           135393
141504                           to a T            50565
143303                       BattleSage             3232
144067                      Snap & Grab              588
144144                      Bounty Star            55528
144148                          Faraway             5471
144163                          Mixtape           156115
144167                 No Goblin Game 3             9938
144179                    The Lost Wild           471075
144189                      Wheel World           109010