In [1]:
from azure.storage.blob import ContainerClient
account_name = "dlsaggregatedprodr9"
container_name = "saas-gold-direct-data-access"
sas_token = "sp=rl&st=2025-08-06T11:15:05Z&se=2026-07-31T19:30:05Z&spr=https&sv=2024-11-04&sr=d&sig=022LIiARMF6VCOJ1xaQGH6wv04Fwqh8quWp%2BzX07S7w%3D&sdd=2"
folder_path = "data/studio_id=10720/"
#folder_path = "data/studio_id=[your studio ID]/"


blob_service_url = f"https://{account_name}.blob.core.windows.net/"

container_client = ContainerClient(
    account_url=blob_service_url,
    container_name=container_name,
    credential=sas_token
)

In [2]:
blob_client = container_client.get_blob_client('data/studio_id=10720/export_fact_sales.csv')
blob_client_wishlist = container_client.get_blob_client('data/studio_id=10720/export_fact_visibility_wishlist.csv')
#blob_client_visibility = container_client.get_blob_client('data/studio_id=10720/fact_visibility.csv')

In [3]:
import time
import pandas as pd
from io import BytesIO


t0 = time.perf_counter()
data_rev = blob_client.download_blob().readall()
data_wl = blob_client_wishlist.download_blob().readall()
#data_vis = blob_client_visibility.download_blob().readall()

t1 = time.perf_counter()

In [4]:
df = pd.read_csv(BytesIO(data_rev))
df_wl = pd.read_csv(BytesIO(data_wl))
#df_vis = pd.read_csv(BytesIO(data_vis))

t2 = time.perf_counter()

print(f"Download: {t1 - t0:.3f}s")
print(f"CSV parse: {t2 - t1:.3f}s")
print(f"Total: {t2 - t0:.3f}s")

Download: 90.350s
CSV parse: 8.747s
Total: 99.097s

/var/folders/vh/qvl8gx_d2m370qv72srt5r1m0000gp/T/ipykernel_93621/3286014683.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_wl = pd.read_csv(BytesIO(data_wl))

In [5]:
df_wl

,date,unique_sku_id,base_sku_id,human_name,product_id,product_name,portal_platform_region_id,portal,store,country_code,non_owner_visits,non_owner_impressions,adds,deletes,purchases_activations_gifts
0,2010-01-01,1945140-store:10720,1945140,A Memoir Blue - Original Soundtrack,A Memoir Blue - Original Soundtrack:171010:10720,A Memoir Blue - Original Soundtrack,171010,Steam,Steam,YYY,NaN,NaN,0.0,0.0,0.0
1,2010-01-01,1497450-store:10720,1497450,A Memoir Blue,A Memoir Blue:171010:10720,A Memoir Blue,171010,Steam,Steam,YYY,NaN,NaN,0.0,0.0,0.0
2,2010-01-01,1116060-store:10720,1116060,Ashen - Nightstorm Isle,Ashen - Nightstorm Isle DLC:171010:10720,Ashen - Nightstorm Isle DLC,171010,Steam,Steam,YYY,NaN,NaN,0.0,0.0,0.0
3,2010-01-01,1202450-store:10720,1202450,Ashen - Original Soundtrack,Ashen - Original Soundtrack:171010:10720,Ashen - Original Soundtrack,171010,Steam,Steam,YYY,NaN,NaN,0.0,0.0,0.0
4,2010-01-01,649950-store:10720,649950,Ashen,Ashen:171010:10720,Ashen,171010,Steam,Steam,YYY,NaN,NaN,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1340699,2025-09-23,1299460-store:10720,1299460,Wanderstop,Wanderstop:171010:10720,Wanderstop,171010,Steam,Steam,YYY,NaN,NaN,30.0,16.0,2.0
1340700,2025-09-23,1792460-store:10720,1792460,We Kill Monsters,We Kill Monsters:171010:10720,We Kill Monsters,171010,Steam,Steam,YYY,NaN,NaN,6.0,1.0,0.0
1340701,2025-09-23,501300-store:10720,501300,What Remains of Edith Finch,What Remains of Edith Finch:171010:10720,What Remains of Edith Finch,171010,Steam,Steam,YYY,NaN,NaN,83.0,9.0,1.0
1340702,2025-09-23,1497460-store:10720,1497460,Wheel World,Wheel World:171010:10720,Wheel World,171010,Steam,Steam,YYY,NaN,NaN,16.0,9.0,2.0
1340703,2025-09-23,1875320-store:10720,1875320,to a T,to a T:171010:10720,to a T,171010,Steam,Steam,YYY,NaN,NaN,3.0,1.0,0.0

In [6]:
df_wl.head().columns

Index(['date', 'unique_sku_id', 'base_sku_id', 'human_name', 'product_id',
       'product_name', 'portal_platform_region_id', 'portal', 'store',
       'country_code', 'non_owner_visits', 'non_owner_impressions', 'adds',
       'deletes', 'purchases_activations_gifts'],
      dtype='object')

In [7]:
df_wl = df_wl.groupby(["date",'product_name'])[['adds','deletes','purchases_activations_gifts','non_owner_visits','non_owner_impressions']].sum().sort_values(by='date',ascending=False).reset_index()

In [8]:
df = df.groupby(["date",'product_name'])[['all_units','units_returned','units_freely_distributed','units_sold_in_retail','gross_revenue', 'gross_returned']].sum().sort_values(by='date',ascending=False).reset_index()

In [9]:
df.columns

Index(['date', 'product_name', 'all_units', 'units_returned',
       'units_freely_distributed', 'units_sold_in_retail', 'gross_revenue',
       'gross_returned'],
      dtype='object')

In [10]:
product_name = "LEGO Voyagers - Friend’s Pass"

In [11]:
df.product_name.unique()

array(['What Remains of Edith Finch', 'Lorelei and the Laser Eyes',
       'Ashen - Nightstorm Isle DLC', 'Cocoon', 'Donut County',
       'Florence', 'Gone Home', 'Gorogoa', 'Hindsight', 'I Am Dead',
       'Kentucky Route Zero: TV Edition', 'LEGO Voyagers',
       'LEGO Voyagers - Friend’s Pass', 'Ashen', 'Maquette',
       'Sayonara Wild Hearts', 'Twelve Minutes', 'The Pathless', 'Stray',
       'Solar Ash', 'Storyteller',
       'Outer Wilds - Archaeologist Edition BUNDLE', 'Outer Wilds',
       'Open Roads', 'Neon White', 'Mundaun', 'If Found...', 'Journey',
       'LEGO Voyagers - Soundtrack', 'LEGO Voyagers - Soundtrack Bundle',
       'Last Stop', 'Lushfoil Photography Sim', 'Hohokum', 'Flower',
       'Demi', 'D-topia', 'A Memoir Blue',
       'Neon White - Original Soundtrack', 'Stray - Original Soundtrack',
       'to a T', 'Wheel World',
       'What Remains of Edith Finch - Original Soundtrack', 'Wattam',
       'Wanderstop', 'Thirsty Suitors', 'The Unfinished Swan',
       'Telling Lies', 'The Artful Escape', 'Project Insomnia',
       'Outer Wilds - Echoes of the Eye DLC',
       'Outer Wilds - Original Soundtrack',
       'Storyteller - Original Soundtrack', 'People of Note', 'Skin Deep',
       'Flock', 'Bounty Star', 'Big Maze', 'Ashen Definitive Edition',
       'Wheel World - Soundtrack', 'Wanderstop - Soundtrack',
       'If Found... - Original Soundtrack',
       'Donut County - Original Soundtrack', 'Skin Deep Soundtrack',
       'Gorogoa - Original Soundtrack',
       'Twelve Minutes - Original Soundtrack',
       'The Pathless - Original Soundtrack',
       'Lorelei and the Laser Eyes - Original Soundtrack', 'BattleSage',
       'Sayonara Wild Hearts - Original Soundtrack', 'Mixtape',
       'Cocoon - Soundtrack', 'to a T - Soundtrack', 'Heron',
       'A Memoir Blue - Original Soundtrack', 'Forever Ago',
       'Flock - Original Soundtrack', 'Hindsight - Original Soundtrack',
       'Florence - Original Soundtrack', 'Morsels',
       'The Artful Escape - Original Soundtrack',
       'Ashen - Original Soundtrack',
       'Thirsty Suitors - Original Soundtrack',
       'Solar Ash - Original Soundtrack', 'Wattam - Original Soundtrack',
       'Faraway', 'Telling Lies - Original Soundtrack',
       'Last Stop - Original Soundtrack',
       'Wheel World + Soundtrack Bundle',
       'I Am Dead - Original Soundtrack', 'REV', 'No Goblin Game 3',
       'Due Process', 'Skin Deep - Soundtrack Edition', 'Saru',
       'Big Hops', 'We Kill Monsters', 'A Person A Problem',
       'Blade Runner 2033: Labyrinth', 'The Lost Wild', 'First Ascent',
       'Due Process - Original Soundtrack'], dtype=object)

In [12]:
df.query("product_name ==@product_name")

,date,product_name,all_units,units_returned,units_freely_distributed,units_sold_in_retail,gross_revenue,gross_returned
12,2025-09-23,LEGO Voyagers - Friend’s Pass,499,0,467,0,620.81,0.0
26,2025-09-22,LEGO Voyagers - Friend’s Pass,2738,0,2454,0,6582.43,0.0
81,2025-09-21,LEGO Voyagers - Friend’s Pass,9448,0,8729,0,16605.08,0.0
143,2025-09-20,LEGO Voyagers - Friend’s Pass,10340,0,9510,0,19060.95,0.0
198,2025-09-19,LEGO Voyagers - Friend’s Pass,7364,1,6780,0,13361.27,0.0
253,2025-09-18,LEGO Voyagers - Friend’s Pass,7042,0,6566,0,10928.71,0.0
304,2025-09-17,LEGO Voyagers - Friend’s Pass,8763,0,8185,0,13422.86,0.0
368,2025-09-16,LEGO Voyagers - Friend’s Pass,10709,0,9981,0,16740.83,0.0
420,2025-09-15,LEGO Voyagers - Friend’s Pass,8682,0,7825,0,20163.79,0.0
532,2025-09-13,LEGO Voyagers - Friend’s Pass,2,0,2,0,0.00,0.0
643,2025-09-11,LEGO Voyagers - Friend’s Pass,2,0,2,0,0.00,0.0
697,2025-09-10,LEGO Voyagers - Friend’s Pass,1,0,1,0,0.00,0.0
750,2025-09-09,LEGO Voyagers - Friend’s Pass,2,0,2,0,0.00,0.0
803,2025-09-08,LEGO Voyagers - Friend’s Pass,1,0,1,0,0.00,0.0
1025,2025-09-04,LEGO Voyagers - Friend’s Pass,1,0,1,0,0.00,0.0

In [13]:
data = df.merge(df_wl, on=['product_name', 'date'], how='right')

In [14]:
data.groupby("product_name")['units_returned'].sum().sort_values(ascending=False)

product_name
Stray                          258044.0
Outer Wilds                    253931.0
Journey                        126329.0
What Remains of Edith Finch    110430.0
Storyteller                     57494.0
                                 ...
D-topia                             0.0
Demi                                0.0
Saru                                0.0
Dreamfeel Next                      0.0
Faraway                             0.0
Name: units_returned, Length: 105, dtype: float64

In [15]:
data.groupby("product_name")['all_units'].get_group("Wheel World").sum() - data.groupby("product_name")['units_freely_distributed'].get_group("Wheel World").sum() - data.groupby("product_name")['units_sold_in_retail'].get_group("Wheel World").sum() -data.groupby("product_name")['units_returned'].get_group("Wheel World").sum()

14720.0

In [16]:
data

,date,product_name,all_units,units_returned,units_freely_distributed,units_sold_in_retail,gross_revenue,gross_returned,adds,deletes,purchases_activations_gifts,non_owner_visits,non_owner_impressions
0,2025-09-23,to a T,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,0.0,0.0,0.0
1,2025-09-23,Flower,NaN,NaN,NaN,NaN,NaN,NaN,4.0,6.0,0.0,0.0,0.0
2,2025-09-23,Lushfoil Photography Sim,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,4.0,0.0,0.0
3,2025-09-23,Lorelei and the Laser Eyes,3.0,0.0,0.0,0.0,57.85,0.0,9.0,3.0,0.0,0.0,0.0
4,2025-09-23,Last Stop,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
444986,2010-01-01,Storyteller,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
444987,2010-01-01,Storyteller - Original Soundtrack,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
444988,2010-01-01,Stray,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
444989,2010-01-01,Stray - Original Soundtrack,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
444990,2010-01-01,A Memoir Blue,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0

stop

In [17]:
data['date'] = pd.to_datetime(data['date'])
#data['date_str'] = data['date'].dt.strftime("%Y-%m-%d")

In [18]:
data['units_excl_refunds'] = data['all_units'] - data['units_returned'] - data['units_freely_distributed']- data['units_sold_in_retail']
data['revenue_excl_refunds'] = data['gross_revenue'] - data['gross_returned']
data['units_excl_refunds_incl_free'] = data['all_units'] - data['units_returned']

data['date_str'] = data['date'].dt.strftime("%Y-%m-%d")

In [19]:
grouped = data.groupby('product_name')

In [20]:
grouped.get_group("Wheel World")['units_returned'].sum()

888.0

In [21]:
rename_dict = {
'date':'Date', 
'product_name':'Product', 
'revenue_excl_refunds':'Revenue (excl. refunds)', 
'units_excl_refunds':'Units (excl. refunds)',
'units_excl_refunds_incl_free':'units_excl_refunds_incl_free',

'units_freely_distributed':'Free units', 
    'adds':'Wishlist adds', 
    'non_owner_visits':'Non-owner visits',
       'non_owner_impressions':'Non-owner impressions', 
'units_returned': 'Refunded units',
    'deletes':"wl_deletes",
    'purchases_activations_gifts':"wl_activations",
    
}

In [22]:
data.rename(rename_dict, axis=1, inplace=True)
#data = data.drop_duplicates(subset=['day', 'product'])
#data['day'] = pd.to_datetime(test['day'] )
#data = data.sort_values(by='day')

data.query("Date=='2025-08-10' & Product =='Solar Ash'")

In [23]:
product_name = "LEGO Voyagers - Friend’s Pass"

In [24]:
data.query("Product ==@product_name")

,Date,Product,all_units,Refunded units,Free units,units_sold_in_retail,gross_revenue,gross_returned,Wishlist adds,wl_deletes,wl_activations,Non-owner visits,Non-owner impressions,Units (excl. refunds),Revenue (excl. refunds),units_excl_refunds_incl_free
53,2025-09-22,LEGO Voyagers - Friend’s Pass,2738.0,0.0,2454.0,0.0,6582.43,0.0,1.0,0.0,0.0,7.0,33.0,284.0,6582.43,2738.0
142,2025-09-21,LEGO Voyagers - Friend’s Pass,9448.0,0.0,8729.0,0.0,16605.08,0.0,1377.0,2.0,0.0,81.0,899.0,719.0,16605.08,9448.0
232,2025-09-20,LEGO Voyagers - Friend’s Pass,10340.0,0.0,9510.0,0.0,19060.95,0.0,2006.0,2.0,1.0,82.0,912.0,830.0,19060.95,10340.0
321,2025-09-19,LEGO Voyagers - Friend’s Pass,7364.0,1.0,6780.0,0.0,13361.27,0.0,1395.0,3.0,3.0,111.0,916.0,583.0,13361.27,7363.0
414,2025-09-18,LEGO Voyagers - Friend’s Pass,7042.0,0.0,6566.0,0.0,10928.71,0.0,1384.0,6.0,3.0,89.0,928.0,476.0,10928.71,7042.0
500,2025-09-17,LEGO Voyagers - Friend’s Pass,8763.0,0.0,8185.0,0.0,13422.86,0.0,1610.0,1.0,3.0,98.0,1076.0,578.0,13422.86,8763.0
593,2025-09-16,LEGO Voyagers - Friend’s Pass,10709.0,0.0,9981.0,0.0,16740.83,0.0,1644.0,1.0,4.0,111.0,1134.0,728.0,16740.83,10709.0
685,2025-09-15,LEGO Voyagers - Friend’s Pass,8682.0,0.0,7825.0,0.0,20163.79,0.0,1589.0,1.0,1.0,134.0,1217.0,857.0,20163.79,8682.0
774,2025-09-14,LEGO Voyagers - Friend’s Pass,NaN,NaN,NaN,NaN,NaN,NaN,2097.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
863,2025-09-13,LEGO Voyagers - Friend’s Pass,2.0,0.0,2.0,0.0,0.00,0.0,2746.0,0.0,0.0,0.0,0.0,0.0,0.00,2.0
951,2025-09-12,LEGO Voyagers - Friend’s Pass,NaN,NaN,NaN,NaN,NaN,NaN,2896.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1038,2025-09-11,LEGO Voyagers - Friend’s Pass,2.0,0.0,2.0,0.0,0.00,0.0,776.0,0.0,0.0,0.0,0.0,0.0,0.00,2.0
1130,2025-09-10,LEGO Voyagers - Friend’s Pass,1.0,0.0,1.0,0.0,0.00,0.0,944.0,0.0,0.0,0.0,0.0,0.0,0.00,1.0
1227,2025-09-09,LEGO Voyagers - Friend’s Pass,2.0,0.0,2.0,0.0,0.00,0.0,594.0,0.0,0.0,0.0,0.0,0.0,0.00,2.0
1318,2025-09-08,LEGO Voyagers - Friend’s Pass,1.0,0.0,1.0,0.0,0.00,0.0,451.0,0.0,0.0,0.0,0.0,0.0,0.00,1.0
1407,2025-09-07,LEGO Voyagers - Friend’s Pass,NaN,NaN,NaN,NaN,NaN,NaN,677.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1496,2025-09-06,LEGO Voyagers - Friend’s Pass,NaN,NaN,NaN,NaN,NaN,NaN,729.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1584,2025-09-05,LEGO Voyagers - Friend’s Pass,NaN,NaN,NaN,NaN,NaN,NaN,591.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1675,2025-09-04,LEGO Voyagers - Friend’s Pass,1.0,0.0,1.0,0.0,0.00,0.0,559.0,0.0,0.0,0.0,0.0,0.0,0.00,1.0
1767,2025-09-03,LEGO Voyagers - Friend’s Pass,NaN,NaN,NaN,NaN,NaN,NaN,473.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1855,2025-09-02,LEGO Voyagers - Friend’s Pass,NaN,NaN,NaN,NaN,NaN,NaN,505.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1945,2025-09-01,LEGO Voyagers - Friend’s Pass,NaN,NaN,NaN,NaN,NaN,NaN,408.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2033,2025-08-31,LEGO Voyagers - Friend’s Pass,NaN,NaN,NaN,NaN,NaN,NaN,484.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2123,2025-08-30,LEGO Voyagers - Friend’s Pass,NaN,NaN,NaN,NaN,NaN,NaN,422.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2212,2025-08-29,LEGO Voyagers - Friend’s Pass,NaN,NaN,NaN,NaN,NaN,NaN,417.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2301,2025-08-28,LEGO Voyagers - Friend’s Pass,NaN,NaN,NaN,NaN,NaN,NaN,411.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2391,2025-08-27,LEGO Voyagers - Friend’s Pass,NaN,NaN,NaN,NaN,NaN,NaN,382.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN

grouped.get_group(product_name)

In [25]:
data[['Date', 'Product', 'Revenue (excl. refunds)', 'Units (excl. refunds)','units_excl_refunds_incl_free',
       'Free units', 'Wishlist adds', 'Non-owner visits',
       'Non-owner impressions', 'Refunded units','wl_deletes','wl_activations']].sort_values(by='Date').query("Date=='2025-09-08' & Product ==@product_name")

/var/folders/vh/qvl8gx_d2m370qv72srt5r1m0000gp/T/ipykernel_93621/3020157460.py:3: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  'Non-owner impressions', 'Refunded units','wl_deletes','wl_activations']].sort_values(by='Date').query("Date=='2025-09-08' & Product ==@product_name")

,Date,Product,Revenue (excl. refunds),Units (excl. refunds),units_excl_refunds_incl_free,Free units,Wishlist adds,Non-owner visits,Non-owner impressions,Refunded units,wl_deletes,wl_activations
1318,2025-09-08,LEGO Voyagers - Friend’s Pass,0.0,0.0,1.0,1.0,451.0,0.0,0.0,0.0,0.0,0.0

In [26]:
export_df = data[['Date', 'Product', 'Revenue (excl. refunds)', 'Units (excl. refunds)','units_excl_refunds_incl_free',
       'Free units', 'Wishlist adds', 'Non-owner visits',
       'Non-owner impressions', 'Refunded units','wl_deletes','wl_activations']].sort_values(by='Date')

export_df.query("Date=='2025-09-18' & Product ==@product_name")

/var/folders/vh/qvl8gx_d2m370qv72srt5r1m0000gp/T/ipykernel_93621/3129069852.py:5: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  export_df.query("Date=='2025-09-18' & Product ==@product_name")

,Date,Product,Revenue (excl. refunds),Units (excl. refunds),units_excl_refunds_incl_free,Free units,Wishlist adds,Non-owner visits,Non-owner impressions,Refunded units,wl_deletes,wl_activations
414,2025-09-18,LEGO Voyagers - Friend’s Pass,10928.71,476.0,7042.0,6566.0,1384.0,89.0,928.0,0.0,6.0,3.0

In [27]:
export_df.tail(25)

,Date,Product,Revenue (excl. refunds),Units (excl. refunds),units_excl_refunds_incl_free,Free units,Wishlist adds,Non-owner visits,Non-owner impressions,Refunded units,wl_deletes,wl_activations
19,2025-09-23,A Memoir Blue,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,2.0,0.0
10,2025-09-23,Florence,21.05,13.0,13.0,0.0,23.0,0.0,0.0,0.0,4.0,1.0
20,2025-09-23,Morsels,NaN,NaN,NaN,NaN,1.0,0.0,0.0,NaN,1.0,0.0
30,2025-09-23,The Pathless,8.37,1.0,1.0,0.0,5.0,0.0,0.0,0.0,10.0,0.0
22,2025-09-23,Neon White,8.88,1.0,1.0,0.0,24.0,0.0,0.0,0.0,10.0,1.0
41,2025-09-23,Outer Wilds,241.67,18.0,18.0,0.0,160.0,0.0,0.0,0.0,39.0,15.0
40,2025-09-23,Outer Wilds - Echoes of the Eye DLC,NaN,NaN,NaN,NaN,12.0,0.0,0.0,NaN,2.0,2.0
39,2025-09-23,Sayonara Wild Hearts,7.79,1.0,1.0,0.0,3.0,0.0,0.0,0.0,5.0,0.0
38,2025-09-23,Skin Deep,NaN,NaN,NaN,NaN,6.0,0.0,0.0,NaN,3.0,1.0
37,2025-09-23,Solar Ash,29.38,2.0,2.0,0.0,5.0,0.0,0.0,0.0,2.0,0.0
36,2025-09-23,Storyteller,84.45,9.0,9.0,0.0,35.0,0.0,0.0,0.0,15.0,3.0
35,2025-09-23,Stray,854.21,44.0,45.0,1.0,96.0,0.0,0.0,0.0,59.0,9.0
34,2025-09-23,Stray - Original Soundtrack,NaN,NaN,NaN,NaN,1.0,0.0,0.0,NaN,0.0,0.0
21,2025-09-23,Gorogoa,76.09,25.0,25.0,0.0,7.0,0.0,0.0,0.0,2.0,0.0
33,2025-09-23,Wheel World,NaN,NaN,NaN,NaN,16.0,0.0,0.0,NaN,9.0,2.0
31,2025-09-23,The Lost Wild,NaN,NaN,NaN,NaN,14.0,0.0,0.0,NaN,8.0,0.0
29,2025-09-23,Thirsty Suitors,NaN,NaN,NaN,NaN,4.0,0.0,0.0,NaN,2.0,0.0
28,2025-09-23,Twelve Minutes,8.04,1.0,1.0,0.0,12.0,0.0,0.0,0.0,10.0,0.0
27,2025-09-23,Wanderstop,NaN,NaN,NaN,NaN,30.0,0.0,0.0,NaN,16.0,2.0
26,2025-09-23,We Kill Monsters,NaN,NaN,NaN,NaN,6.0,0.0,0.0,NaN,1.0,0.0
25,2025-09-23,What Remains of Edith Finch,93.80,19.0,19.0,0.0,83.0,0.0,0.0,0.0,9.0,1.0
24,2025-09-23,Open Roads,10.34,1.0,1.0,0.0,2.0,0.0,0.0,0.0,3.0,0.0
23,2025-09-23,Telling Lies,NaN,NaN,NaN,NaN,7.0,0.0,0.0,NaN,0.0,0.0
32,2025-09-23,The Artful Escape,NaN,NaN,NaN,NaN,3.0,0.0,0.0,NaN,2.0,0.0
0,2025-09-23,to a T,NaN,NaN,NaN,NaN,3.0,0.0,0.0,NaN,1.0,0.0

In [28]:
export_df.to_csv("DB_Update/API/bulkAPI_Export.csv", index=False)

In [29]:
export_df['Product'].unique()

array(['A Memoir Blue', 'Florence', 'Ashen',
       'Ashen - Nightstorm Isle DLC', 'Ashen - Original Soundtrack',
       'BattleSage', 'Big Hops', 'Blade Runner 2033: Labyrinth',
       'Bounty Star', 'Cocoon', 'Cocoon - Soundtrack', 'Donut County',
       'Donut County - Original Soundtrack', 'Due Process',
       'Due Process - Original Soundtrack', 'Flock',
       'Florence - Original Soundtrack', 'Morsels', 'Forever Ago',
       'Flower', 'If Found...', 'Gorogoa',
       'Gorogoa - Original Soundtrack', 'Hindsight',
       'Hindsight - Original Soundtrack', 'Hohokum', 'I Am Dead',
       'Flock - Original Soundtrack', 'I Am Dead - Original Soundtrack',
       'If Found... - Original Soundtrack', 'Journey', 'Last Stop',
       'Lorelei and the Laser Eyes',
       'Lorelei and the Laser Eyes - Original Soundtrack',
       'Lushfoil Photography Sim', 'Maquette',
       'Last Stop - Original Soundtrack', 'Mixtape',
       'Stray - Original Soundtrack', 'Mundaun', 'Telling Lies',
       'Neon White - Original Soundtrack', 'Open Roads', 'Outer Wilds',
       'Outer Wilds - Echoes of the Eye DLC',
       'Outer Wilds - Original Soundtrack', 'Project D',
       'Sayonara Wild Hearts',
       'Sayonara Wild Hearts - Original Soundtrack', 'Skin Deep',
       'Solar Ash', 'Solar Ash - Original Soundtrack', 'Storyteller',
       'Storyteller - Original Soundtrack', 'Stray',
       'Telling Lies - Original Soundtrack', 'The Artful Escape',
       'A Memoir Blue - Original Soundtrack', 'to a T',
       'The Artful Escape - Original Soundtrack',
       'Twelve Minutes - Original Soundtrack', 'The Lost Wild',
       'The Pathless', 'The Pathless - Original Soundtrack',
       'Thirsty Suitors', 'Thirsty Suitors - Original Soundtrack',
       'Twelve Minutes', 'The Unfinished Swan', 'Neon White', 'Wattam',
       'Wattam - Original Soundtrack', 'We Kill Monsters',
       'What Remains of Edith Finch',
       'What Remains of Edith Finch - Original Soundtrack', 'Wheel World',
       'Wanderstop', 'Gone Home', 'Kentucky Route Zero: TV Edition',
       'No Goblin Game 3', 'LEGO Voyagers', 'Perfect Stride',
       'People of Note', 'Outer Wilds - Archaeologist Edition BUNDLE',
       'Demi', 'Heron', 'BML', 'First Ascent', 'Dreamfeel Next',
       'D-topia', 'Cannula', 'REV', 'Saru',
       'Traveler - A Journey Symphony', 'Faraway', 'Big Maze',
       'Wanderstop - Soundtrack', 'Skin Deep Soundtrack',
       'Wheel World - Soundtrack', 'to a T - Soundtrack', 'Snap & Grab',
       'Project Uncanyon', 'Journey - Original Soundtrack',
       'Lushfoil Photography Sim VR', 'LEGO Voyagers - Soundtrack',
       'LEGO Voyagers - Friend’s Pass'], dtype=object)

In [30]:
stop

NameError: name 'stop' is not defined

In [ ]:
stop

data.rename(rename_dict, axis=1, inplace=True)
data = data.drop_duplicates(subset=['day', 'product'])
data['day'] = pd.to_datetime(test['day'] )
data = data.sort_values(by='day')

data['cume_units'] = data.groupby('product')['units'].cumsum()
data['cume_revs'] = data.groupby('product')['revenue'].cumsum()

data['cume_free_units'] = data.groupby('product')['free_units'].cumsum()
data['cume_wishlist_adds'] = data.groupby('product')['wishlist_adds'].cumsum()
data['cume_visits'] = data.groupby('product')['visits'].cumsum()
data['cume_impressions'] = data.groupby('product')['impressions'].cumsum()
data['cume_refunded_units'] =data.groupby('product')['refunded_units'].cumsum()

cols_ = ['day',
         'product',
         'units',
         'cume_units',
         'revenue',
         'cume_revs',
         'free_units',
         'cume_free_units',
         'wishlist_adds',
         'cume_wishlist_adds',
         'visits',
         'cume_visits',
         'impressions',
         'cume_impressions',
         'refunded_units',
         'cume_refunded_units']

value_cols = [

'units',
         'cume_units',
'units_percent_of_max',
         'revenue',
         'cume_revs',
'revs_percent_of_max',
'avg_price',
         'free_units',
         'cume_free_units',
         'wishlist_adds',
         'cume_wishlist_adds',
         'visits',
         'cume_visits',
         'impressions',
         'cume_impressions',
         'refunded_units',
         'cume_refunded_units'

]

data

export_df = data.groupby(['product', 'day'])[value_cols].sum().sort_values(by='date', ascending=True).reset_index()

export_df['date_str'] = export_df['date'].dt.strftime("%Y-%m-%d")
export_df['units_excl_refunds'] = export_df['all_units'] - export_df['units_returned'] - export_df['units_freely_distributed']
export_df['revenue_excl_refunds'] = export_df['gross_revenue'] - export_df['gross_returned']
export_df['product_day'] = export_df['product_name'] + "_"+export_df['date_str']
export_df['_id'] = export_df['product_day']
export_df = export_df.set_index('_id')

export_df

folder_path = "wishlists/Annapurna Interactive Historical Revenues - releases_dates.csv"
dates  = pd.read_csv(folder_path)
dates = dates.dropna(subset='pc_release_date')
dates['pc_release_date'] = pd.to_datetime(dates['pc_release_date'])
release_date_dict = dates.groupby('product')['pc_release_date'].min().to_dict()

df['release_date'] = pd.to_datetime(df['Day'])


df["units_percent_of_max"] = df["cume_units"] / df.groupby("product")["cume_units"].transform("max")
df["revs_percent_of_max"] = df["cume_revs"] / df.groupby("product")["cume_revs"].transform("max")

df['release_date'] = pd.to_datetime(df['Day'])
df['Day'] = pd.to_datetime(df['Day']).dt.to_pydatetime()
df['release_date'] = df.groupby('product')['release_date'].transform('min')
df['release_date'] = df['product'].map(release_date_dict)
df["DAR"] = (df["Day"] - df["release_date"]).dt.days
#df["DAR"] = df.groupby("product")["DAR"].transform(lambda x: x.clip(lower=0))

df["Weeks_from_Release"] = (df["DAR"] // 7) + 1  # Week 1 starts at 0-7 days

df["avg_price"] = df["revenue"] / df["units"]

df = df.groupby(["product", "Weeks_from_Release",'DAR','Day','release_date'], as_index=False)[value_cols].max()

df.columns = [col.strip().replace(" ", "_").lower() for col in df.columns]

df['product_day'] = df['product'].astype(str) + '_' + df['day'].astype(str)

df['unit_daily_delta']  = df.groupby('product')['units'].pct_change()
df['rev_daily_delta']  = df.groupby('product')['revenue'].pct_change()

records = df.to_dict(orient="records")

records