In [1]:
## Download from IndieBI, details by product, All Games No Soundtrack, daily units

#TEST Data is using EXPORT function and seems to be working.

In [2]:
import pandas as pd
import glob
import os
import warnings

warnings.filterwarnings("ignore")

import pandas as pd
import glob
import os

# Define folder path
folder_path = "DB_Update/units/"

# Get all Excel files in the folder
excel_files = glob.glob(os.path.join(folder_path, "*.xlsx"))

# Read and combine all files, skipping first 2 rows
df_list = [pd.read_excel(f, skiprows=2).assign(filename=os.path.basename(f)) for f in excel_files]
combined_df = pd.concat(df_list, ignore_index=True)

combined_df

df = combined_df.drop_duplicates(subset=['Day', 'product'])
df

import pandas as pd
import glob
import os

# Define folder path
folder_path = "DB_Update/revs/"

# Get all Excel files in the folder
excel_files = glob.glob(os.path.join(folder_path, "*.xlsx"))

# Read and combine all files, skipping first 2 rows
df_list = [pd.read_excel(f, skiprows=2).assign(filename=os.path.basename(f)) for f in excel_files]
combined_df_revs = pd.concat(df_list, ignore_index=True)

revs = combined_df_revs.drop_duplicates(subset=['Day', 'product'])
revs

import pandas as pd
import glob
import os

# Define folder path
folder_path = "DB_Update/wishlists/"

# Get all Excel files in the folder
excel_files = glob.glob(os.path.join(folder_path, "*.xlsx"))

# Read and combine all files, skipping first 2 rows
df_list = [pd.read_excel(f, skiprows=2).assign(filename=os.path.basename(f)) for f in excel_files]
combined_df_wl = pd.concat(df_list, ignore_index=True)

wishlists = combined_df_wl.drop_duplicates(subset=['Day', 'product'])
wishlists

df = df.rename({"Selected Measure":"units"}, axis=1)
revs = revs.rename({"Selected Measure":"revenue"}, axis=1)
#wishlists = wishlists.rename({"Selected Measure":"wishlist_adds"}, axis=1)

df = df.drop("Blank Measure", axis=1)
revs = revs.drop("Blank Measure", axis=1)
#wishlists = wishlists.drop("Blank Measure", axis=1)

df = df.drop("filename", axis=1)
revs = revs.drop("filename", axis=1)
#wishlists = wishlists.drop("filename", axis=1)

df

revs

df['cume_units'] = df.groupby('product')['units'].cumsum()
revs['cume_revs'] = revs.groupby('product')['revenue'].cumsum()
#wishlists['cume_wishlists'] = wishlists.groupby('product')['wishlist_adds'].cumsum()

df = df.merge(revs,on=['product', 'Day'], how='left')
#df = df.merge(wishlists,on=['product', 'Day'], how='left')

## Export Test

for f in excel_files:
    try:
        df = pd.read_excel(f, skipfooter=2, engine='openpyxl')
        print(f"✔ Loaded: {f}")
    except Exception as e:
        print(f"❌ Failed to load: {f} — {e}")

In [4]:
import pandas as pd
import glob
import os

# Define folder path
folder_path = "DB_Update/test"

# Get all Excel files in the folder
excel_files = glob.glob(os.path.join(folder_path, "*.xlsx"))

# Read and combine all files, skipping first 2 rows
df_list = [pd.read_excel(f, skipfooter=2).assign(filename=os.path.basename(f)) for f in excel_files]
combined_test = pd.concat(df_list, ignore_index=True)

In [5]:
combined_test

,Date,Product,Revenue (excl. refunds),Units (excl. refunds),Free units,Wishlist adds,Non-owner visits,Non-owner impressions,Refunded units,filename
0,2016-12-18,A Memoir Blue,NaN,NaN,NaN,0.0,NaN,NaN,NaN,test_export_pre_2020.xlsx
1,2016-12-18,A Memoir Blue - Original Soundtrack,NaN,NaN,NaN,0.0,NaN,NaN,NaN,test_export_pre_2020.xlsx
2,2016-12-18,Ashen,NaN,NaN,NaN,0.0,NaN,NaN,NaN,test_export_pre_2020.xlsx
3,2016-12-18,Ashen - Nightstorm Isle DLC,NaN,NaN,NaN,0.0,NaN,NaN,NaN,test_export_pre_2020.xlsx
4,2016-12-18,Ashen - Original Soundtrack,NaN,NaN,NaN,0.0,NaN,NaN,NaN,test_export_pre_2020.xlsx
...,...,...,...,...,...,...,...,...,...,...
249459,2023-01-01,Wattam - Original Soundtrack,9.76,2.0,0.0,0.0,64.0,5301.0,0.0,test_export_2020_2023.xlsx
249460,2023-01-01,We Kill Monsters,NaN,NaN,NaN,0.0,NaN,NaN,NaN,test_export_2020_2023.xlsx
249461,2023-01-01,What Remains of Edith Finch,13015.52,3395.0,2587.0,1344.0,10336.0,554647.0,204.0,test_export_2020_2023.xlsx
249462,2023-01-01,What Remains of Edith Finch - Original Soundtrack,21.14,14.0,0.0,0.0,214.0,13025.0,1.0,test_export_2020_2023.xlsx
249463,2023-01-01,Wheel World,NaN,NaN,NaN,0.0,NaN,NaN,NaN,test_export_2020_2023.xlsx

In [6]:
rename_dict = {
'Date':'Day', 
    'Product':'product', 
    'Revenue (excl. refunds)':'revenue', 
    'Units (excl. refunds)':'units',
       'Free units':'free_units', 
    'Wishlist adds':'wishlist_adds', 
    'Non-owner visits':'visits',
       'Non-owner impressions':'impressions', 
    'Refunded units': 'refunded_units'
    
}

In [7]:
combined_test.rename(rename_dict, axis=1, inplace=True)

combined_test

In [8]:
test = combined_test.drop_duplicates(subset=['Day', 'product'])

In [9]:
test['Day'] = pd.to_datetime(test['Day'] )

In [10]:
test = test.sort_values(by='Day')

In [11]:
test['cume_units'] = test.groupby('product')['units'].cumsum()
test['cume_revs'] = test.groupby('product')['revenue'].cumsum()

test['cume_free_units'] = test.groupby('product')['free_units'].cumsum()
test['cume_wishlist_adds'] = test.groupby('product')['wishlist_adds'].cumsum()
test['cume_visits'] = test.groupby('product')['visits'].cumsum()
test['cume_impressions'] = test.groupby('product')['impressions'].cumsum()
test['cume_refunded_units'] = test.groupby('product')['refunded_units'].cumsum()

In [12]:
cols_ = ['Day',
         'product',
         'units',
         'cume_units',
         'revenue',
         'cume_revs',
         'free_units',
         'cume_free_units',
         'wishlist_adds',
         'cume_wishlist_adds',
         'visits',
         'cume_visits',
         'impressions',
         'cume_impressions',
         'refunded_units',
         'cume_refunded_units']

In [13]:
df = test[cols_]

In [14]:
test[cols_].query("product=='Wheel World' & Day =='2024-04-23'")

,Day,product,units,cume_units,revenue,cume_revs,free_units,cume_free_units,wishlist_adds,cume_wishlist_adds,visits,cume_visits,impressions,cume_impressions,refunded_units,cume_refunded_units
123500,2024-04-23,Wheel World,NaN,NaN,NaN,NaN,NaN,NaN,16.0,16952.0,228.0,127456.0,2215.0,1914216.0,NaN,NaN

In [15]:
df

,Day,product,units,cume_units,revenue,cume_revs,free_units,cume_free_units,wishlist_adds,cume_wishlist_adds,visits,cume_visits,impressions,cume_impressions,refunded_units,cume_refunded_units
0,2016-12-18,A Memoir Blue,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
54,2016-12-18,Stray,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
53,2016-12-18,Storyteller - Original Soundtrack,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
52,2016-12-18,Storyteller,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
51,2016-12-18,Solar Ash - Original Soundtrack,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162891,2025-08-12,Gorogoa - Original Soundtrack,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3049.0,NaN,NaN,NaN,NaN,NaN,NaN
162890,2025-08-12,Gorogoa,36.0,1154568.0,133.11,6547365.80,0.0,5649.0,56.0,976813.0,NaN,NaN,NaN,NaN,0.0,52979.0
162889,2025-08-12,Gone Home,7.0,155648.0,19.25,1024391.24,0.0,643.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,27.0
162909,2025-08-12,Morsels,NaN,NaN,NaN,NaN,NaN,NaN,8.0,68594.0,NaN,NaN,NaN,NaN,NaN,NaN
162952,2025-08-12,Wheel World,3.0,12854.0,57.61,228474.24,3.0,729.0,96.0,162317.0,NaN,NaN,NaN,NaN,0.0,792.0

stop

In [16]:
folder_path = "wishlists/Annapurna Interactive Historical Revenues - releases_dates.csv"
dates  = pd.read_csv(folder_path)
dates = dates.dropna(subset='pc_release_date')
dates['pc_release_date'] = pd.to_datetime(dates['pc_release_date'])
release_date_dict = dates.groupby('product')['pc_release_date'].min().to_dict()

In [17]:
release_date_dict.get("Donut County")

Timestamp('2018-08-28 00:00:00')

In [18]:
df['release_date'] = pd.to_datetime(df['Day'])


df["units_percent_of_max"] = df["cume_units"] / df.groupby("product")["cume_units"].transform("max")
df["revs_percent_of_max"] = df["cume_revs"] / df.groupby("product")["cume_revs"].transform("max")

In [19]:
df['release_date'] = pd.to_datetime(df['Day'])
df['Day'] = pd.to_datetime(df['Day']).dt.to_pydatetime()
df['release_date'] = df.groupby('product')['release_date'].transform('min')
df['release_date'] = df['product'].map(release_date_dict)
df["DAR"] = (df["Day"] - df["release_date"]).dt.days
#df["DAR"] = df.groupby("product")["DAR"].transform(lambda x: x.clip(lower=0))

df["Weeks_from_Release"] = (df["DAR"] // 7) + 1  # Week 1 starts at 0-7 days

In [20]:
df["avg_price"] = df["revenue"] / df["units"]

In [21]:
value_cols = [

'units',
         'cume_units',
'units_percent_of_max',
         'revenue',
         'cume_revs',
'revs_percent_of_max',
'avg_price',
         'free_units',
         'cume_free_units',
         'wishlist_adds',
         'cume_wishlist_adds',
         'visits',
         'cume_visits',
         'impressions',
         'cume_impressions',
         'refunded_units',
         'cume_refunded_units'

]

In [22]:
df = df.groupby(["product", "Weeks_from_Release",'DAR','Day','release_date'], as_index=False)[value_cols].max()

In [23]:
df.columns = [col.strip().replace(" ", "_").lower() for col in df.columns]
#df['date'] = pd.to_datetime(df['date'], format="%d %B, %Y")

In [24]:
df['product_day'] = df['product'].astype(str) + '_' + df['day'].astype(str)
#df.set_index('product_day', inplace=True)

In [25]:
df['unit_daily_delta']  = df.groupby('product')['units'].pct_change()
df['rev_daily_delta']  = df.groupby('product')['revenue'].pct_change()

df.query("product =='Stray'")

In [26]:
records = df.to_dict(orient="records")
records

[{'product': 'A Memoir Blue',
  'weeks_from_release': -274.0,
  'dar': -1922.0,
  'day': Timestamp('2016-12-18 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2016-12-18',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -274.0,
  'dar': -1921.0,
  'day': Timestamp('2016-12-19 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2016-12-19',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -274.0,
  'dar': -1920.0,
  'day': Timestamp('2016-12-20 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2016-12-20',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -274.0,
  'dar': -1919.0,
  'day': Timestamp('2016-12-21 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2016-12-21',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -273.0,
  'dar': -1918.0,
  'day': Timestamp('2016-12-22 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2016-12-22',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -273.0,
  'dar': -1917.0,
  'day': Timestamp('2016-12-23 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2016-12-23',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -273.0,
  'dar': -1916.0,
  'day': Timestamp('2016-12-24 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2016-12-24',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -273.0,
  'dar': -1915.0,
  'day': Timestamp('2016-12-25 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2016-12-25',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -273.0,
  'dar': -1914.0,
  'day': Timestamp('2016-12-26 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2016-12-26',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -273.0,
  'dar': -1913.0,
  'day': Timestamp('2016-12-27 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2016-12-27',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -273.0,
  'dar': -1912.0,
  'day': Timestamp('2016-12-28 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2016-12-28',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -272.0,
  'dar': -1911.0,
  'day': Timestamp('2016-12-29 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2016-12-29',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -272.0,
  'dar': -1910.0,
  'day': Timestamp('2016-12-30 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2016-12-30',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -272.0,
  'dar': -1909.0,
  'day': Timestamp('2016-12-31 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2016-12-31',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -272.0,
  'dar': -1908.0,
  'day': Timestamp('2017-01-01 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2017-01-01',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -272.0,
  'dar': -1907.0,
  'day': Timestamp('2017-01-02 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2017-01-02',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -272.0,
  'dar': -1906.0,
  'day': Timestamp('2017-01-03 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2017-01-03',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -272.0,
  'dar': -1905.0,
  'day': Timestamp('2017-01-04 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2017-01-04',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -271.0,
  'dar': -1904.0,
  'day': Timestamp('2017-01-05 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2017-01-05',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -271.0,
  'dar': -1903.0,
  'day': Timestamp('2017-01-06 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2017-01-06',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -271.0,
  'dar': -1902.0,
  'day': Timestamp('2017-01-07 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2017-01-07',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -271.0,
  'dar': -1901.0,
  'day': Timestamp('2017-01-08 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2017-01-08',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -271.0,
  'dar': -1900.0,
  'day': Timestamp('2017-01-09 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2017-01-09',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -271.0,
  'dar': -1899.0,
  'day': Timestamp('2017-01-10 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2017-01-10',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -271.0,
  'dar': -1898.0,
  'day': Timestamp('2017-01-11 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2017-01-11',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -270.0,
  'dar': -1897.0,
  'day': Timestamp('2017-01-12 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2017-01-12',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -270.0,
  'dar': -1896.0,
  'day': Timestamp('2017-01-13 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2017-01-13',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -270.0,
  'dar': -1895.0,
  'day': Timestamp('2017-01-14 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2017-01-14',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -270.0,
  'dar': -1894.0,
  'day': Timestamp('2017-01-15 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,
  'impressions': nan,
  'cume_impressions': nan,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2017-01-15',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -270.0,
  'dar': -1893.0,
  'day': Timestamp('2017-01-16 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': nan,
  'cume_visits': nan,

requests

In [27]:
df.query("product == 'to a T'").sort_values(by='cume_units',ascending=False)

,product,weeks_from_release,dar,day,release_date,units,cume_units,units_percent_of_max,revenue,cume_revs,...,cume_wishlist_adds,visits,cume_visits,impressions,cume_impressions,refunded_units,cume_refunded_units,product_day,unit_daily_delta,rev_daily_delta
143654,to a T,11.0,75.0,2025-08-11,2025-05-28,12.0,8818.0,1.000000,233.28,147869.07,...,65487.0,920.0,692293.0,37284.0,14227596.0,1.0,232.0,to a T_2025-08-11,0.000000,0.241644
143653,to a T,11.0,74.0,2025-08-10,2025-05-28,12.0,8806.0,0.998639,187.88,147635.79,...,65409.0,973.0,691373.0,36336.0,14190312.0,1.0,231.0,to a T_2025-08-10,-0.076923,-0.290376
143652,to a T,11.0,73.0,2025-08-09,2025-05-28,13.0,8794.0,0.997278,264.76,147447.91,...,65317.0,908.0,690400.0,35215.0,14153976.0,0.0,230.0,to a T_2025-08-09,-0.380952,-0.340540
143651,to a T,11.0,72.0,2025-08-08,2025-05-28,21.0,8781.0,0.995804,401.48,147183.15,...,65242.0,1044.0,689492.0,34713.0,14118761.0,0.0,230.0,to a T_2025-08-08,0.235294,0.256352
143650,to a T,11.0,71.0,2025-08-07,2025-05-28,17.0,8760.0,0.993423,319.56,146781.67,...,65159.0,1174.0,688448.0,38605.0,14084048.0,0.0,230.0,to a T_2025-08-07,0.307692,0.228321
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143561,to a T,-2.0,-18.0,2025-05-10,2025-05-28,NaN,NaN,NaN,NaN,NaN,...,30641.0,485.0,289605.0,7919.0,5305457.0,NaN,NaN,to a T_2025-05-10,NaN,NaN
143562,to a T,-2.0,-17.0,2025-05-11,2025-05-28,NaN,NaN,NaN,NaN,NaN,...,30724.0,529.0,290134.0,8039.0,5313496.0,NaN,NaN,to a T_2025-05-11,NaN,NaN
143565,to a T,-1.0,-14.0,2025-05-14,2025-05-28,NaN,NaN,NaN,NaN,NaN,...,30963.0,487.0,291716.0,7527.0,5336838.0,NaN,NaN,to a T_2025-05-14,NaN,NaN
143567,to a T,-1.0,-12.0,2025-05-16,2025-05-28,NaN,NaN,NaN,NaN,NaN,...,31176.0,761.0,293027.0,8701.0,5353188.0,NaN,NaN,to a T_2025-05-16,NaN,NaN
143655,to a T,11.0,76.0,2025-08-12,2025-05-28,NaN,NaN,NaN,NaN,NaN,...,65502.0,NaN,NaN,NaN,NaN,NaN,NaN,to a T_2025-08-12,0.000000,0.000000

In [28]:
stop

NameError: name 'stop' is not defined

folder_path = "units/cume_revenues.xlsx"


revs  = pd.read_excel(folder_path, skiprows=2)

In [29]:
from pymongo import UpdateOne

## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [30]:
from datetime import datetime
date_string = datetime.today().strftime('%Y-%m-%d')

In [31]:
db = client['ai_sales_data']
collection = db['units']

unique_products = collection.distinct("product", {"date": {"$gte": 2025-01-01}})

unique_products

In [32]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

In [33]:
#####
for batch in batchify(records, 5000):
    operations = [
        UpdateOne(
            {"_id": doc["product_day"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 259
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 3160
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 67
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 2944
Matched: 5000, Inserted: 0, Modified: 216
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 5000, Inserted: 0, Modified: 0
Matched: 3656, Inserted: 0, Modified: 0

collection.update_many({}, {"$unset": {"percent_of_max": ""}})

In [34]:
client.close()