In [7]:
## Download from IndieBI, details by product, All Games No Soundtrack, daily units

In [9]:
import pandas as pd
import glob
import os
import warnings

warnings.filterwarnings("ignore")

In [11]:


# Define folder path
folder_path = "/Users/dougs/Documents/GitHub/IndieBI-Sales-EDA/DB_Update/platform_breakout"

# Get all .xlsx files in the folder
files = glob.glob(f"{folder_path}/*.xlsx")

# Read all files into DataFrames and add filename column
#dfs = [pd.read_excel(file, skiprows=2).assign(Source=os.path.basename(file)) for file in files]


#df = pd.concat(dfs, ignore_index=True)

In [13]:
folder_path = "wishlists/Annapurna Interactive Historical Revenues - releases_dates.csv"
dates  = pd.read_csv(folder_path)
dates = dates.dropna(subset='pc_release_date')
dates['pc_release_date'] = pd.to_datetime(dates['pc_release_date'])
release_date_dict = dates.groupby('product')['pc_release_date'].min().to_dict()

In [15]:
release_date_dict.get("What Remains of Edith Finch")

Timestamp('2017-04-25 00:00:00')

In [17]:
df_list = []

for file in files:
    df = pd.read_excel(file, skiprows=2).assign(Source=os.path.basename(file))
    df['release_date'] = pd.to_datetime(df['Day'])
    df['release_date'] = df.groupby('product')['release_date'].transform('min')
    #df['release_date'] = df['product'].map(release_date_dict)

    df["DAR"] = (df["Day"] - df["release_date"]).dt.days

    df["Weeks_from_Release"] = (df["DAR"] // 7) + 1  # Week 1 starts at 0-7 days
    #df["avg_price"] = df["revenue"] / df["units"]
    df_list.append(df)

In [19]:
final_df = pd.concat(df_list, ignore_index=True)

In [21]:
final_df["Source"] = final_df["Source"].replace({
    "steam_2023TD.xlsx": "steam.xlsx",
    "steam_to2023.xlsx": "steam.xlsx"
})

In [23]:
final_df = final_df.drop_duplicates(subset=['product','Source',  'Day'], keep='last')

In [25]:
final_df.query("product =='Stray' & Day =='2025-08-15'").sort_values(by='release_date')

,Day,product,Selected Measure,Blank Measure,Source,release_date,DAR,Weeks_from_Release
136908,2025-08-15,Stray,319,NaN,playstation.xlsx,2022-07-18,1124,161
27660,2025-08-15,Stray,214,NaN,steam.xlsx,2023-01-01,957,137
184580,2025-08-15,Stray,1155,NaN,xbox.xlsx,2023-08-01,745,107
190004,2025-08-15,Stray,20,NaN,apple.xlsx,2024-05-14,458,66
197452,2025-08-15,Stray,12,NaN,humble.xlsx,2024-07-11,400,58
95553,2025-08-15,Stray,648,NaN,nintendo.xlsx,2024-11-12,276,40

In [11]:
final_df.query("Source == 'steam.xlsx'").groupby("product")['Day'].max()

product
A Memoir Blue                         2025-08-17
Ashen                                 2025-08-16
Ashen - Nightstorm Isle DLC           2025-08-12
Cocoon                                2025-08-17
Donut County                          2025-08-17
Due Process                           2022-07-31
Flock                                 2025-08-17
Florence                              2025-08-17
Flower                                2025-08-17
Gorogoa                               2025-08-17
Hindsight                             2025-08-08
Hohokum                               2025-08-13
I Am Dead                             2025-08-14
If Found...                           2025-08-16
Journey                               2025-08-17
Last Stop                             2025-08-17
Lorelei and the Laser Eyes            2025-08-17
Lushfoil Photography Sim              2025-08-17
Maquette                              2025-08-16
Mundaun                               2025-08-16
Neon White                            2025-08-17
Open Roads                            2025-08-17
Outer Wilds                           2025-08-17
Outer Wilds - Echoes of the Eye DLC   2025-08-17
Sayonara Wild Hearts                  2025-08-17
Skin Deep                             2025-08-17
Solar Ash                             2025-08-17
Storyteller                           2025-08-17
Stray                                 2025-08-17
Telling Lies                          2025-08-17
The Artful Escape                     2025-08-17
The Pathless                          2025-08-17
The Unfinished Swan                   2025-08-17
Thirsty Suitors                       2025-08-10
Twelve Minutes                        2025-08-17
Wanderstop                            2025-08-17
Wattam                                2025-08-17
What Remains of Edith Finch           2025-08-17
Wheel World                           2025-08-17
to a T                                2025-08-17
Name: Day, dtype: datetime64[ns]

In [12]:
final_df['Day'] = pd.to_datetime(final_df['Day'])
final_df = final_df.sort_values(by='Day')
final_df['release_date'] = pd.to_datetime(final_df['release_date'])

In [13]:
final_df.query("product =='Stray' & Day =='2025-06-25'")

,Day,product,Selected Measure,Blank Measure,Source,release_date,DAR,Weeks_from_Release
135491,2025-06-25,Stray,329,NaN,playstation.xlsx,2022-07-18,1073,154
197375,2025-06-25,Stray,8,NaN,humble.xlsx,2024-07-11,349,50
183599,2025-06-25,Stray,103,NaN,xbox.xlsx,2023-08-01,694,100
25861,2025-06-25,Stray,172,NaN,steam.xlsx,2023-01-01,906,130
94150,2025-06-25,Stray,499,NaN,nintendo.xlsx,2024-11-12,225,33
189426,2025-06-25,Stray,15,NaN,apple.xlsx,2024-05-14,407,59

In [14]:
pivot_df = final_df.pivot(index=['product','Day'], columns='Source',values='Selected Measure').reset_index()

In [15]:
pivot_df.query("product =='Stray' & Day =='2025-06-25'")

Source,product,Day,apple.xlsx,epic.xlsx,gog.xlsx,google.xlsx,humble.xlsx,nintendo.xlsx,playstation.xlsx,steam.xlsx,xbox.xlsx
49380,Stray,2025-06-25,15.0,NaN,NaN,NaN,8.0,499.0,329.0,172.0,103.0

pivot_df['Day'] = pd.to_datetime(pivot_df['Day'], errors='coerce')
pivot_df['release_date'] = pd.to_datetime(pivot_df['release_date'], errors='coerce')

In [16]:
## Add Platform Breakout Here

In [17]:
col_rename_dict = {'apple.xlsx': 'apple_units',
                   'epic.xlsx': 'epic_units',
  'gog.xlsx':  'gog_units',
   'google.xlsx':    'google_units',
    'humble.xlsx' :     'humble_units',
    'nintendo.xlsx' : 'nintendo_units',
  'playstation.xlsx' :   'playstation_units',
    'steam.xlsx' :  'steam_units',
   'xbox.xlsx': 'xbox_units'}

In [18]:
pivot_df = pivot_df.rename(col_rename_dict, axis=1)
pivot_df =  pivot_df.fillna(0)

In [19]:
pivot_df

Source,product,Day,apple_units,epic_units,gog_units,google_units,humble_units,nintendo_units,playstation_units,steam_units,xbox_units
0,A Memoir Blue,2022-03-24,0.0,0.0,0.0,0.0,6.0,56.0,227.0,370.0,0.0
1,A Memoir Blue,2022-03-25,0.0,0.0,0.0,0.0,0.0,93.0,229.0,197.0,0.0
2,A Memoir Blue,2022-03-26,0.0,0.0,0.0,0.0,2.0,94.0,123.0,118.0,0.0
3,A Memoir Blue,2022-03-27,0.0,0.0,0.0,0.0,1.0,102.0,94.0,103.0,0.0
4,A Memoir Blue,2022-03-28,0.0,0.0,0.0,0.0,2.0,53.0,90.0,58.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
64134,to a T,2025-08-13,0.0,0.0,0.0,0.0,0.0,0.0,5.0,10.0,1.0
64135,to a T,2025-08-14,0.0,0.0,0.0,0.0,0.0,0.0,7.0,9.0,11.0
64136,to a T,2025-08-15,0.0,0.0,0.0,0.0,0.0,0.0,4.0,10.0,8.0
64137,to a T,2025-08-16,0.0,0.0,0.0,0.0,0.0,0.0,1.0,7.0,21.0
64138,to a T,2025-08-17,0.0,0.0,0.0,0.0,0.0,0.0,8.0,5.0,0.0

In [20]:
###STOPPED HERE

In [21]:
metric_cols = [
    'apple_units',
               'epic_units',
'gog_units',
'google_units',
'humble_units',
'nintendo_units',
'playstation_units',
'steam_units',
    'xbox_units'
              ]

In [22]:
for col in metric_cols:
    pivot_df[f'cume_{col}'] = pivot_df.groupby('product')[col].cumsum()

In [23]:
pivot_df.columns

Index(['product', 'Day', 'apple_units', 'epic_units', 'gog_units',
       'google_units', 'humble_units', 'nintendo_units', 'playstation_units',
       'steam_units', 'xbox_units', 'cume_apple_units', 'cume_epic_units',
       'cume_gog_units', 'cume_google_units', 'cume_humble_units',
       'cume_nintendo_units', 'cume_playstation_units', 'cume_steam_units',
       'cume_xbox_units'],
      dtype='object', name='Source')

In [24]:
value_cols = ['apple_units',
       'epic_units', 'gog_units', 'google_units', 'humble_units',
       'nintendo_units', 'playstation_units', 'steam_units', 'xbox_units',
       'cume_apple_units', 'cume_epic_units', 'cume_gog_units',
       'cume_google_units', 'cume_humble_units', 'cume_nintendo_units',
       'cume_playstation_units', 'cume_steam_units', 'cume_xbox_units']

In [25]:
pivot_df.dtypes

Source
product                           object
Day                       datetime64[ns]
apple_units                      float64
epic_units                       float64
gog_units                        float64
google_units                     float64
humble_units                     float64
nintendo_units                   float64
playstation_units                float64
steam_units                      float64
xbox_units                       float64
cume_apple_units                 float64
cume_epic_units                  float64
cume_gog_units                   float64
cume_google_units                float64
cume_humble_units                float64
cume_nintendo_units              float64
cume_playstation_units           float64
cume_steam_units                 float64
cume_xbox_units                  float64
dtype: object

In [26]:
df = pivot_df.groupby(["product", 'Day'], as_index=False)[value_cols].max()

In [27]:
df.query("product =='Stray'")

Source,product,Day,apple_units,epic_units,gog_units,google_units,humble_units,nintendo_units,playstation_units,steam_units,xbox_units,cume_apple_units,cume_epic_units,cume_gog_units,cume_google_units,cume_humble_units,cume_nintendo_units,cume_playstation_units,cume_steam_units,cume_xbox_units
48261,Stray,2022-06-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13946.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13946.0,0.0
48262,Stray,2022-06-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22723.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36669.0,0.0
48263,Stray,2022-06-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14384.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,51053.0,0.0
48264,Stray,2022-06-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12245.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,63298.0,0.0
48265,Stray,2022-06-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10130.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,73428.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49430,Stray,2025-08-14,22.0,0.0,0.0,0.0,3.0,864.0,314.0,173.0,1019.0,15917.0,0.0,0.0,0.0,4780.0,231795.0,2030954.0,3822743.0,703291.0
49431,Stray,2025-08-15,20.0,0.0,0.0,0.0,12.0,648.0,319.0,214.0,1155.0,15937.0,0.0,0.0,0.0,4792.0,232443.0,2031273.0,3822957.0,704446.0
49432,Stray,2025-08-16,20.0,0.0,0.0,0.0,17.0,702.0,441.0,292.0,1442.0,15957.0,0.0,0.0,0.0,4809.0,233145.0,2031714.0,3823249.0,705888.0
49433,Stray,2025-08-17,0.0,0.0,0.0,0.0,13.0,773.0,253.0,201.0,0.0,15957.0,0.0,0.0,0.0,4822.0,233918.0,2031967.0,3823450.0,705888.0
49434,Stray,2025-08-18,0.0,0.0,0.0,0.0,3.0,48.0,0.0,0.0,0.0,15957.0,0.0,0.0,0.0,4825.0,233966.0,2031967.0,3823450.0,705888.0

In [28]:
stop

NameError: name 'stop' is not defined

In [29]:
df.columns = [col.strip().replace(" ", "_").lower() for col in df.columns]
#df['date'] = pd.to_datetime(df['date'], format="%d %B, %Y")

In [30]:
df['product_day'] = df['product'].astype(str) + '_' + df['day'].astype(str)
#df.set_index('product_day', inplace=True)

df['unit_daily_delta']  = df.groupby('product')['units'].pct_change()
df['rev_daily_delta']  = df.groupby('product')['revenue'].pct_change()

In [31]:
df

,product,day,apple_units,epic_units,gog_units,google_units,humble_units,nintendo_units,playstation_units,steam_units,...,cume_apple_units,cume_epic_units,cume_gog_units,cume_google_units,cume_humble_units,cume_nintendo_units,cume_playstation_units,cume_steam_units,cume_xbox_units,product_day
0,A Memoir Blue,2022-03-24,0.0,0.0,0.0,0.0,6.0,56.0,227.0,370.0,...,0.0,0.0,0.0,0.0,6.0,56.0,227.0,370.0,0.0,A Memoir Blue_2022-03-24
1,A Memoir Blue,2022-03-25,0.0,0.0,0.0,0.0,0.0,93.0,229.0,197.0,...,0.0,0.0,0.0,0.0,6.0,149.0,456.0,567.0,0.0,A Memoir Blue_2022-03-25
2,A Memoir Blue,2022-03-26,0.0,0.0,0.0,0.0,2.0,94.0,123.0,118.0,...,0.0,0.0,0.0,0.0,8.0,243.0,579.0,685.0,0.0,A Memoir Blue_2022-03-26
3,A Memoir Blue,2022-03-27,0.0,0.0,0.0,0.0,1.0,102.0,94.0,103.0,...,0.0,0.0,0.0,0.0,9.0,345.0,673.0,788.0,0.0,A Memoir Blue_2022-03-27
4,A Memoir Blue,2022-03-28,0.0,0.0,0.0,0.0,2.0,53.0,90.0,58.0,...,0.0,0.0,0.0,0.0,11.0,398.0,763.0,846.0,0.0,A Memoir Blue_2022-03-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64134,to a T,2025-08-13,0.0,0.0,0.0,0.0,0.0,0.0,5.0,10.0,...,0.0,18.0,0.0,0.0,0.0,0.0,3229.0,4648.0,959.0,to a T_2025-08-13
64135,to a T,2025-08-14,0.0,0.0,0.0,0.0,0.0,0.0,7.0,9.0,...,0.0,18.0,0.0,0.0,0.0,0.0,3236.0,4657.0,970.0,to a T_2025-08-14
64136,to a T,2025-08-15,0.0,0.0,0.0,0.0,0.0,0.0,4.0,10.0,...,0.0,18.0,0.0,0.0,0.0,0.0,3240.0,4667.0,978.0,to a T_2025-08-15
64137,to a T,2025-08-16,0.0,0.0,0.0,0.0,0.0,0.0,1.0,7.0,...,0.0,18.0,0.0,0.0,0.0,0.0,3241.0,4674.0,999.0,to a T_2025-08-16
64138,to a T,2025-08-17,0.0,0.0,0.0,0.0,0.0,0.0,8.0,5.0,...,0.0,18.0,0.0,0.0,0.0,0.0,3249.0,4679.0,999.0,to a T_2025-08-17

In [32]:
test = df.query("product == 'Stray'")

In [33]:
test.query("day >'2025-06-24'")[['product_day']+value_cols]

,product_day,apple_units,epic_units,gog_units,google_units,humble_units,nintendo_units,playstation_units,steam_units,xbox_units,cume_apple_units,cume_epic_units,cume_gog_units,cume_google_units,cume_humble_units,cume_nintendo_units,cume_playstation_units,cume_steam_units,cume_xbox_units
49380,Stray_2025-06-25,15.0,0.0,0.0,0.0,8.0,499.0,329.0,172.0,103.0,15039.0,0.0,0.0,0.0,4766.0,207468.0,1988000.0,3737206.0,684405.0
49381,Stray_2025-06-26,20.0,0.0,0.0,0.0,10.0,545.0,379.0,3456.0,119.0,15059.0,0.0,0.0,0.0,4776.0,208013.0,1988379.0,3740662.0,684524.0
49382,Stray_2025-06-27,15.0,0.0,0.0,0.0,0.0,565.0,409.0,5194.0,145.0,15074.0,0.0,0.0,0.0,4776.0,208578.0,1988788.0,3745856.0,684669.0
49383,Stray_2025-06-28,20.0,0.0,0.0,0.0,0.0,668.0,523.0,5062.0,195.0,15094.0,0.0,0.0,0.0,4776.0,209246.0,1989311.0,3750918.0,684864.0
49384,Stray_2025-06-29,10.0,0.0,0.0,0.0,0.0,674.0,538.0,4095.0,181.0,15104.0,0.0,0.0,0.0,4776.0,209920.0,1989849.0,3755013.0,685045.0
49385,Stray_2025-06-30,14.0,0.0,0.0,0.0,-1.0,464.0,335.0,3516.0,139.0,15118.0,0.0,0.0,0.0,4775.0,210384.0,1990184.0,3758529.0,685184.0
49386,Stray_2025-07-01,13.0,0.0,0.0,0.0,0.0,448.0,392.0,3346.0,128.0,15131.0,0.0,0.0,0.0,4775.0,210832.0,1990576.0,3761875.0,685312.0
49387,Stray_2025-07-02,12.0,0.0,0.0,0.0,0.0,450.0,337.0,2727.0,111.0,15143.0,0.0,0.0,0.0,4775.0,211282.0,1990913.0,3764602.0,685423.0
49388,Stray_2025-07-03,14.0,0.0,0.0,0.0,0.0,460.0,364.0,2815.0,133.0,15157.0,0.0,0.0,0.0,4775.0,211742.0,1991277.0,3767417.0,685556.0
49389,Stray_2025-07-04,20.0,0.0,0.0,0.0,0.0,521.0,460.0,3028.0,181.0,15177.0,0.0,0.0,0.0,4775.0,212263.0,1991737.0,3770445.0,685737.0
49390,Stray_2025-07-05,19.0,0.0,0.0,0.0,1.0,678.0,544.0,2962.0,176.0,15196.0,0.0,0.0,0.0,4776.0,212941.0,1992281.0,3773407.0,685913.0
49391,Stray_2025-07-06,17.0,0.0,0.0,0.0,0.0,792.0,538.0,3089.0,221.0,15213.0,0.0,0.0,0.0,4776.0,213733.0,1992819.0,3776496.0,686134.0
49392,Stray_2025-07-07,14.0,0.0,0.0,0.0,0.0,537.0,353.0,2582.0,118.0,15227.0,0.0,0.0,0.0,4776.0,214270.0,1993172.0,3779078.0,686252.0
49393,Stray_2025-07-08,13.0,0.0,0.0,0.0,0.0,508.0,374.0,2778.0,1176.0,15240.0,0.0,0.0,0.0,4776.0,214778.0,1993546.0,3781856.0,687428.0
49394,Stray_2025-07-09,11.0,0.0,0.0,0.0,0.0,222.0,337.0,4445.0,1659.0,15251.0,0.0,0.0,0.0,4776.0,215000.0,1993883.0,3786301.0,689087.0
49395,Stray_2025-07-10,19.0,0.0,0.0,0.0,0.0,195.0,350.0,4652.0,1881.0,15270.0,0.0,0.0,0.0,4776.0,215195.0,1994233.0,3790953.0,690968.0
49396,Stray_2025-07-11,23.0,0.0,0.0,0.0,1.0,211.0,423.0,3076.0,1292.0,15293.0,0.0,0.0,0.0,4777.0,215406.0,1994656.0,3794029.0,692260.0
49397,Stray_2025-07-12,28.0,0.0,0.0,0.0,0.0,272.0,482.0,2753.0,1418.0,15321.0,0.0,0.0,0.0,4777.0,215678.0,1995138.0,3796782.0,693678.0
49398,Stray_2025-07-13,23.0,0.0,0.0,0.0,0.0,281.0,529.0,2397.0,1234.0,15344.0,0.0,0.0,0.0,4777.0,215959.0,1995667.0,3799179.0,694912.0
49399,Stray_2025-07-14,16.0,0.0,0.0,0.0,-1.0,207.0,352.0,1942.0,1093.0,15360.0,0.0,0.0,0.0,4776.0,216166.0,1996019.0,3801121.0,696005.0
49400,Stray_2025-07-15,15.0,0.0,0.0,0.0,0.0,212.0,367.0,1911.0,1231.0,15375.0,0.0,0.0,0.0,4776.0,216378.0,1996386.0,3803032.0,697236.0
49401,Stray_2025-07-16,13.0,0.0,0.0,0.0,0.0,200.0,2424.0,1724.0,1048.0,15388.0,0.0,0.0,0.0,4776.0,216578.0,1998810.0,3804756.0,698284.0
49402,Stray_2025-07-17,10.0,0.0,0.0,0.0,0.0,186.0,2010.0,1665.0,664.0,15398.0,0.0,0.0,0.0,4776.0,216764.0,2000820.0,3806421.0,698948.0
49403,Stray_2025-07-18,19.0,0.0,0.0,0.0,0.0,194.0,1875.0,1832.0,141.0,15417.0,0.0,0.0,0.0,4776.0,216958.0,2002695.0,3808253.0,699089.0
49404,Stray_2025-07-19,16.0,0.0,0.0,0.0,0.0,232.0,2353.0,1952.0,168.0,15433.0,0.0,0.0,0.0,4776.0,217190.0,2005048.0,3810205.0,699257.0
49405,Stray_2025-07-20,17.0,0.0,0.0,0.0,0.0,240.0,2401.0,2075.0,176.0,15450.0,0.0,0.0,0.0,4776.0,217430.0,2007449.0,3812280.0,699433.0
49406,Stray_2025-07-21,12.0,0.0,0.0,0.0,0.0,187.0,1801.0,1810.0,135.0,15462.0,0.0,0.0,0.0,4776.0,217617.0,2009250.0,3814090.0,699568.0
49407,Stray_2025-07-22,16.0,0.0,0.0,0.0,0.0,173.0,1557.0,1661.0,115.0,15478.0,0.0,0.0,0.0,4776.0,217790.0,2010807.0,3815751.0,699683.0
49408,Stray_2025-07-23,11.0,0.0,0.0,0.0,0.0,150.0,1550.0,1765.0,92.0,15489.0,0.0,0.0,0.0,4776.0,217940.0,2012357.0,3817516.0,699775.0
49409,Stray_2025-07-24,20.0,0.0,0.0,0.0,0.0,134.0,1494.0,966.0,115.0,15509.0,0.0,0.0,0.0,4776.0,218074.0,2013851.0,3818482.0,699890.0
49410,Stray_2025-07-25,26.0,0.0,0.0,0.0,0.0,478.0,1691.0,168.0,136.0,15535.0,0.0,0.0,0.0,4776.0,218552.0,2015542.0,3818650.0,700026.0
49411,Stray_2025-07-26,22.0,0.0,0.0,0.0,0.0,664.0,2220.0,248.0,144.0,15557.0,0.0,0.0,0.0,4776.0,219216.0,2017762.0,3818898.0,700170.0
49412,Stray_2025-07-27,26.0,0.0,0.0,0.0,0.0,769.0,2354.0,220.0,136.0,15583.0,0.0,0.0,0.0,4776.0,219985.0,2020116.0,3819118.0,700306.0
49413,Stray_2025-07-28,26.0,0.0,0.0,0.0,0.0,497.0,1703.0,179.0,125.0,15609.0,0.0,0.0,0.0,4776.0,220482.0,2021819.0,3819297.0,700431.0
49414,Stray_2025-07-29,25.0,0.0,0.0,0.0,0.0,464.0,1500.0,162.0,98.0,15634.0,0.0,0.0,0.0,4776.0,220946.0,2023319.0,3819459.0,700529.0
49415,Stray_2025-07-30,19.0,0.0,0.0,0.0,0.0,514.0,1645.0,198.0,98.0,15653.0,0.0,0.0,0.0,4776.0,221460.0,2024964.0,3819657.0,700627.0
49416,Stray_2025-07-31,19.0,0.0,0.0,0.0,0.0,537.0,664.0,181.0,106.0,15672.0,0.0,0.0,0.0,4776.0,221997.0,2025628.0,3819838.0,700733.0
49417,Stray_2025-08-01,19.0,0.0,0.0,0.0,1.0,592.0,434.0,230.0,136.0,15691.0,0.0,0.0,0.0,4777.0,222589.0,2026062.0,3820068.0,700869.0
49418,Stray_2025-08-02,26.0,0.0,0.0,0.0,0.0,712.0,553.0,292.0,164.0,15717.0,0.0,0.0,0.0,4777.0,223301.0,2026615.0,3820360.0,701033.0
49419,Stray_2025-08-03,15.0,0.0,0.0,0.0,0.0,658.0,491.0,234.0,152.0,15732.0,0.0,0.0,0.0,4777.0,223959.0,2027106.0,3820594.0,701185.0
49420,Stray_2025-08-04,19.0,0.0,0.0,0.0,0.0,506.0,349.0,181.0,118.0,15751.0,0.0,0.0,0.0,4777.0,224465.0,2027455.0,3820775.0,701303.0
49421,Stray_2025-08-05,19.0,0.0,0.0,0.0,0.0,415.0,321.0,200.0,94.0,15770.0,0.0,0.0,0.0,4777.0,224880.0,2027776.0,3820975.0,701397.0
49422,Stray_2025-08-06,16.0,0.0,0.0,0.0,0.0,472.0,296.0,187.0,100.0,15786.0,0.0,0.0,0.0,4777.0,225352.0,2028072.0,3821162.0,701497.0
49423,Stray_2025-08-07,16.0,0.0,0.0,0.0,0.0,462.0,307.0,168.0,103.0,15802.0,0.0,0.0,0.0,4777.0,225814.0,2028379.0,3821330.0,701600.0
49424,Stray_2025-08-08,13.0,0.0,0.0,0.0,0.0,664.0,391.0,222.0,120.0,15815.0,0.0,0.0,0.0,4777.0,226478.0,2028770.0,3821552.0,701720.0
49425,Stray_2025-08-09,20.0,0.0,0.0,0.0,0.0,944.0,487.0,207.0,140.0,15835.0,0.0,0.0,0.0,4777.0,227422.0,2029257.0,3821759.0,701860.0
49426,Stray_2025-08-10,19.0,0.0,0.0,0.0,0.0,1137.0,482.0,232.0,132.0,15854.0,0.0,0.0,0.0,4777.0,228559.0,2029739.0,3821991.0,701992.0
49427,Stray_2025-08-11,11.0,0.0,0.0,0.0,0.0,759.0,329.0,203.0,96.0,15865.0,0.0,0.0,0.0,4777.0,229318.0,2030068.0,3822194.0,702088.0
49428,Stray_2025-08-12,15.0,0.0,0.0,0.0,0.0,825.0,288.0,190.0,94.0,15880.0,0.0,0.0,0.0,4777.0,230143.0,2030356.0,3822384.0,702182.0
49429,Stray_2025-08-13,15.0,0.0,0.0,0.0,0.0,788.0,284.0,186.0,90.0,15895.0,0.0,0.0,0.0,4777.0,230931.0,2030640.0,3822570.0,702272.0
49430,Stray_2025-08-14,22.0,0.0,0.0,0.0,3.0,864.0,314.0,173.0,1019.0,15917.0,0.0,0.0,0.0,4780.0,231795.0,2030954.0,3822743.0,703291.0
49431,Stray_2025-08-15,20.0,0.0,0.0,0.0,12.0,648.0,319.0,214.0,1155.0,15937.0,0.0,0.0,0.0,4792.0,232443.0,2031273.0,3822957.0,704446.0
49432,Stray_2025-08-16,20.0,0.0,0.0,0.0,17.0,702.0,441.0,292.0,1442.0,15957.0,0.0,0.0,0.0,4809.0,233145.0,2031714.0,3823249.0,705888.0
49433,Stray_2025-08-17,0.0,0.0,0.0,0.0,13.0,773.0,253.0,201.0,0.0,15957.0,0.0,0.0,0.0,4822.0,233918.0,2031967.0,3823450.0,705888.0
49434,Stray_2025-08-18,0.0,0.0,0.0,0.0,3.0,48.0,0.0,0.0,0.0,15957.0,0.0,0.0,0.0,4825.0,233966.0,2031967.0,3823450.0,705888.0

In [34]:
# Restructure each row
records = []
for _, row in df.iterrows():
    doc = {'_id': row['product_day'],
        "platform_units": {
            "Apple": row["apple_units"],
            "Epic": row["epic_units"],
            "GOG": row["gog_units"],
            "Google": row["google_units"],
            "Humble": row["humble_units"],
            "Nintendo": row["nintendo_units"],
            "PS": row["playstation_units"],
            "Steam": row["steam_units"],
            "Xbox": row["xbox_units"]
        }
    }
    records.append(doc)

In [35]:
records

[{'_id': 'A Memoir Blue_2022-03-24',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 6.0,
   'Nintendo': 56.0,
   'PS': 227.0,
   'Steam': 370.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-03-25',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 93.0,
   'PS': 229.0,
   'Steam': 197.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-03-26',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 2.0,
   'Nintendo': 94.0,
   'PS': 123.0,
   'Steam': 118.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-03-27',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 1.0,
   'Nintendo': 102.0,
   'PS': 94.0,
   'Steam': 103.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-03-28',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 2.0,
   'Nintendo': 53.0,
   'PS': 90.0,
   'Steam': 58.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-03-29',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 1.0,
   'Nintendo': 57.0,
   'PS': 69.0,
   'Steam': 62.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-03-30',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 46.0,
   'PS': 61.0,
   'Steam': 53.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-03-31',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 1.0,
   'Nintendo': 37.0,
   'PS': 41.0,
   'Steam': 36.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-04-01',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 37.0,
   'PS': 44.0,
   'Steam': 21.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-04-02',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 49.0,
   'PS': 48.0,
   'Steam': 26.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-04-03',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 44.0,
   'PS': 37.0,
   'Steam': 27.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-04-04',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 30.0,
   'PS': 25.0,
   'Steam': 6.0,
   'Xbox': 7.0}},
 {'_id': 'A Memoir Blue_2022-04-05',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 28.0,
   'PS': 23.0,
   'Steam': 16.0,
   'Xbox': 7.0}},
 {'_id': 'A Memoir Blue_2022-04-06',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 29.0,
   'PS': 22.0,
   'Steam': 19.0,
   'Xbox': 11.0}},
 {'_id': 'A Memoir Blue_2022-04-07',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 18.0,
   'PS': 29.0,
   'Steam': 33.0,
   'Xbox': 7.0}},
 {'_id': 'A Memoir Blue_2022-04-08',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 15.0,
   'PS': 22.0,
   'Steam': 39.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-04-09',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 2.0,
   'Nintendo': 15.0,
   'PS': 41.0,
   'Steam': 34.0,
   'Xbox': 11.0}},
 {'_id': 'A Memoir Blue_2022-04-10',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 22.0,
   'PS': 26.0,
   'Steam': 15.0,
   'Xbox': 11.0}},
 {'_id': 'A Memoir Blue_2022-04-11',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 15.0,
   'PS': 28.0,
   'Steam': 14.0,
   'Xbox': 5.0}},
 {'_id': 'A Memoir Blue_2022-04-12',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 8.0,
   'PS': 30.0,
   'Steam': 10.0,
   'Xbox': 7.0}},
 {'_id': 'A Memoir Blue_2022-04-13',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 12.0,
   'PS': 23.0,
   'Steam': 6.0,
   'Xbox': 3.0}},
 {'_id': 'A Memoir Blue_2022-04-14',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 4.0,
   'PS': 19.0,
   'Steam': 17.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-04-15',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 11.0,
   'PS': 36.0,
   'Steam': 13.0,
   'Xbox': 6.0}},
 {'_id': 'A Memoir Blue_2022-04-16',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 14.0,
   'PS': 31.0,
   'Steam': 13.0,
   'Xbox': 8.0}},
 {'_id': 'A Memoir Blue_2022-04-17',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 13.0,
   'PS': 26.0,
   'Steam': 9.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-04-18',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 12.0,
   'PS': 17.0,
   'Steam': 13.0,
   'Xbox': 2.0}},
 {'_id': 'A Memoir Blue_2022-04-19',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 8.0,
   'PS': 14.0,
   'Steam': 19.0,
   'Xbox': 2.0}},
 {'_id': 'A Memoir Blue_2022-04-20',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 6.0,
   'PS': 17.0,
   'Steam': 12.0,
   'Xbox': 13.0}},
 {'_id': 'A Memoir Blue_2022-04-21',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 5.0,
   'PS': 21.0,
   'Steam': 10.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-04-22',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 5.0,
   'PS': 19.0,
   'Steam': 10.0,
   'Xbox': 5.0}},
 {'_id': 'A Memoir Blue_2022-04-23',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 6.0,
   'PS': 19.0,
   'Steam': 8.0,
   'Xbox': 5.0}},
 {'_id': 'A Memoir Blue_2022-04-24',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 10.0,
   'PS': 23.0,
   'Steam': 11.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-04-25',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 3.0,
   'PS': 23.0,
   'Steam': 4.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-04-26',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 4.0,
   'PS': 29.0,
   'Steam': 7.0,
   'Xbox': 1.0}},
 {'_id': 'A Memoir Blue_2022-04-27',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 3.0,
   'PS': 66.0,
   'Steam': 5.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-04-28',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 3.0,
   'PS': 45.0,
   'Steam': 5.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-04-29',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 7.0,
   'PS': 45.0,
   'Steam': 10.0,
   'Xbox': 6.0}},
 {'_id': 'A Memoir Blue_2022-04-30',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 2.0,
   'Nintendo': 9.0,
   'PS': 51.0,
   'Steam': 12.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-05-01',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 3.0,
   'PS': 34.0,
   'Steam': 9.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-05-02',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 3.0,
   'PS': 33.0,
   'Steam': 3.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-05-03',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 2.0,
   'PS': 22.0,
   'Steam': 1.0,
   'Xbox': 8.0}},
 {'_id': 'A Memoir Blue_2022-05-04',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 3.0,
   'PS': 17.0,
   'Steam': 7.0,
   'Xbox': 1.0}},
 {'_id': 'A Memoir Blue_2022-05-05',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 2.0,
   'PS': 20.0,
   'Steam': 5.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-05-06',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 0.0,
   'PS': 25.0,
   'Steam': 13.0,
   'Xbox': 5.0}},
 {'_id': 'A Memoir Blue_2022-05-07',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 3.0,
   'PS': 18.0,
   'Steam': 11.0,
   'Xbox': 3.0}},
 {'_id': 'A Memoir Blue_2022-05-08',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 7.0,
   'PS': 32.0,
   'Steam': 10.0,
   'Xbox': 9.0}},
 {'_id': 'A Memoir Blue_2022-05-09',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 7.0,
   'PS': 17.0,
   'Steam': 11.0,
   'Xbox': 7.0}},
 {'_id': 'A Memoir Blue_2022-05-10',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 1.0,
   'Nintendo': 5.0,
   'PS': 16.0,
   'Steam': 2.0,
   'Xbox': 6.0}},
 {'_id': 'A Memoir Blue_2022-05-11',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 4.0,
   'PS': 18.0,
   'Steam': 2.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-05-12',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 3.0,
   'PS': 10.0,
   'Steam': 7.0,
   'Xbox': 2.0}},
 {'_id': 'A Memoir Blue_2022-05-13',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 3.0,
   'PS': 15.0,
   'Steam': 6.0,
   'Xbox': 5.0}},
 {'_id': 'A Memoir Blue_2022-05-14',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 3.0,
   'PS': 10.0,
   'Steam': 6.0,
   'Xbox': 5.0}},
 {'_id': 'A Memoir Blue_2022-05-15',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 8.0,
   'PS': 12.0,
   'Steam': 4.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-05-16',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 1.0,
   'PS': 3.0,
   'Steam': 4.0,
   'Xbox': 1.0}},
 {'_id': 'A Memoir Blue_2022-05-17',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 1.0,
   'PS': 8.0,
   'Steam': 5.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-05-18',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 1.0,
   'PS': 8.0,
   'Steam': 5.0,
   'Xbox': 6.0}},
 {'_id': 'A Memoir Blue_2022-05-19',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 3.0,
   'PS': 7.0,
   'Steam': 7.0,
   'Xbox': 5.0}},
 {'_id': 'A Memoir Blue_2022-05-20',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 1.0,
   'Nintendo': 2.0,
   'PS': 9.0,
   'Steam': 1.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-05-21',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 4.0,
   'PS': 6.0,
   'Steam': 6.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-05-22',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 3.0,
   'PS': 1.0,
   'Steam': 6.0,
   'Xbox': 3.0}},
 {'_id': 'A Memoir Blue_2022-05-23',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 30.0,
   'PS': 4.0,
   'Steam': 89.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-05-24',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 54.0,
   'PS': 9.0,
   'Steam': 87.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-05-25',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 45.0,
   'PS': 149.0,
   'Steam': 80.0,
   'Xbox': 3.0}},
 {'_id': 'A Memoir Blue_2022-05-26',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 27.0,
   'PS': 115.0,
   'Steam': 199.0,
   'Xbox': 3.0}},
 {'_id': 'A Memoir Blue_2022-05-27',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 33.0,
   'PS': 81.0,
   'Steam': 267.0,
   'Xbox': 1.0}},
 {'_id': 'A Memoir Blue_2022-05-28',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 34.0,
   'PS': 63.0,
   'Steam': 182.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-05-29',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 48.0,
   'PS': 51.0,
   'Steam': 190.0,
   'Xbox': 3.0}},
 {'_id': 'A Memoir Blue_2022-05-30',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 47.0,
   'PS': 59.0,
   'Steam': 99.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-05-31',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 14.0,
   'PS': 35.0,
   'Steam': 9.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-06-01',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 4.0,
   'PS': 36.0,
   'Steam': 2.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-06-02',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 4.0,
   'PS': 42.0,
   'Steam': 12.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-06-03',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 3.0,
   'PS': 47.0,
   'Steam': 11.0,
   'Xbox': 3.0}},
 {'_id': 'A Memoir Blue_2022-06-04',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 2.0,
   'PS': 42.0,
   'Steam': 8.0,
   'Xbox': 5.0}},
 {'_id': 'A Memoir Blue_2022-06-05',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 2.0,
   'PS': 41.0,
   'Steam': 7.0,
   'Xbox': 5.0}},
 {'_id': 'A Memoir Blue_2022-06-06',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 1.0,
   'PS': 44.0,
   'Steam': 4.0,
   'Xbox': 4.0}},
 {'_id': 'A Memoir Blue_2022-06-07',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 2.0,
   'PS': 43.0,
   'Steam': 9.0,
   'Xbox': 2.0}},
 {'_id': 'A Memoir Blue_2022-06-08',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 2.0,
   'PS': 70.0,
   'Steam': 9.0,
   'Xbox': 3.0}},
 {'_id': 'A Memoir Blue_2022-06-09',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 1.0,
   'PS': 17.0,
   'Steam': 5.0,
   'Xbox': 3.0}},
 {'_id': 'A Memoir Blue_2022-06-10',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 1.0,
   'PS': 7.0,
   'Steam': 3.0,
   'Xbox': 3.0}},
 {'_id': 'A Memoir Blue_2022-06-11',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 3.0,
   'PS': 6.0,
   'Steam': 3.0,
   'Xbox': 5.0}},
 {'_id': 'A Memoir Blue_2022-06-12',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 2.0,
   'PS': 2.0,
   'Steam': 7.0,
   'Xbox': 6.0}},
 {'_id': 'A Memoir Blue_2022-06-13',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 2.0,
   'PS': 0.0,
   'Steam': 8.0,
   'Xbox': 0.0}},
 {'_id': 'A Memoir Blue_2022-06-14',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 2.0,
   'PS': 4.0,
   'Steam': 5.0,
   'Xbox': 1.0}},
 {'_id': 'A Memoir Blue_2022-06-15',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 2.0,
   'PS': 3.0,
   'Steam': 11.0,
   'Xbox': 2.0}},
 {'_id': 'A Memoir Blue_2022-06-16',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 1.0,
   'PS': 2.0,
   'Steam': 3.0,
   'Xbox': 3.0}},
 {'_id': 'A Memoir Blue_2022-06-17',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 1.0,
   'PS': 2.0,
   'Steam': 4.0,
   'Xbox': 21.0}},
 {'_id': 'A Memoir Blue_2022-06-18',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 3.0,
   'PS': 2.0,
   'Steam': 3.0,
   'Xbox': 24.0}},
 {'_id': 'A Memoir Blue_2022-06-19',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 2.0,
   'PS': 5.0,
   'Steam': 5.0,
   'Xbox': 20.0}},
 {'_id': 'A Memoir Blue_2022-06-20',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 0.0,
   'PS': 7.0,
   'Steam': 5.0,
   'Xbox': 21.0}},
 {'_id': 'A Memoir Blue_2022-06-21',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 2.0,
   'PS': 4.0,
   'Steam': 9.0,
   'Xbox': 36.0}},
 {'_id': 'A Memoir Blue_2022-06-22',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 1.0,
   'PS': 10.0,
   'Steam': 4.0,
   'Xbox': 8.0}},
 {'_id': 'A Memoir Blue_2022-06-23',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 14.0,
   'PS': 10.0,
   'Steam': 100.0,
   'Xbox': 8.0}},
 {'_id': 'A Memoir Blue_2022-06-24',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 5.0,
   'PS': 12.0,
   'Steam': 94.0,
   'Xbox': 18.0}},
 {'_id': 'A Memoir Blue_2022-06-25',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 4.0,
   'PS': 8.0,
   'Steam': 64.0,
   'Xbox': 24.0}},
 {'_id': 'A Memoir Blue_2022-06-26',
  'platform_units': {'Apple': 0.0,
   'Epic': 0.0,
   'GOG': 0.0,
   'Google': 0.0,
   'Humble': 0.0,
   'Nintendo': 9.0,
   'PS': 12.0,
   'Steam': 48.0,
   'Xbox': 19.0}},
 {'_id': 'A Memoir Blue_2022-06-27',

requests

In [36]:
stop

NameError: name 'stop' is not defined

folder_path = "units/cume_revenues.xlsx"


revs  = pd.read_excel(folder_path, skiprows=2)

In [45]:
from pymongo import UpdateOne

## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [46]:
from datetime import datetime
date_string = datetime.today().strftime('%Y-%m-%d')

In [47]:
db = client['ai_sales_data']
collection = db['units']

unique_products = collection.distinct("product", {"date": {"$gte": 2025-01-01}})

unique_products

In [48]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

In [49]:
#####
for batch in batchify(records, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 4000, Inserted: 0, Modified: 17
Matched: 3990, Inserted: 10, Modified: 11
Matched: 4000, Inserted: 0, Modified: 17
Matched: 4000, Inserted: 0, Modified: 9
Matched: 3993, Inserted: 7, Modified: 10
Matched: 4000, Inserted: 0, Modified: 18
Matched: 4000, Inserted: 0, Modified: 17
Matched: 4000, Inserted: 0, Modified: 19
Matched: 4000, Inserted: 0, Modified: 33
Matched: 4000, Inserted: 0, Modified: 26
Matched: 4000, Inserted: 0, Modified: 31
Matched: 4000, Inserted: 0, Modified: 25
Matched: 4000, Inserted: 0, Modified: 29
Matched: 4000, Inserted: 0, Modified: 17
Matched: 4000, Inserted: 0, Modified: 33
Matched: 4000, Inserted: 0, Modified: 8
Matched: 139, Inserted: 0, Modified: 26

collection.update_many({}, {"$unset": {"percent_of_max": ""}})

In [50]:
client.close()