In [1]:
## Download from IndieBI, details by product, All Games No Soundtrack, daily units

In [2]:
import pandas as pd
import glob
import os
import warnings

warnings.filterwarnings("ignore")

In [3]:
import pandas as pd
import glob
import os

# Define folder path
folder_path = "DB_Update/wishlists/"

# Get all Excel files in the folder
excel_files = glob.glob(os.path.join(folder_path, "*.xlsx"))

# Read and combine all files, skipping first 2 rows
df_list = [pd.read_excel(f, skiprows=2).assign(filename=os.path.basename(f)) for f in excel_files]
combined_df = pd.concat(df_list, ignore_index=True)

In [4]:
combined_df = combined_df.sort_values(by="Day")

In [5]:
wishlists = combined_df.drop_duplicates(subset=['Day', 'product'])
wishlists

,Day,product,Selected Measure,Blank Measure,filename
0,2016-12-18,A Memoir Blue,0,NaN,pre_2020_wishlists.xlsx
54,2016-12-18,Stray,0,NaN,pre_2020_wishlists.xlsx
53,2016-12-18,Storyteller - Original Soundtrack,0,NaN,pre_2020_wishlists.xlsx
52,2016-12-18,Storyteller,0,NaN,pre_2020_wishlists.xlsx
51,2016-12-18,Solar Ash - Original Soundtrack,0,NaN,pre_2020_wishlists.xlsx
...,...,...,...,...,...
396283,2025-08-04,Gorogoa - Original Soundtrack,0,NaN,2023_todate_WL.xlsx
396282,2025-08-04,Gorogoa,22,NaN,2023_todate_WL.xlsx
396281,2025-08-04,Forever Ago,8,NaN,2023_todate_WL.xlsx
396289,2025-08-04,If Found...,8,NaN,2023_todate_WL.xlsx
396343,2025-08-04,Wheel World - Soundtrack,1,NaN,2023_todate_WL.xlsx

In [6]:

wishlists = wishlists.rename({"Selected Measure":"wishlist_adds"}, axis=1)

In [7]:
wishlists = wishlists.drop("Blank Measure", axis=1)


wishlists = wishlists.drop("filename", axis=1)

In [8]:
wishlists

              Day                            product  wishlist_adds
0      2016-12-18                      A Memoir Blue              0
54     2016-12-18                              Stray              0
53     2016-12-18  Storyteller - Original Soundtrack              0
52     2016-12-18                        Storyteller              0
51     2016-12-18    Solar Ash - Original Soundtrack              0
...           ...                                ...            ...
396283 2025-08-04      Gorogoa - Original Soundtrack              0
396282 2025-08-04                            Gorogoa             22
396281 2025-08-04                        Forever Ago              8
396289 2025-08-04                        If Found...              8
396343 2025-08-04           Wheel World - Soundtrack              1

[246342 rows x 3 columns]

wishlists

In [9]:

wishlists['cume_wishlists'] = wishlists.groupby('product')['wishlist_adds'].cumsum()

In [10]:
wishlists.query("product=='Stray'")

              Day product  wishlist_adds  cume_wishlists
54     2016-12-18   Stray              0               0
130    2016-12-19   Stray              0               0
206    2016-12-20   Stray              0               0
282    2016-12-21   Stray              0               0
358    2016-12-22   Stray              0               0
...           ...     ...            ...             ...
395975 2025-07-31   Stray           4286        11260291
396062 2025-08-01   Stray           4027        11264318
396149 2025-08-02   Stray           4142        11268460
396235 2025-08-03   Stray           3051        11271511
396319 2025-08-04   Stray            262        11271773

[3152 rows x 4 columns]

stop

In [11]:
folder_path = "wishlists/Annapurna Interactive Historical Revenues - releases_dates.csv"
dates  = pd.read_csv(folder_path)
dates = dates.dropna(subset='pc_release_date')
dates['pc_release_date'] = pd.to_datetime(dates['pc_release_date'])
release_date_dict = dates.groupby('product')['pc_release_date'].min().to_dict()

In [12]:
release_date_dict.get("The Lost Wild")

Timestamp('2026-11-01 00:00:00')

In [13]:
wishlists['release_date'] = pd.to_datetime(wishlists['Day'])


wishlists["wishlists_percent_of_max"] = wishlists["cume_wishlists"] / wishlists.groupby("product")["cume_wishlists"].transform("max")

In [14]:
wishlists['release_date'] = pd.to_datetime(wishlists['Day'])
wishlists['Day'] = pd.to_datetime(wishlists['Day']).dt.to_pydatetime()
wishlists['release_date'] = wishlists.groupby('product')['release_date'].transform('min')
wishlists['release_date'] = wishlists['product'].map(release_date_dict)
wishlists["DAR"] = (wishlists["Day"] - wishlists["release_date"]).dt.days
#df["DAR"] = df.groupby("product")["DAR"].transform(lambda x: x.clip(lower=0))

wishlists["Weeks_from_Release"] = (wishlists["DAR"] // 7) + 1  # Week 1 starts at 0-7 days

df["avg_price"] = df["revenue"] / df["units"]

In [15]:
wishlists

,Day,product,wishlist_adds,cume_wishlists,release_date,wishlists_percent_of_max,DAR,Weeks_from_Release
0,2016-12-18,A Memoir Blue,0,0,2022-03-24,0.0,-1922.0,-274.0
54,2016-12-18,Stray,0,0,2022-07-19,0.0,-2039.0,-291.0
53,2016-12-18,Storyteller - Original Soundtrack,0,0,NaT,0.0,NaN,NaN
52,2016-12-18,Storyteller,0,0,2023-03-23,0.0,-2286.0,-326.0
51,2016-12-18,Solar Ash - Original Soundtrack,0,0,NaT,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...
396283,2025-08-04,Gorogoa - Original Soundtrack,0,3040,NaT,1.0,NaN,NaN
396282,2025-08-04,Gorogoa,22,975128,2017-12-14,1.0,2790.0,399.0
396281,2025-08-04,Forever Ago,8,86636,NaT,1.0,NaN,NaN
396289,2025-08-04,If Found...,8,237687,2020-05-19,1.0,1903.0,272.0
396343,2025-08-04,Wheel World - Soundtrack,1,99,NaT,1.0,NaN,NaN

In [16]:
value_cols = ["wishlist_adds",'cume_wishlists','wishlists_percent_of_max']

In [17]:
df = wishlists.groupby(["product", "Weeks_from_Release",'DAR','Day','release_date'], as_index=False)[value_cols].max()

df.query("DAR==0")

In [18]:
df.columns = [col.strip().replace(" ", "_").lower() for col in df.columns]
#df['date'] = pd.to_datetime(df['date'], format="%d %B, %Y")

In [19]:
df['product_day'] = df['product'].astype(str) + '_' + df['day'].astype(str)
#df.set_index('product_day', inplace=True)

In [20]:
df['wl_daily_delta']  = df.groupby('product')['wishlist_adds'].pct_change()

In [21]:
export = df.query("dar <=0")
export = export.drop_duplicates(subset='product', keep='last')

In [22]:
df.query("product =='Stray' & dar ==0")

,product,weeks_from_release,dar,day,release_date,wishlist_adds,cume_wishlists,wishlists_percent_of_max,product_day,wl_daily_delta
103621,Stray,1.0,0.0,2022-07-19,2022-07-19,385642,3248875,0.288231,Stray_2022-07-19,2.22338

In [23]:
export[['product','weeks_from_release', 'wishlist_adds','cume_wishlists']]

,product,weeks_from_release,wishlist_adds,cume_wishlists
1922,A Memoir Blue,1.0,1842,15349
3871,Ashen,1.0,7547,61972
9420,BattleSage,1.0,0,3228
12607,Bounty Star,-9.0,0,55901
15084,Cocoon,1.0,19892,116814
16378,Donut County,1.0,15826,34754
20328,Due Process,1.0,4827,116080
22302,Faraway,-21.0,0,5519
25070,Flock,1.0,3348,59932
25878,Florence,1.0,0,0
29395,Flower,1.0,23371,23371
32120,Gorogoa,1.0,22282,43433
36966,Hindsight,1.0,1392,20941
40111,Hohokum,1.0,6251,6251
42605,I Am Dead,1.0,3654,33102
45615,If Found...,1.0,2009,17621
48790,Journey,1.0,50081,173544
50686,Kentucky Route Zero: TV Edition,1.0,1800,11204
52768,LEGO Voyagers,-8.0,39,127016
54446,Last Stop,1.0,2647,33022
58627,Lorelei and the Laser Eyes,1.0,9792,53743
62113,Lushfoil Photography Sim,1.0,18200,166301
63760,Maquette,1.0,10087,40541
68528,Mixtape,-21.0,21,158607
71523,Morsels,1.0,68,39911
73230,Mundaun,1.0,3747,17955
76839,Neon White,1.0,22075,142271
78052,No Goblin Game 3,-27.0,1,10150
80710,Open Roads,1.0,5662,113731
82483,Outer Wilds,1.0,77341,500062
84357,Outer Wilds - Archaeologist Edition BUNDLE,1.0,101,101
87509,Outer Wilds - Echoes of the Eye DLC,1.0,13945,54791
90005,Sayonara Wild Hearts,1.0,12876,30721
95123,Skin Deep,1.0,12306,95432
95277,Snap & Grab,-27.0,3,655
97459,Solar Ash,1.0,12184,144244
100716,Storyteller,1.0,10814,187016
103621,Stray,1.0,385642,3248875
105712,Telling Lies,1.0,29995,77818
109612,The Artful Escape,1.0,3792,40882
114189,The Lost Wild,-64.0,27,473230
115984,The Pathless,1.0,6611,54125
118704,The Unfinished Swan,1.0,27157,27157
123004,Thirsty Suitors,1.0,2886,51429
125351,Twelve Minutes,1.0,55616,381116
129803,Wanderstop,1.0,32304,278667
131411,Wattam,1.0,1185,43319
133230,What Remains of Edith Finch,1.0,15860,30151
139393,Wheel World,1.0,6474,117310
142489,to a T,1.0,4788,41229

df

In [24]:
export[['product','weeks_from_release', 'wishlist_adds','cume_wishlists']].to_clipboard()

In [25]:
final_df = df.query("wishlist_adds	>0")

In [26]:
final_df

,product,weeks_from_release,dar,day,release_date,wishlist_adds,cume_wishlists,wishlists_percent_of_max,product_day,wl_daily_delta
1684,A Memoir Blue,-33.0,-238.0,2021-07-29,2022-03-24,1140,1140,0.010111,A Memoir Blue_2021-07-29,inf
1685,A Memoir Blue,-33.0,-237.0,2021-07-30,2022-03-24,676,1816,0.016107,A Memoir Blue_2021-07-30,-0.407018
1686,A Memoir Blue,-33.0,-236.0,2021-07-31,2022-03-24,279,2095,0.018582,A Memoir Blue_2021-07-31,-0.587278
1687,A Memoir Blue,-33.0,-235.0,2021-08-01,2022-03-24,209,2304,0.020436,A Memoir Blue_2021-08-01,-0.250896
1688,A Memoir Blue,-33.0,-234.0,2021-08-02,2022-03-24,180,2484,0.022032,A Memoir Blue_2021-08-02,-0.138756
...,...,...,...,...,...,...,...,...,...,...
142553,to a T,10.0,64.0,2025-07-31,2025-05-28,472,64098,0.990145,to a T_2025-07-31,0.578595
142554,to a T,10.0,65.0,2025-08-01,2025-05-28,275,64373,0.994393,to a T_2025-08-01,-0.417373
142555,to a T,10.0,66.0,2025-08-02,2025-05-28,187,64560,0.997281,to a T_2025-08-02,-0.320000
142556,to a T,10.0,67.0,2025-08-03,2025-05-28,150,64710,0.999598,to a T_2025-08-03,-0.197861
142557,to a T,10.0,68.0,2025-08-04,2025-05-28,26,64736,1.000000,to a T_2025-08-04,-0.826667

In [27]:
# Restructure each row
records = []
for _, row in final_df.iterrows():
    doc = {'_id': row['product_day'],
           'product': row['product'],
           'day': row['day'],
            "wishlist_adds": row["wishlist_adds"],
            "cume_wishlists": row["cume_wishlists"],
            "wishlists_percent_of_max": row["wishlists_percent_of_max"],
            "wl_daily_delta": row["wl_daily_delta"],

    }
    records.append(doc)

records = df.to_dict(orient="records")
records

In [28]:
records

[{'_id': 'A Memoir Blue_2021-07-29',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-07-29 00:00:00'),
  'wishlist_adds': 1140,
  'cume_wishlists': 1140,
  'wishlists_percent_of_max': 0.010111402824097069,
  'wl_daily_delta': inf},
 {'_id': 'A Memoir Blue_2021-07-30',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-07-30 00:00:00'),
  'wishlist_adds': 676,
  'cume_wishlists': 1816,
  'wishlists_percent_of_max': 0.01610728730575463,
  'wl_daily_delta': -0.40701754385964917},
 {'_id': 'A Memoir Blue_2021-07-31',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-07-31 00:00:00'),
  'wishlist_adds': 279,
  'cume_wishlists': 2095,
  'wishlists_percent_of_max': 0.018581920102178386,
  'wl_daily_delta': -0.5872781065088757},
 {'_id': 'A Memoir Blue_2021-08-01',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-01 00:00:00'),
  'wishlist_adds': 209,
  'cume_wishlists': 2304,
  'wishlists_percent_of_max': 0.020435677286596184,
  'wl_daily_delta': -0.2508960573476703},
 {'_id': 'A Memoir Blue_2021-08-02',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-02 00:00:00'),
  'wishlist_adds': 180,
  'cume_wishlists': 2484,
  'wishlists_percent_of_max': 0.02203221457461151,
  'wl_daily_delta': -0.13875598086124397},
 {'_id': 'A Memoir Blue_2021-08-03',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-03 00:00:00'),
  'wishlist_adds': 95,
  'cume_wishlists': 2579,
  'wishlists_percent_of_max': 0.0228748314766196,
  'wl_daily_delta': -0.4722222222222222},
 {'_id': 'A Memoir Blue_2021-08-04',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-04 00:00:00'),
  'wishlist_adds': 66,
  'cume_wishlists': 2645,
  'wishlists_percent_of_max': 0.023460228482225218,
  'wl_daily_delta': -0.3052631578947368},
 {'_id': 'A Memoir Blue_2021-08-05',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-05 00:00:00'),
  'wishlist_adds': 58,
  'cume_wishlists': 2703,
  'wishlists_percent_of_max': 0.023974668275030156,
  'wl_daily_delta': -0.12121212121212122},
 {'_id': 'A Memoir Blue_2021-08-06',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-06 00:00:00'),
  'wishlist_adds': 49,
  'cume_wishlists': 2752,
  'wishlists_percent_of_max': 0.02440928120343433,
  'wl_daily_delta': -0.15517241379310343},
 {'_id': 'A Memoir Blue_2021-08-07',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-07 00:00:00'),
  'wishlist_adds': 44,
  'cume_wishlists': 2796,
  'wishlists_percent_of_max': 0.024799545873838074,
  'wl_daily_delta': -0.10204081632653061},
 {'_id': 'A Memoir Blue_2021-08-08',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-08 00:00:00'),
  'wishlist_adds': 50,
  'cume_wishlists': 2846,
  'wishlists_percent_of_max': 0.025243028453842332,
  'wl_daily_delta': 0.13636363636363646},
 {'_id': 'A Memoir Blue_2021-08-09',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-09 00:00:00'),
  'wishlist_adds': 39,
  'cume_wishlists': 2885,
  'wishlists_percent_of_max': 0.025588944866245654,
  'wl_daily_delta': -0.21999999999999997},
 {'_id': 'A Memoir Blue_2021-08-10',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-10 00:00:00'),
  'wishlist_adds': 46,
  'cume_wishlists': 2931,
  'wishlists_percent_of_max': 0.02599694883984957,
  'wl_daily_delta': 0.17948717948717952},
 {'_id': 'A Memoir Blue_2021-08-11',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-11 00:00:00'),
  'wishlist_adds': 29,
  'cume_wishlists': 2960,
  'wishlists_percent_of_max': 0.02625416873625204,
  'wl_daily_delta': -0.3695652173913043},
 {'_id': 'A Memoir Blue_2021-08-12',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-12 00:00:00'),
  'wishlist_adds': 33,
  'cume_wishlists': 2993,
  'wishlists_percent_of_max': 0.02654686723905485,
  'wl_daily_delta': 0.13793103448275867},
 {'_id': 'A Memoir Blue_2021-08-13',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-13 00:00:00'),
  'wishlist_adds': 26,
  'cume_wishlists': 3019,
  'wishlists_percent_of_max': 0.026777478180657063,
  'wl_daily_delta': -0.21212121212121215},
 {'_id': 'A Memoir Blue_2021-08-14',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-14 00:00:00'),
  'wishlist_adds': 22,
  'cume_wishlists': 3041,
  'wishlists_percent_of_max': 0.026972610515858936,
  'wl_daily_delta': -0.15384615384615385},
 {'_id': 'A Memoir Blue_2021-08-15',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-15 00:00:00'),
  'wishlist_adds': 32,
  'cume_wishlists': 3073,
  'wishlists_percent_of_max': 0.027256439367061663,
  'wl_daily_delta': 0.4545454545454546},
 {'_id': 'A Memoir Blue_2021-08-16',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-16 00:00:00'),
  'wishlist_adds': 29,
  'cume_wishlists': 3102,
  'wishlists_percent_of_max': 0.027513659263464132,
  'wl_daily_delta': -0.09375},
 {'_id': 'A Memoir Blue_2021-08-17',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-17 00:00:00'),
  'wishlist_adds': 28,
  'cume_wishlists': 3130,
  'wishlists_percent_of_max': 0.027762009508266516,
  'wl_daily_delta': -0.03448275862068961},
 {'_id': 'A Memoir Blue_2021-08-18',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-18 00:00:00'),
  'wishlist_adds': 29,
  'cume_wishlists': 3159,
  'wishlists_percent_of_max': 0.028019229404668985,
  'wl_daily_delta': 0.03571428571428581},
 {'_id': 'A Memoir Blue_2021-08-19',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-19 00:00:00'),
  'wishlist_adds': 52,
  'cume_wishlists': 3211,
  'wishlists_percent_of_max': 0.028480451287873413,
  'wl_daily_delta': 0.7931034482758621},
 {'_id': 'A Memoir Blue_2021-08-20',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-20 00:00:00'),
  'wishlist_adds': 36,
  'cume_wishlists': 3247,
  'wishlists_percent_of_max': 0.028799758745476477,
  'wl_daily_delta': -0.3076923076923077},
 {'_id': 'A Memoir Blue_2021-08-21',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-21 00:00:00'),
  'wishlist_adds': 43,
  'cume_wishlists': 3290,
  'wishlists_percent_of_max': 0.02918115376428014,
  'wl_daily_delta': 0.19444444444444442},
 {'_id': 'A Memoir Blue_2021-08-22',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-22 00:00:00'),
  'wishlist_adds': 32,
  'cume_wishlists': 3322,
  'wishlists_percent_of_max': 0.029464982615482863,
  'wl_daily_delta': -0.2558139534883721},
 {'_id': 'A Memoir Blue_2021-08-23',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-23 00:00:00'),
  'wishlist_adds': 40,
  'cume_wishlists': 3362,
  'wishlists_percent_of_max': 0.02981976867948627,
  'wl_daily_delta': 0.25},
 {'_id': 'A Memoir Blue_2021-08-24',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-24 00:00:00'),
  'wishlist_adds': 25,
  'cume_wishlists': 3387,
  'wishlists_percent_of_max': 0.030041509969488397,
  'wl_daily_delta': -0.375},
 {'_id': 'A Memoir Blue_2021-08-25',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-25 00:00:00'),
  'wishlist_adds': 25,
  'cume_wishlists': 3412,
  'wishlists_percent_of_max': 0.030263251259490528,
  'wl_daily_delta': 0.0},
 {'_id': 'A Memoir Blue_2021-08-26',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-26 00:00:00'),
  'wishlist_adds': 25,
  'cume_wishlists': 3437,
  'wishlists_percent_of_max': 0.030484992549492655,
  'wl_daily_delta': 0.0},
 {'_id': 'A Memoir Blue_2021-08-27',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-27 00:00:00'),
  'wishlist_adds': 26,
  'cume_wishlists': 3463,
  'wishlists_percent_of_max': 0.03071560349109487,
  'wl_daily_delta': 0.040000000000000036},
 {'_id': 'A Memoir Blue_2021-08-28',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-28 00:00:00'),
  'wishlist_adds': 20,
  'cume_wishlists': 3483,
  'wishlists_percent_of_max': 0.030892996523096572,
  'wl_daily_delta': -0.23076923076923073},
 {'_id': 'A Memoir Blue_2021-08-29',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-29 00:00:00'),
  'wishlist_adds': 34,
  'cume_wishlists': 3517,
  'wishlists_percent_of_max': 0.031194564677499467,
  'wl_daily_delta': 0.7},
 {'_id': 'A Memoir Blue_2021-08-30',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-30 00:00:00'),
  'wishlist_adds': 17,
  'cume_wishlists': 3534,
  'wishlists_percent_of_max': 0.031345348754700915,
  'wl_daily_delta': -0.5},
 {'_id': 'A Memoir Blue_2021-08-31',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-31 00:00:00'),
  'wishlist_adds': 17,
  'cume_wishlists': 3551,
  'wishlists_percent_of_max': 0.03149613283190236,
  'wl_daily_delta': 0.0},
 {'_id': 'A Memoir Blue_2021-09-01',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-01 00:00:00'),
  'wishlist_adds': 14,
  'cume_wishlists': 3565,
  'wishlists_percent_of_max': 0.03162030795430355,
  'wl_daily_delta': -0.17647058823529416},
 {'_id': 'A Memoir Blue_2021-09-02',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-02 00:00:00'),
  'wishlist_adds': 23,
  'cume_wishlists': 3588,
  'wishlists_percent_of_max': 0.031824309941105515,
  'wl_daily_delta': 0.6428571428571428},
 {'_id': 'A Memoir Blue_2021-09-03',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-03 00:00:00'),
  'wishlist_adds': 18,
  'cume_wishlists': 3606,
  'wishlists_percent_of_max': 0.031983963669907044,
  'wl_daily_delta': -0.21739130434782605},
 {'_id': 'A Memoir Blue_2021-09-04',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-04 00:00:00'),
  'wishlist_adds': 18,
  'cume_wishlists': 3624,
  'wishlists_percent_of_max': 0.03214361739870858,
  'wl_daily_delta': 0.0},
 {'_id': 'A Memoir Blue_2021-09-05',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-05 00:00:00'),
  'wishlist_adds': 17,
  'cume_wishlists': 3641,
  'wishlists_percent_of_max': 0.03229440147591003,
  'wl_daily_delta': -0.05555555555555558},
 {'_id': 'A Memoir Blue_2021-09-06',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-06 00:00:00'),
  'wishlist_adds': 19,
  'cume_wishlists': 3660,
  'wishlists_percent_of_max': 0.032462924856311644,
  'wl_daily_delta': 0.11764705882352944},
 {'_id': 'A Memoir Blue_2021-09-07',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-07 00:00:00'),
  'wishlist_adds': 21,
  'cume_wishlists': 3681,
  'wishlists_percent_of_max': 0.03264918753991343,
  'wl_daily_delta': 0.10526315789473695},
 {'_id': 'A Memoir Blue_2021-09-08',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-08 00:00:00'),
  'wishlist_adds': 24,
  'cume_wishlists': 3705,
  'wishlists_percent_of_max': 0.03286205917831547,
  'wl_daily_delta': 0.1428571428571428},
 {'_id': 'A Memoir Blue_2021-09-09',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-09 00:00:00'),
  'wishlist_adds': 40,
  'cume_wishlists': 3745,
  'wishlists_percent_of_max': 0.03321684524231888,
  'wl_daily_delta': 0.6666666666666667},
 {'_id': 'A Memoir Blue_2021-09-10',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-10 00:00:00'),
  'wishlist_adds': 34,
  'cume_wishlists': 3779,
  'wishlists_percent_of_max': 0.03351841339672178,
  'wl_daily_delta': -0.15000000000000002},
 {'_id': 'A Memoir Blue_2021-09-11',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-11 00:00:00'),
  'wishlist_adds': 38,
  'cume_wishlists': 3817,
  'wishlists_percent_of_max': 0.03385546015752501,
  'wl_daily_delta': 0.11764705882352944},
 {'_id': 'A Memoir Blue_2021-09-12',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-12 00:00:00'),
  'wishlist_adds': 32,
  'cume_wishlists': 3849,
  'wishlists_percent_of_max': 0.03413928900872774,
  'wl_daily_delta': -0.1578947368421053},
 {'_id': 'A Memoir Blue_2021-09-13',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-13 00:00:00'),
  'wishlist_adds': 25,
  'cume_wishlists': 3874,
  'wishlists_percent_of_max': 0.03436103029872987,
  'wl_daily_delta': -0.21875},
 {'_id': 'A Memoir Blue_2021-09-14',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-14 00:00:00'),
  'wishlist_adds': 16,
  'cume_wishlists': 3890,
  'wishlists_percent_of_max': 0.03450294472433123,
  'wl_daily_delta': -0.36},
 {'_id': 'A Memoir Blue_2021-09-15',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-15 00:00:00'),
  'wishlist_adds': 32,
  'cume_wishlists': 3922,
  'wishlists_percent_of_max': 0.034786773575533954,
  'wl_daily_delta': 1.0},
 {'_id': 'A Memoir Blue_2021-09-16',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-16 00:00:00'),
  'wishlist_adds': 17,
  'cume_wishlists': 3939,
  'wishlists_percent_of_max': 0.0349375576527354,
  'wl_daily_delta': -0.46875},
 {'_id': 'A Memoir Blue_2021-09-17',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-17 00:00:00'),
  'wishlist_adds': 14,
  'cume_wishlists': 3953,
  'wishlists_percent_of_max': 0.03506173277513659,
  'wl_daily_delta': -0.17647058823529416},
 {'_id': 'A Memoir Blue_2021-09-18',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-18 00:00:00'),
  'wishlist_adds': 14,
  'cume_wishlists': 3967,
  'wishlists_percent_of_max': 0.03518590789753778,
  'wl_daily_delta': 0.0},
 {'_id': 'A Memoir Blue_2021-09-19',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-19 00:00:00'),
  'wishlist_adds': 23,
  'cume_wishlists': 3990,
  'wishlists_percent_of_max': 0.035389909884339744,
  'wl_daily_delta': 0.6428571428571428},
 {'_id': 'A Memoir Blue_2021-09-20',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-20 00:00:00'),
  'wishlist_adds': 10,
  'cume_wishlists': 4000,
  'wishlists_percent_of_max': 0.0354786064003406,
  'wl_daily_delta': -0.5652173913043479},
 {'_id': 'A Memoir Blue_2021-09-21',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-21 00:00:00'),
  'wishlist_adds': 20,
  'cume_wishlists': 4020,
  'wishlists_percent_of_max': 0.035655999432342295,
  'wl_daily_delta': 1.0},
 {'_id': 'A Memoir Blue_2021-09-22',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-22 00:00:00'),
  'wishlist_adds': 18,
  'cume_wishlists': 4038,
  'wishlists_percent_of_max': 0.03581565316114383,
  'wl_daily_delta': -0.09999999999999998},
 {'_id': 'A Memoir Blue_2021-09-23',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-23 00:00:00'),
  'wishlist_adds': 10,
  'cume_wishlists': 4048,
  'wishlists_percent_of_max': 0.03590434967714468,
  'wl_daily_delta': -0.4444444444444444},
 {'_id': 'A Memoir Blue_2021-09-24',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-24 00:00:00'),
  'wishlist_adds': 14,
  'cume_wishlists': 4062,
  'wishlists_percent_of_max': 0.03602852479954587,
  'wl_daily_delta': 0.3999999999999999},
 {'_id': 'A Memoir Blue_2021-09-25',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-25 00:00:00'),
  'wishlist_adds': 12,
  'cume_wishlists': 4074,
  'wishlists_percent_of_max': 0.036134960618746895,
  'wl_daily_delta': -0.1428571428571429},
 {'_id': 'A Memoir Blue_2021-09-26',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-26 00:00:00'),
  'wishlist_adds': 11,
  'cume_wishlists': 4085,
  'wishlists_percent_of_max': 0.036232526786347835,
  'wl_daily_delta': -0.08333333333333337},
 {'_id': 'A Memoir Blue_2021-09-27',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-27 00:00:00'),
  'wishlist_adds': 13,
  'cume_wishlists': 4098,
  'wishlists_percent_of_max': 0.03634783225714894,
  'wl_daily_delta': 0.18181818181818188},
 {'_id': 'A Memoir Blue_2021-09-28',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-28 00:00:00'),
  'wishlist_adds': 31,
  'cume_wishlists': 4129,
  'wishlists_percent_of_max': 0.036622791456751576,
  'wl_daily_delta': 1.3846153846153846},
 {'_id': 'A Memoir Blue_2021-09-29',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-29 00:00:00'),
  'wishlist_adds': 28,
  'cume_wishlists': 4157,
  'wishlists_percent_of_max': 0.036871141701553964,
  'wl_daily_delta': -0.09677419354838712},
 {'_id': 'A Memoir Blue_2021-09-30',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-30 00:00:00'),
  'wishlist_adds': 40,
  'cume_wishlists': 4197,
  'wishlists_percent_of_max': 0.037225927765557366,
  'wl_daily_delta': 0.4285714285714286},
 {'_id': 'A Memoir Blue_2021-10-01',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-01 00:00:00'),
  'wishlist_adds': 23,
  'cume_wishlists': 4220,
  'wishlists_percent_of_max': 0.03742992975235933,
  'wl_daily_delta': -0.42500000000000004},
 {'_id': 'A Memoir Blue_2021-10-02',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-02 00:00:00'),
  'wishlist_adds': 18,
  'cume_wishlists': 4238,
  'wishlists_percent_of_max': 0.03758958348116086,
  'wl_daily_delta': -0.21739130434782605},
 {'_id': 'A Memoir Blue_2021-10-03',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-03 00:00:00'),
  'wishlist_adds': 19,
  'cume_wishlists': 4257,
  'wishlists_percent_of_max': 0.03775810686156248,
  'wl_daily_delta': 0.05555555555555558},
 {'_id': 'A Memoir Blue_2021-10-04',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-04 00:00:00'),
  'wishlist_adds': 22,
  'cume_wishlists': 4279,
  'wishlists_percent_of_max': 0.037953239196764355,
  'wl_daily_delta': 0.1578947368421053},
 {'_id': 'A Memoir Blue_2021-10-05',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-05 00:00:00'),
  'wishlist_adds': 19,
  'cume_wishlists': 4298,
  'wishlists_percent_of_max': 0.03812176257716597,
  'wl_daily_delta': -0.13636363636363635},
 {'_id': 'A Memoir Blue_2021-10-06',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-06 00:00:00'),
  'wishlist_adds': 84,
  'cume_wishlists': 4382,
  'wishlists_percent_of_max': 0.03886681331157312,
  'wl_daily_delta': 3.421052631578948},
 {'_id': 'A Memoir Blue_2021-10-07',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-07 00:00:00'),
  'wishlist_adds': 55,
  'cume_wishlists': 4437,
  'wishlists_percent_of_max': 0.0393546441495778,
  'wl_daily_delta': -0.34523809523809523},
 {'_id': 'A Memoir Blue_2021-10-08',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-08 00:00:00'),
  'wishlist_adds': 40,
  'cume_wishlists': 4477,
  'wishlists_percent_of_max': 0.03970943021358121,
  'wl_daily_delta': -0.2727272727272727},
 {'_id': 'A Memoir Blue_2021-10-09',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-09 00:00:00'),
  'wishlist_adds': 48,
  'cume_wishlists': 4525,
  'wishlists_percent_of_max': 0.0401351734903853,
  'wl_daily_delta': 0.19999999999999996},
 {'_id': 'A Memoir Blue_2021-10-10',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-10 00:00:00'),
  'wishlist_adds': 26,
  'cume_wishlists': 4551,
  'wishlists_percent_of_max': 0.04036578443198751,
  'wl_daily_delta': -0.45833333333333337},
 {'_id': 'A Memoir Blue_2021-10-11',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-11 00:00:00'),
  'wishlist_adds': 41,
  'cume_wishlists': 4592,
  'wishlists_percent_of_max': 0.040729440147591,
  'wl_daily_delta': 0.5769230769230769},
 {'_id': 'A Memoir Blue_2021-10-12',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-12 00:00:00'),
  'wishlist_adds': 102,
  'cume_wishlists': 4694,
  'wishlists_percent_of_max': 0.04163414461079969,
  'wl_daily_delta': 1.4878048780487805},
 {'_id': 'A Memoir Blue_2021-10-13',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-13 00:00:00'),
  'wishlist_adds': 72,
  'cume_wishlists': 4766,
  'wishlists_percent_of_max': 0.042272759526005815,
  'wl_daily_delta': -0.2941176470588235},
 {'_id': 'A Memoir Blue_2021-10-14',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-14 00:00:00'),
  'wishlist_adds': 57,
  'cume_wishlists': 4823,
  'wishlists_percent_of_max': 0.04277832966721067,
  'wl_daily_delta': -0.20833333333333337},
 {'_id': 'A Memoir Blue_2021-10-15',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-15 00:00:00'),
  'wishlist_adds': 41,
  'cume_wishlists': 4864,
  'wishlists_percent_of_max': 0.04314198538281416,
  'wl_daily_delta': -0.2807017543859649},
 {'_id': 'A Memoir Blue_2021-10-16',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-16 00:00:00'),
  'wishlist_adds': 38,
  'cume_wishlists': 4902,
  'wishlists_percent_of_max': 0.0434790321436174,
  'wl_daily_delta': -0.07317073170731703},

requests

In [29]:
stop

NameError: name 'stop' is not defined

folder_path = "units/cume_revenues.xlsx"


revs  = pd.read_excel(folder_path, skiprows=2)

In [30]:
from pymongo import UpdateOne

## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [31]:
from datetime import datetime
date_string = datetime.today().strftime('%Y-%m-%d')

In [32]:
db = client['ai_sales_data']
collection = db['units']

unique_products = collection.distinct("product", {"date": {"$gte": 2025-01-01}})

unique_products

In [33]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]




collection.update_many(
    {},
    {
        "$unset": {
            "wishlist_adds": "",
            "cume_wishlists": "",
            "wishlists_percent_of_max": "",
            "wl_daily_delta": ""
        }
    }
)

In [34]:
#####
for batch in batchify(records, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 3999, Inserted: 1, Modified: 3999
Matched: 3992, Inserted: 8, Modified: 3992
Matched: 4000, Inserted: 0, Modified: 4000
Matched: 3987, Inserted: 13, Modified: 3987
Matched: 3999, Inserted: 1, Modified: 3999
Matched: 3999, Inserted: 1, Modified: 3999
Matched: 3998, Inserted: 2, Modified: 3998
Matched: 3998, Inserted: 2, Modified: 3998
Matched: 3994, Inserted: 6, Modified: 3994
Matched: 3990, Inserted: 10, Modified: 3990
Matched: 3992, Inserted: 8, Modified: 3992
Matched: 3991, Inserted: 9, Modified: 3991
Matched: 4000, Inserted: 0, Modified: 4000
Matched: 3999, Inserted: 1, Modified: 3999
Matched: 3991, Inserted: 9, Modified: 3991
Matched: 3999, Inserted: 1, Modified: 3999
Matched: 3993, Inserted: 7, Modified: 3993
Matched: 3997, Inserted: 3, Modified: 3997
Matched: 3998, Inserted: 2, Modified: 3998
Matched: 3999, Inserted: 1, Modified: 3999
Matched: 1418, Inserted: 2, Modified: 1418

collection.update_many({}, {"$unset": {"percent_of_max": ""}})

In [35]:
client.close()