In [1]:
## Download from IndieBI, details by product, All Games No Soundtrack, daily units

In [2]:
import pandas as pd
import glob
import os
import warnings

warnings.filterwarnings("ignore")

In [3]:
import pandas as pd
import glob
import os

# Define folder path
folder_path = "DB_Update/non_owner_impressions/"

# Get all Excel files in the folder
excel_files = glob.glob(os.path.join(folder_path, "*.xlsx"))

# Read and combine all files, skipping first 2 rows
df_list = [pd.read_excel(f, skiprows=2).assign(filename=os.path.basename(f)) for f in excel_files]
combined_df = pd.concat(df_list, ignore_index=True)

In [4]:
combined_df = combined_df.sort_values(by="Day")

In [5]:
wishlists = combined_df.drop_duplicates(subset=['Day', 'product'])
wishlists

,Day,product,Selected Measure,Blank Measure,filename
0,2020-12-14,Ashen,35417,NaN,till2020_impressions.xlsx
461,2020-12-14,Wattam,51007,NaN,since2020_impressions.xlsx
460,2020-12-14,Twelve Minutes,4073,NaN,since2020_impressions.xlsx
459,2020-12-14,The Unfinished Swan,41146,NaN,since2020_impressions.xlsx
458,2020-12-14,The Artful Escape,4057,NaN,since2020_impressions.xlsx
...,...,...,...,...,...
70549,2025-07-27,LEGO Voyagers,27978,NaN,since2020_impressions.xlsx
70550,2025-07-27,Lorelei and the Laser Eyes,21253,NaN,since2020_impressions.xlsx
70551,2025-07-27,Lushfoil Photography Sim,55374,NaN,since2020_impressions.xlsx
70553,2025-07-27,Mixtape,10253,NaN,since2020_impressions.xlsx
70579,2025-07-27,Wheel World,2364050,NaN,since2020_impressions.xlsx

In [6]:

wishlists = wishlists.rename({"Selected Measure":"non_owner_impressions"}, axis=1)

In [7]:
wishlists = wishlists.drop("Blank Measure", axis=1)


wishlists = wishlists.drop("filename", axis=1)

In [8]:
wishlists

             Day                     product  non_owner_impressions
0     2020-12-14                       Ashen                  35417
461   2020-12-14                      Wattam                  51007
460   2020-12-14              Twelve Minutes                   4073
459   2020-12-14         The Unfinished Swan                  41146
458   2020-12-14           The Artful Escape                   4057
...          ...                         ...                    ...
70549 2025-07-27               LEGO Voyagers                  27978
70550 2025-07-27  Lorelei and the Laser Eyes                  21253
70551 2025-07-27    Lushfoil Photography Sim                  55374
70553 2025-07-27                     Mixtape                  10253
70579 2025-07-27                 Wheel World                2364050

[70143 rows x 3 columns]

wishlists

In [9]:

wishlists['cume_non_owner_impressions'] = wishlists.groupby('product')['non_owner_impressions'].cumsum()

In [10]:
wishlists.query("product=='Stray'")

             Day product  non_owner_impressions  cume_non_owner_impressions
456   2020-12-14   Stray                  12511                       12511
481   2020-12-15   Stray                  12016                       24527
506   2020-12-16   Stray                  11372                       35899
94    2020-12-17   Stray                  12397                       48296
555   2020-12-18   Stray                  14428                       62724
...          ...     ...                    ...                         ...
70356 2025-07-23   Stray                1842420                  2497955447
70409 2025-07-24   Stray                1688623                  2499644070
70463 2025-07-25   Stray                 560522                  2500204592
70515 2025-07-26   Stray                 562676                  2500767268
70566 2025-07-27   Stray                 535856                  2501303124

[1687 rows x 4 columns]

stop

In [11]:
folder_path = "wishlists/Annapurna Interactive Historical Revenues - releases_dates.csv"
dates  = pd.read_csv(folder_path)
dates = dates.dropna(subset='pc_release_date')
dates['pc_release_date'] = pd.to_datetime(dates['pc_release_date'])
release_date_dict = dates.groupby('product')['pc_release_date'].min().to_dict()

In [12]:
release_date_dict.get("The Lost Wild")

Timestamp('2026-11-01 00:00:00')

In [13]:
wishlists['release_date'] = pd.to_datetime(wishlists['Day'])


wishlists["non_owner_impressions_percent_of_max"] = wishlists["cume_non_owner_impressions"] / wishlists.groupby("product")["cume_non_owner_impressions"].transform("max")

In [14]:
wishlists['release_date'] = pd.to_datetime(wishlists['Day'])
wishlists['Day'] = pd.to_datetime(wishlists['Day']).dt.to_pydatetime()
wishlists['release_date'] = wishlists.groupby('product')['release_date'].transform('min')
wishlists['release_date'] = wishlists['product'].map(release_date_dict)
wishlists["DAR"] = (wishlists["Day"] - wishlists["release_date"]).dt.days
#df["DAR"] = df.groupby("product")["DAR"].transform(lambda x: x.clip(lower=0))

wishlists["Weeks_from_Release"] = (wishlists["DAR"] // 7) + 1  # Week 1 starts at 0-7 days

df["avg_price"] = df["revenue"] / df["units"]

In [15]:
wishlists

,Day,product,non_owner_impressions,cume_non_owner_impressions,release_date,non_owner_impressions_percent_of_max,DAR,Weeks_from_Release
0,2020-12-14,Ashen,35417,35417,2018-12-07,0.000298,738.0,106.0
461,2020-12-14,Wattam,51007,51007,2020-12-18,0.000900,-4.0,0.0
460,2020-12-14,Twelve Minutes,4073,4073,2021-08-19,0.000013,-248.0,-35.0
459,2020-12-14,The Unfinished Swan,41146,41146,2020-09-10,0.000452,95.0,14.0
458,2020-12-14,The Artful Escape,4057,4057,2021-09-09,0.000040,-269.0,-38.0
...,...,...,...,...,...,...,...,...
70549,2025-07-27,LEGO Voyagers,27978,2927554,2025-09-30,1.000000,-65.0,-9.0
70550,2025-07-27,Lorelei and the Laser Eyes,21253,79114469,2024-05-16,1.000000,437.0,63.0
70551,2025-07-27,Lushfoil Photography Sim,55374,58184694,2025-04-15,1.000000,103.0,15.0
70553,2025-07-27,Mixtape,10253,4521800,2025-12-31,1.000000,-157.0,-22.0
70579,2025-07-27,Wheel World,2364050,28383649,2025-07-23,1.000000,4.0,1.0

In [16]:
value_cols = ["non_owner_impressions",'cume_non_owner_impressions','non_owner_impressions_percent_of_max']

In [17]:
df = wishlists.groupby(["product", "Weeks_from_Release",'DAR','Day','release_date'], as_index=False)[value_cols].max()

df.query("DAR==0")

In [18]:
df.columns = [col.strip().replace(" ", "_").lower() for col in df.columns]
#df['date'] = pd.to_datetime(df['date'], format="%d %B, %Y")

In [19]:
df['product_day'] = df['product'].astype(str) + '_' + df['day'].astype(str)
#df.set_index('product_day', inplace=True)

In [20]:
df['impressions_daily_delta']  = df.groupby('product')['non_owner_impressions'].pct_change()

In [21]:
export = df.query("dar <=0")
export = export.drop_duplicates(subset='product', keep='last')

In [22]:
df.query("product =='Stray' & dar ==0")

,product,weeks_from_release,dar,day,release_date,non_owner_impressions,cume_non_owner_impressions,non_owner_impressions_percent_of_max,product_day,impressions_daily_delta
45901,Stray,1.0,0.0,2022-07-19,2022-07-19,15446200,195596674,0.078198,Stray_2022-07-19,1.097338

In [23]:
export[['product','weeks_from_release', 'non_owner_impressions','cume_non_owner_impressions']]

,product,weeks_from_release,non_owner_impressions,cume_non_owner_impressions
243,A Memoir Blue,1.0,448509,2299131
4371,BattleSage,1.0,182,290472
5518,Bounty Star,-10.0,3580,8037424
6003,Cocoon,1.0,2776506,22627579
9599,Faraway,-22.0,1819,1741566
10457,Flock,1.0,530775,7904231
16377,Hindsight,1.0,417701,4137848
17510,Hohokum,1.0,965076,965107
24026,LEGO Voyagers,-9.0,27978,2927554
24247,Last Stop,1.0,424410,2846219
26407,Lorelei and the Laser Eyes,1.0,1421728,5241928
28163,Lushfoil Photography Sim,1.0,3857819,16321778
28345,Maquette,1.0,1762512,3450306
30385,Mixtape,-22.0,10253,4521800
30665,Morsels,1.0,14342,2346738
30907,Mundaun,1.0,1055913,4261082
32990,Neon White,1.0,3942806,18155069
34528,No Goblin Game 3,-28.0,3436,393545
35729,Open Roads,1.0,705249,13342065
37968,Outer Wilds - Echoes of the Eye DLC,1.0,1495881,3100765
42652,Skin Deep,1.0,3137287,18294100
42874,Solar Ash,1.0,1426134,3732775
44461,Storyteller,1.0,2216920,15933034
45901,Stray,1.0,15446200,195596674
48962,The Artful Escape,1.0,776492,5579701
51488,The Lost Wild,-65.0,22133,30167355
51604,The Pathless,1.0,822641,1673443
55368,Thirsty Suitors,1.0,768312,9518200
56250,Twelve Minutes,1.0,8473549,56464993
58007,Wanderstop,1.0,4226999,20753803
58150,Wattam,1.0,731722,1841171
62360,Wheel World,1.0,1755208,15782354
63082,to a T,1.0,857697,6940892

df

In [24]:
export[['product','weeks_from_release', 'non_owner_impressions','cume_non_owner_impressions']].to_clipboard()

In [25]:
final_df = df.query("cume_non_owner_impressions	>0")

In [26]:
final_df

,product,weeks_from_release,dar,day,release_date,non_owner_impressions,cume_non_owner_impressions,non_owner_impressions_percent_of_max,product_day,impressions_daily_delta
5,A Memoir Blue,-33.0,-238.0,2021-07-29,2022-03-24,2253,2253,0.000075,A Memoir Blue_2021-07-29,inf
6,A Memoir Blue,-33.0,-237.0,2021-07-30,2022-03-24,10089,12342,0.000412,A Memoir Blue_2021-07-30,3.478029
7,A Memoir Blue,-33.0,-236.0,2021-07-31,2022-03-24,7988,20330,0.000679,A Memoir Blue_2021-07-31,-0.208247
8,A Memoir Blue,-33.0,-235.0,2021-08-01,2022-03-24,5819,26149,0.000873,A Memoir Blue_2021-08-01,-0.271532
9,A Memoir Blue,-33.0,-234.0,2021-08-02,2022-03-24,5216,31365,0.001048,A Memoir Blue_2021-08-02,-0.103626
...,...,...,...,...,...,...,...,...,...,...
63138,to a T,9.0,56.0,2025-07-23,2025-05-28,37731,13496733,0.988887,to a T_2025-07-23,0.055885
63139,to a T,9.0,57.0,2025-07-24,2025-05-28,37755,13534488,0.991654,to a T_2025-07-24,0.000636
63140,to a T,9.0,58.0,2025-07-25,2025-05-28,34989,13569477,0.994217,to a T_2025-07-25,-0.073262
63141,to a T,9.0,59.0,2025-07-26,2025-05-28,39063,13608540,0.997079,to a T_2025-07-26,0.116437
63142,to a T,9.0,60.0,2025-07-27,2025-05-28,39861,13648401,1.000000,to a T_2025-07-27,0.020429

In [27]:
# Restructure each row
records = []
for _, row in final_df.iterrows():
    doc = {'_id': row['product_day'],
           'product': row['product'],
           'day': row['day'],
            "non_owner_impressions": row["non_owner_impressions"],
            "cume_non_owner_impressions": row["cume_non_owner_impressions"],
            "non_owner_impressions_percent_of_max": row["non_owner_impressions_percent_of_max"],
            "impressions_daily_delta": row["impressions_daily_delta"],

    }
    records.append(doc)

records = df.to_dict(orient="records")
records

In [28]:
records

[{'_id': 'A Memoir Blue_2021-07-29',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-07-29 00:00:00'),
  'non_owner_impressions': 2253,
  'cume_non_owner_impressions': 2253,
  'non_owner_impressions_percent_of_max': 7.524561280170677e-05,
  'impressions_daily_delta': inf},
 {'_id': 'A Memoir Blue_2021-07-30',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-07-30 00:00:00'),
  'non_owner_impressions': 10089,
  'cume_non_owner_impressions': 12342,
  'non_owner_impressions_percent_of_max': 0.00041219767119337106,
  'impressions_daily_delta': 3.478029294274301},
 {'_id': 'A Memoir Blue_2021-07-31',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-07-31 00:00:00'),
  'non_owner_impressions': 7988,
  'cume_non_owner_impressions': 20330,
  'non_owner_impressions_percent_of_max': 0.0006789806073052368,
  'impressions_daily_delta': -0.20824660521359895},
 {'_id': 'A Memoir Blue_2021-08-01',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-01 00:00:00'),
  'non_owner_impressions': 5819,
  'cume_non_owner_impressions': 26149,
  'non_owner_impressions_percent_of_max': 0.0008733233595880295,
  'impressions_daily_delta': -0.27153229844767146},
 {'_id': 'A Memoir Blue_2021-08-02',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-02 00:00:00'),
  'non_owner_impressions': 5216,
  'cume_non_owner_impressions': 31365,
  'non_owner_impressions_percent_of_max': 0.0010475271396029884,
  'impressions_daily_delta': -0.10362605258635504},
 {'_id': 'A Memoir Blue_2021-08-03',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-03 00:00:00'),
  'non_owner_impressions': 5148,
  'cume_non_owner_impressions': 36513,
  'non_owner_impressions_percent_of_max': 0.0012194598580686725,
  'impressions_daily_delta': -0.0130368098159509},
 {'_id': 'A Memoir Blue_2021-08-04',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-04 00:00:00'),
  'non_owner_impressions': 4506,
  'cume_non_owner_impressions': 41019,
  'non_owner_impressions_percent_of_max': 0.001369951083672086,
  'impressions_daily_delta': -0.12470862470862476},
 {'_id': 'A Memoir Blue_2021-08-05',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-05 00:00:00'),
  'non_owner_impressions': 3509,
  'cume_non_owner_impressions': 44528,
  'non_owner_impressions_percent_of_max': 0.0014871445392074564,
  'impressions_daily_delta': -0.2212605415002219},
 {'_id': 'A Memoir Blue_2021-08-06',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-06 00:00:00'),
  'non_owner_impressions': 3151,
  'cume_non_owner_impressions': 47679,
  'non_owner_impressions_percent_of_max': 0.001592381523645174,
  'impressions_daily_delta': -0.10202336848104876},
 {'_id': 'A Memoir Blue_2021-08-07',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-07 00:00:00'),
  'non_owner_impressions': 3642,
  'cume_non_owner_impressions': 51321,
  'non_owner_impressions_percent_of_max': 0.001714016908387214,
  'impressions_daily_delta': 0.15582354807997456},
 {'_id': 'A Memoir Blue_2021-08-08',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-08 00:00:00'),
  'non_owner_impressions': 4171,
  'cume_non_owner_impressions': 55492,
  'non_owner_impressions_percent_of_max': 0.0018533198160640533,
  'impressions_daily_delta': 0.14524986271279516},
 {'_id': 'A Memoir Blue_2021-08-09',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-09 00:00:00'),
  'non_owner_impressions': 4316,
  'cume_non_owner_impressions': 59808,
  'non_owner_impressions_percent_of_max': 0.0019974654285150814,
  'impressions_daily_delta': 0.03476384560057544},
 {'_id': 'A Memoir Blue_2021-08-10',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-10 00:00:00'),
  'non_owner_impressions': 4269,
  'cume_non_owner_impressions': 64077,
  'non_owner_impressions_percent_of_max': 0.0021400413366599934,
  'impressions_daily_delta': -0.010889712696941611},
 {'_id': 'A Memoir Blue_2021-08-11',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-11 00:00:00'),
  'non_owner_impressions': 4033,
  'cume_non_owner_impressions': 68110,
  'non_owner_impressions_percent_of_max': 0.0022747353253103632,
  'impressions_daily_delta': -0.05528226750995546},
 {'_id': 'A Memoir Blue_2021-08-12',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-12 00:00:00'),
  'non_owner_impressions': 3593,
  'cume_non_owner_impressions': 71703,
  'non_owner_impressions_percent_of_max': 0.002394734209818367,
  'impressions_daily_delta': -0.10909992561368709},
 {'_id': 'A Memoir Blue_2021-08-13',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-13 00:00:00'),
  'non_owner_impressions': 5220,
  'cume_non_owner_impressions': 76923,
  'non_owner_impressions_percent_of_max': 0.0025690715816891656,
  'impressions_daily_delta': 0.45282493737823537},
 {'_id': 'A Memoir Blue_2021-08-14',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-14 00:00:00'),
  'non_owner_impressions': 3626,
  'cume_non_owner_impressions': 80549,
  'non_owner_impressions_percent_of_max': 0.0026901725990078466,
  'impressions_daily_delta': -0.30536398467432946},
 {'_id': 'A Memoir Blue_2021-08-15',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-15 00:00:00'),
  'non_owner_impressions': 3145,
  'cume_non_owner_impressions': 83694,
  'non_owner_impressions_percent_of_max': 0.002795209195661805,
  'impressions_daily_delta': -0.13265306122448983},
 {'_id': 'A Memoir Blue_2021-08-16',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-16 00:00:00'),
  'non_owner_impressions': 3202,
  'cume_non_owner_impressions': 86896,
  'non_owner_impressions_percent_of_max': 0.0029021494762614787,
  'impressions_daily_delta': 0.01812400635930045},
 {'_id': 'A Memoir Blue_2021-08-17',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-17 00:00:00'),
  'non_owner_impressions': 3433,
  'cume_non_owner_impressions': 90329,
  'non_owner_impressions_percent_of_max': 0.0030168046865358946,
  'impressions_daily_delta': 0.07214241099312924},
 {'_id': 'A Memoir Blue_2021-08-18',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-18 00:00:00'),
  'non_owner_impressions': 4042,
  'cume_non_owner_impressions': 94371,
  'non_owner_impressions_percent_of_max': 0.003151799256861904,
  'impressions_daily_delta': 0.17739586367608506},
 {'_id': 'A Memoir Blue_2021-08-19',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-19 00:00:00'),
  'non_owner_impressions': 10077,
  'cume_non_owner_impressions': 104448,
  'non_owner_impressions_percent_of_max': 0.003488350539686049,
  'impressions_daily_delta': 1.4930727362691738},
 {'_id': 'A Memoir Blue_2021-08-20',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-20 00:00:00'),
  'non_owner_impressions': 9682,
  'cume_non_owner_impressions': 114130,
  'non_owner_impressions_percent_of_max': 0.003811709626746025,
  'impressions_daily_delta': -0.03919817405974002},
 {'_id': 'A Memoir Blue_2021-08-21',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-21 00:00:00'),
  'non_owner_impressions': 7562,
  'cume_non_owner_impressions': 121692,
  'non_owner_impressions_percent_of_max': 0.004064265030210963,
  'impressions_daily_delta': -0.21896302416856017},
 {'_id': 'A Memoir Blue_2021-08-22',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-22 00:00:00'),
  'non_owner_impressions': 6599,
  'cume_non_owner_impressions': 128291,
  'non_owner_impressions_percent_of_max': 0.0042846581943824956,
  'impressions_daily_delta': -0.12734726262893414},
 {'_id': 'A Memoir Blue_2021-08-23',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-23 00:00:00'),
  'non_owner_impressions': 6071,
  'cume_non_owner_impressions': 134362,
  'non_owner_impressions_percent_of_max': 0.004487417233583189,
  'impressions_daily_delta': -0.08001212304894678},
 {'_id': 'A Memoir Blue_2021-08-24',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-24 00:00:00'),
  'non_owner_impressions': 6146,
  'cume_non_owner_impressions': 140508,
  'non_owner_impressions_percent_of_max': 0.004692681120080876,
  'impressions_daily_delta': 0.012353813210344233},
 {'_id': 'A Memoir Blue_2021-08-25',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-25 00:00:00'),
  'non_owner_impressions': 5062,
  'cume_non_owner_impressions': 145570,
  'non_owner_impressions_percent_of_max': 0.004861741613646007,
  'impressions_daily_delta': -0.17637487796941098},
 {'_id': 'A Memoir Blue_2021-08-26',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-26 00:00:00'),
  'non_owner_impressions': 4280,
  'cume_non_owner_impressions': 149850,
  'non_owner_impressions_percent_of_max': 0.005004684899394478,
  'impressions_daily_delta': -0.1544843935203477},
 {'_id': 'A Memoir Blue_2021-08-27',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-27 00:00:00'),
  'non_owner_impressions': 3455,
  'cume_non_owner_impressions': 153305,
  'non_owner_impressions_percent_of_max': 0.0051200748648760125,
  'impressions_daily_delta': -0.19275700934579443},
 {'_id': 'A Memoir Blue_2021-08-28',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-28 00:00:00'),
  'non_owner_impressions': 3311,
  'cume_non_owner_impressions': 156616,
  'non_owner_impressions_percent_of_max': 0.005230655523547318,
  'impressions_daily_delta': -0.041678726483357464},
 {'_id': 'A Memoir Blue_2021-08-29',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-29 00:00:00'),
  'non_owner_impressions': 3585,
  'cume_non_owner_impressions': 160201,
  'non_owner_impressions_percent_of_max': 0.0053503872243436425,
  'impressions_daily_delta': 0.08275445484747812},
 {'_id': 'A Memoir Blue_2021-08-30',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-30 00:00:00'),
  'non_owner_impressions': 3152,
  'cume_non_owner_impressions': 163353,
  'non_owner_impressions_percent_of_max': 0.00545565760674532,
  'impressions_daily_delta': -0.1207810320781032},
 {'_id': 'A Memoir Blue_2021-08-31',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-31 00:00:00'),
  'non_owner_impressions': 2919,
  'cume_non_owner_impressions': 166272,
  'non_owner_impressions_percent_of_max': 0.005553146263544336,
  'impressions_daily_delta': -0.07392131979695427},
 {'_id': 'A Memoir Blue_2021-09-01',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-01 00:00:00'),
  'non_owner_impressions': 2416,
  'cume_non_owner_impressions': 168688,
  'non_owner_impressions_percent_of_max': 0.00563383574447151,
  'impressions_daily_delta': -0.17231928742720115},
 {'_id': 'A Memoir Blue_2021-09-02',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-02 00:00:00'),
  'non_owner_impressions': 2307,
  'cume_non_owner_impressions': 170995,
  'non_owner_impressions_percent_of_max': 0.0057108848473270525,
  'impressions_daily_delta': -0.04511589403973515},
 {'_id': 'A Memoir Blue_2021-09-03',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-03 00:00:00'),
  'non_owner_impressions': 2267,
  'cume_non_owner_impressions': 173262,
  'non_owner_impressions_percent_of_max': 0.0057865980316241985,
  'impressions_daily_delta': -0.01733853489380144},
 {'_id': 'A Memoir Blue_2021-09-04',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-04 00:00:00'),
  'non_owner_impressions': 2658,
  'cume_non_owner_impressions': 175920,
  'non_owner_impressions_percent_of_max': 0.005875369819829674,
  'impressions_daily_delta': 0.172474636082929},
 {'_id': 'A Memoir Blue_2021-09-05',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-05 00:00:00'),
  'non_owner_impressions': 2713,
  'cume_non_owner_impressions': 178633,
  'non_owner_impressions_percent_of_max': 0.0059659784960529455,
  'impressions_daily_delta': 0.020692249811888663},
 {'_id': 'A Memoir Blue_2021-09-06',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-06 00:00:00'),
  'non_owner_impressions': 2433,
  'cume_non_owner_impressions': 181066,
  'non_owner_impressions_percent_of_max': 0.006047235742367438,
  'impressions_daily_delta': -0.10320678215997048},
 {'_id': 'A Memoir Blue_2021-09-07',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-07 00:00:00'),
  'non_owner_impressions': 2475,
  'cume_non_owner_impressions': 183541,
  'non_owner_impressions_percent_of_max': 0.006129895703168247,
  'impressions_daily_delta': 0.01726263871763245},
 {'_id': 'A Memoir Blue_2021-09-08',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-08 00:00:00'),
  'non_owner_impressions': 2409,
  'cume_non_owner_impressions': 185950,
  'non_owner_impressions_percent_of_max': 0.006210351398347702,
  'impressions_daily_delta': -0.026666666666666616},
 {'_id': 'A Memoir Blue_2021-09-09',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-09 00:00:00'),
  'non_owner_impressions': 3678,
  'cume_non_owner_impressions': 189628,
  'non_owner_impressions_percent_of_max': 0.0063331891097923,
  'impressions_daily_delta': 0.5267745952677461},
 {'_id': 'A Memoir Blue_2021-09-10',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-10 00:00:00'),
  'non_owner_impressions': 6235,
  'cume_non_owner_impressions': 195863,
  'non_owner_impressions_percent_of_max': 0.006541425415082421,
  'impressions_daily_delta': 0.6952147906470909},
 {'_id': 'A Memoir Blue_2021-09-11',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-11 00:00:00'),
  'non_owner_impressions': 4909,
  'cume_non_owner_impressions': 200772,
  'non_owner_impressions_percent_of_max': 0.006705376020161683,
  'impressions_daily_delta': -0.21267040898155576},
 {'_id': 'A Memoir Blue_2021-09-12',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-12 00:00:00'),
  'non_owner_impressions': 4906,
  'cume_non_owner_impressions': 205678,
  'non_owner_impressions_percent_of_max': 0.006869226431349066,
  'impressions_daily_delta': -0.0006111224281931671},
 {'_id': 'A Memoir Blue_2021-09-13',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-13 00:00:00'),
  'non_owner_impressions': 4125,
  'cume_non_owner_impressions': 209803,
  'non_owner_impressions_percent_of_max': 0.0070069930326837485,
  'impressions_daily_delta': -0.15919282511210764},
 {'_id': 'A Memoir Blue_2021-09-14',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-14 00:00:00'),
  'non_owner_impressions': 3896,
  'cume_non_owner_impressions': 213699,
  'non_owner_impressions_percent_of_max': 0.007137111500271609,
  'impressions_daily_delta': -0.05551515151515152},
 {'_id': 'A Memoir Blue_2021-09-15',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-15 00:00:00'),
  'non_owner_impressions': 3759,
  'cume_non_owner_impressions': 217458,
  'non_owner_impressions_percent_of_max': 0.00726265444679696,
  'impressions_daily_delta': -0.03516427104722797},
 {'_id': 'A Memoir Blue_2021-09-16',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-16 00:00:00'),
  'non_owner_impressions': 3498,
  'cume_non_owner_impressions': 220956,
  'non_owner_impressions_percent_of_max': 0.007379480524728771,
  'impressions_daily_delta': -0.06943335993615318},
 {'_id': 'A Memoir Blue_2021-09-17',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-17 00:00:00'),
  'non_owner_impressions': 2489,
  'cume_non_owner_impressions': 223445,
  'non_owner_impressions_percent_of_max': 0.007462608057025019,
  'impressions_daily_delta': -0.2884505431675243},
 {'_id': 'A Memoir Blue_2021-09-18',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-18 00:00:00'),
  'non_owner_impressions': 2522,
  'cume_non_owner_impressions': 225967,
  'non_owner_impressions_percent_of_max': 0.007546837722131946,
  'impressions_daily_delta': 0.013258336681398086},
 {'_id': 'A Memoir Blue_2021-09-19',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-19 00:00:00'),
  'non_owner_impressions': 2674,
  'cume_non_owner_impressions': 228641,
  'non_owner_impressions_percent_of_max': 0.0076361438777607805,
  'impressions_daily_delta': 0.060269627279936566},
 {'_id': 'A Memoir Blue_2021-09-20',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-20 00:00:00'),
  'non_owner_impressions': 2319,
  'cume_non_owner_impressions': 230960,
  'non_owner_impressions_percent_of_max': 0.007713593756183842,
  'impressions_daily_delta': -0.1327599102468212},
 {'_id': 'A Memoir Blue_2021-09-21',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-21 00:00:00'),
  'non_owner_impressions': 2257,
  'cume_non_owner_impressions': 233217,
  'non_owner_impressions_percent_of_max': 0.007788972960841388,
  'impressions_daily_delta': -0.026735661923242726},
 {'_id': 'A Memoir Blue_2021-09-22',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-22 00:00:00'),
  'non_owner_impressions': 2121,
  'cume_non_owner_impressions': 235338,
  'non_owner_impressions_percent_of_max': 0.007859810042400385,
  'impressions_daily_delta': -0.06025697828976517},
 {'_id': 'A Memoir Blue_2021-09-23',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-23 00:00:00'),
  'non_owner_impressions': 2148,
  'cume_non_owner_impressions': 237486,
  'non_owner_impressions_percent_of_max': 0.0079315488689863,
  'impressions_daily_delta': 0.012729844413012836},
 {'_id': 'A Memoir Blue_2021-09-24',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-24 00:00:00'),
  'non_owner_impressions': 2291,
  'cume_non_owner_impressions': 239777,
  'non_owner_impressions_percent_of_max': 0.008008063604418483,
  'impressions_daily_delta': 0.06657355679702048},
 {'_id': 'A Memoir Blue_2021-09-25',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-25 00:00:00'),
  'non_owner_impressions': 2478,
  'cume_non_owner_impressions': 242255,
  'non_owner_impressions_percent_of_max': 0.008090823759111174,
  'impressions_daily_delta': 0.08162374508948056},
 {'_id': 'A Memoir Blue_2021-09-26',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-26 00:00:00'),
  'non_owner_impressions': 2496,
  'cume_non_owner_impressions': 244751,
  'non_owner_impressions_percent_of_max': 0.008174185077155142,
  'impressions_daily_delta': 0.007263922518159882},
 {'_id': 'A Memoir Blue_2021-09-27',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-27 00:00:00'),
  'non_owner_impressions': 2971,
  'cume_non_owner_impressions': 247722,
  'non_owner_impressions_percent_of_max': 0.008273410428080073,
  'impressions_daily_delta': 0.19030448717948723},
 {'_id': 'A Memoir Blue_2021-09-28',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-28 00:00:00'),
  'non_owner_impressions': 6052,
  'cume_non_owner_impressions': 253774,
  'non_owner_impressions_percent_of_max': 0.008475534905965528,
  'impressions_daily_delta': 1.0370245708515653},
 {'_id': 'A Memoir Blue_2021-09-29',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-29 00:00:00'),
  'non_owner_impressions': 6604,
  'cume_non_owner_impressions': 260378,
  'non_owner_impressions_percent_of_max': 0.00869609505995686,
  'impressions_daily_delta': 0.09120951751487105},
 {'_id': 'A Memoir Blue_2021-09-30',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-30 00:00:00'),
  'non_owner_impressions': 4252,
  'cume_non_owner_impressions': 264630,
  'non_owner_impressions_percent_of_max': 0.008838103202714453,
  'impressions_daily_delta': -0.3561477892186553},
 {'_id': 'A Memoir Blue_2021-10-01',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-01 00:00:00'),
  'non_owner_impressions': 1948,
  'cume_non_owner_impressions': 266578,
  'non_owner_impressions_percent_of_max': 0.008903162436508382,
  'impressions_daily_delta': -0.5418626528692381},
 {'_id': 'A Memoir Blue_2021-10-02',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-02 00:00:00'),
  'non_owner_impressions': 4403,
  'cume_non_owner_impressions': 270981,
  'non_owner_impressions_percent_of_max': 0.009050213671823924,
  'impressions_daily_delta': 1.2602669404517455},
 {'_id': 'A Memoir Blue_2021-10-03',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-03 00:00:00'),
  'non_owner_impressions': 4094,
  'cume_non_owner_impressions': 275075,
  'non_owner_impressions_percent_of_max': 0.00918694493627585,
  'impressions_daily_delta': -0.07017942312059955},

requests

In [29]:
stop

NameError: name 'stop' is not defined

folder_path = "units/cume_revenues.xlsx"


revs  = pd.read_excel(folder_path, skiprows=2)

In [30]:
from pymongo import UpdateOne

## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [31]:
from datetime import datetime
date_string = datetime.today().strftime('%Y-%m-%d')

In [32]:
db = client['ai_sales_data']
collection = db['units']

unique_products = collection.distinct("product", {"date": {"$gte": 2025-01-01}})

unique_products

In [33]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]




collection.update_many(
    {},
    {
        "$unset": {
            "wishlist_adds": "",
            "cume_wishlists": "",
            "wishlists_percent_of_max": "",
            "wl_daily_delta": ""
        }
    }
)

In [34]:
#####
for batch in batchify(records, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 2515, Inserted: 0, Modified: 0

collection.update_many({}, {"$unset": {"percent_of_max": ""}})

In [35]:
client.close()