In [1]:
## Download from IndieBI, details by product, All Games No Soundtrack, daily units

In [2]:
import pandas as pd
import glob
import os
import warnings

warnings.filterwarnings("ignore")

In [3]:
import pandas as pd
import glob
import os

# Define folder path
folder_path = "DB_Update/non_owner visits/"

# Get all Excel files in the folder
excel_files = glob.glob(os.path.join(folder_path, "*.xlsx"))

# Read and combine all files, skipping first 2 rows
df_list = [pd.read_excel(f, skiprows=2).assign(filename=os.path.basename(f)) for f in excel_files]
combined_df = pd.concat(df_list, ignore_index=True)

In [4]:
combined_df = combined_df.sort_values(by="Day")

In [5]:
wishlists = combined_df.drop_duplicates(subset=['Day', 'product'])
wishlists

,Day,product,Selected Measure,Blank Measure,filename
0,2020-12-14,Ashen,2034,NaN,till2020_visits.xlsx
461,2020-12-14,Wattam,988,NaN,since2020_visits.xlsx
460,2020-12-14,Twelve Minutes,633,NaN,since2020_visits.xlsx
459,2020-12-14,The Unfinished Swan,1559,NaN,since2020_visits.xlsx
458,2020-12-14,The Artful Escape,225,NaN,since2020_visits.xlsx
...,...,...,...,...,...
70549,2025-07-27,LEGO Voyagers,1888,NaN,since2020_visits.xlsx
70550,2025-07-27,Lorelei and the Laser Eyes,1067,NaN,since2020_visits.xlsx
70551,2025-07-27,Lushfoil Photography Sim,2810,NaN,since2020_visits.xlsx
70553,2025-07-27,Mixtape,708,NaN,since2020_visits.xlsx
70579,2025-07-27,Wheel World,44440,NaN,since2020_visits.xlsx

In [6]:

wishlists = wishlists.rename({"Selected Measure":"non_owner_visits"}, axis=1)

In [7]:
wishlists = wishlists.drop("Blank Measure", axis=1)


wishlists = wishlists.drop("filename", axis=1)

In [8]:
wishlists

             Day                     product  non_owner_visits
0     2020-12-14                       Ashen              2034
461   2020-12-14                      Wattam               988
460   2020-12-14              Twelve Minutes               633
459   2020-12-14         The Unfinished Swan              1559
458   2020-12-14           The Artful Escape               225
...          ...                         ...               ...
70549 2025-07-27               LEGO Voyagers              1888
70550 2025-07-27  Lorelei and the Laser Eyes              1067
70551 2025-07-27    Lushfoil Photography Sim              2810
70553 2025-07-27                     Mixtape               708
70579 2025-07-27                 Wheel World             44440

[70143 rows x 3 columns]

wishlists

In [9]:

wishlists['cume_non_owner_visits'] = wishlists.groupby('product')['non_owner_visits'].cumsum()

In [10]:
wishlists.query("product=='Stray'")

             Day product  non_owner_visits  cume_non_owner_visits
456   2020-12-14   Stray              1947                   1947
481   2020-12-15   Stray              1925                   3872
506   2020-12-16   Stray              1859                   5731
94    2020-12-17   Stray              1772                   7503
555   2020-12-18   Stray              1445                   8948
...          ...     ...               ...                    ...
70356 2025-07-23   Stray             29271               86267681
70409 2025-07-24   Stray             26517               86294198
70463 2025-07-25   Stray             14813               86309011
70515 2025-07-26   Stray             16083               86325094
70566 2025-07-27   Stray             15261               86340355

[1687 rows x 4 columns]

stop

In [11]:
folder_path = "wishlists/Annapurna Interactive Historical Revenues - releases_dates.csv"
dates  = pd.read_csv(folder_path)
dates = dates.dropna(subset='pc_release_date')
dates['pc_release_date'] = pd.to_datetime(dates['pc_release_date'])
release_date_dict = dates.groupby('product')['pc_release_date'].min().to_dict()

In [12]:
release_date_dict.get("The Lost Wild")

Timestamp('2026-11-01 00:00:00')

In [13]:
wishlists['release_date'] = pd.to_datetime(wishlists['Day'])


wishlists["non_owner_visits_percent_of_max"] = wishlists["cume_non_owner_visits"] / wishlists.groupby("product")["cume_non_owner_visits"].transform("max")

In [14]:
wishlists['release_date'] = pd.to_datetime(wishlists['Day'])
wishlists['Day'] = pd.to_datetime(wishlists['Day']).dt.to_pydatetime()
wishlists['release_date'] = wishlists.groupby('product')['release_date'].transform('min')
wishlists['release_date'] = wishlists['product'].map(release_date_dict)
wishlists["DAR"] = (wishlists["Day"] - wishlists["release_date"]).dt.days
#df["DAR"] = df.groupby("product")["DAR"].transform(lambda x: x.clip(lower=0))

wishlists["Weeks_from_Release"] = (wishlists["DAR"] // 7) + 1  # Week 1 starts at 0-7 days

df["avg_price"] = df["revenue"] / df["units"]

In [15]:
wishlists

,Day,product,non_owner_visits,cume_non_owner_visits,release_date,non_owner_visits_percent_of_max,DAR,Weeks_from_Release
0,2020-12-14,Ashen,2034,2034,2018-12-07,0.000464,738.0,106.0
461,2020-12-14,Wattam,988,988,2020-12-18,0.000473,-4.0,0.0
460,2020-12-14,Twelve Minutes,633,633,2021-08-19,0.000052,-248.0,-35.0
459,2020-12-14,The Unfinished Swan,1559,1559,2020-09-10,0.000689,95.0,14.0
458,2020-12-14,The Artful Escape,225,225,2021-09-09,0.000101,-269.0,-38.0
...,...,...,...,...,...,...,...,...
70549,2025-07-27,LEGO Voyagers,1888,221249,2025-09-30,1.000000,-65.0,-9.0
70550,2025-07-27,Lorelei and the Laser Eyes,1067,3020187,2024-05-16,1.000000,437.0,63.0
70551,2025-07-27,Lushfoil Photography Sim,2810,2707932,2025-04-15,1.000000,103.0,15.0
70553,2025-07-27,Mixtape,708,460057,2025-12-31,1.000000,-157.0,-22.0
70579,2025-07-27,Wheel World,44440,958597,2025-07-23,1.000000,4.0,1.0

In [16]:
value_cols = ["non_owner_visits",'cume_non_owner_visits','non_owner_visits_percent_of_max']

In [17]:
df = wishlists.groupby(["product", "Weeks_from_Release",'DAR','Day','release_date'], as_index=False)[value_cols].max()

df.query("DAR==0")

In [18]:
df.columns = [col.strip().replace(" ", "_").lower() for col in df.columns]
#df['date'] = pd.to_datetime(df['date'], format="%d %B, %Y")

In [19]:
df['product_day'] = df['product'].astype(str) + '_' + df['day'].astype(str)
#df.set_index('product_day', inplace=True)

In [20]:
df['visits_daily_delta']  = df.groupby('product')['non_owner_visits'].pct_change()

In [21]:
export = df.query("dar <=0")
export = export.drop_duplicates(subset='product', keep='last')

In [22]:
df.query("product =='Stray' & dar ==0")

,product,weeks_from_release,dar,day,release_date,non_owner_visits,cume_non_owner_visits,non_owner_visits_percent_of_max,product_day,visits_daily_delta
45901,Stray,1.0,0.0,2022-07-19,2022-07-19,2769680,18053532,0.209097,Stray_2022-07-19,3.035699

In [23]:
export[['product','weeks_from_release', 'non_owner_visits','cume_non_owner_visits']]

,product,weeks_from_release,non_owner_visits,cume_non_owner_visits
243,A Memoir Blue,1.0,14965,81885
4371,BattleSage,1.0,43,80577
5518,Bounty Star,-10.0,237,369948
6003,Cocoon,1.0,122816,592064
9599,Faraway,-22.0,137,44772
10457,Flock,1.0,34098,600678
16377,Hindsight,1.0,9481,99151
17510,Hohokum,1.0,21421,21445
24026,LEGO Voyagers,-9.0,1888,221249
24247,Last Stop,1.0,27697,137947
26407,Lorelei and the Laser Eyes,1.0,68940,350597
28163,Lushfoil Photography Sim,1.0,142256,1440381
28345,Maquette,1.0,83024,156884
30385,Mixtape,-22.0,708,460057
30665,Morsels,1.0,668,147554
30907,Mundaun,1.0,61673,129043
32990,Neon White,1.0,174226,882999
34528,No Goblin Game 3,-28.0,191,24499
35729,Open Roads,1.0,46985,727283
37968,Outer Wilds - Echoes of the Eye DLC,1.0,197301,405199
42652,Skin Deep,1.0,124525,764199
42874,Solar Ash,1.0,192975,354728
44461,Storyteller,1.0,127224,1590429
45901,Stray,1.0,2769680,18053532
48962,The Artful Escape,1.0,35706,150895
51488,The Lost Wild,-65.0,1492,2243853
51604,The Pathless,1.0,42150,130401
55368,Thirsty Suitors,1.0,43019,593922
56250,Twelve Minutes,1.0,588198,2320407
58007,Wanderstop,1.0,242573,1062720
58150,Wattam,1.0,24123,31260
62360,Wheel World,1.0,69734,682316
63082,to a T,1.0,42724,386557

df

In [24]:
export[['product','weeks_from_release', 'non_owner_visits','cume_non_owner_visits']].to_clipboard()

In [25]:
final_df = df.query("cume_non_owner_visits	>0")

In [26]:
final_df

,product,weeks_from_release,dar,day,release_date,non_owner_visits,cume_non_owner_visits,non_owner_visits_percent_of_max,product_day,visits_daily_delta
2,A Memoir Blue,-35.0,-246.0,2021-07-21,2022-03-24,14,14,0.000017,A Memoir Blue_2021-07-21,inf
3,A Memoir Blue,-34.0,-245.0,2021-07-22,2022-03-24,1,15,0.000018,A Memoir Blue_2021-07-22,-0.928571
4,A Memoir Blue,-34.0,-241.0,2021-07-26,2022-03-24,0,15,0.000018,A Memoir Blue_2021-07-26,-1.000000
5,A Memoir Blue,-33.0,-238.0,2021-07-29,2022-03-24,1924,1939,0.002297,A Memoir Blue_2021-07-29,inf
6,A Memoir Blue,-33.0,-237.0,2021-07-30,2022-03-24,2409,4348,0.005151,A Memoir Blue_2021-07-30,0.252079
...,...,...,...,...,...,...,...,...,...,...
63138,to a T,9.0,56.0,2025-07-23,2025-05-28,1257,666013,0.992523,to a T_2025-07-23,-0.102143
63139,to a T,9.0,57.0,2025-07-24,2025-05-28,1387,667400,0.994590,to a T_2025-07-24,0.103421
63140,to a T,9.0,58.0,2025-07-25,2025-05-28,995,668395,0.996073,to a T_2025-07-25,-0.282624
63141,to a T,9.0,59.0,2025-07-26,2025-05-28,1138,669533,0.997769,to a T_2025-07-26,0.143719
63142,to a T,9.0,60.0,2025-07-27,2025-05-28,1497,671030,1.000000,to a T_2025-07-27,0.315466

In [27]:
# Restructure each row
records = []
for _, row in final_df.iterrows():
    doc = {'_id': row['product_day'],
           'product': row['product'],
           'day': row['day'],
            "non_owner_visits": row["non_owner_visits"],
            "cume_non_owner_visits": row["cume_non_owner_visits"],
            "non_owner_visits_percent_of_max": row["non_owner_visits_percent_of_max"],
            "visits_daily_delta": row["visits_daily_delta"],

    }
    records.append(doc)

records = df.to_dict(orient="records")
records

In [28]:
records

[{'_id': 'A Memoir Blue_2021-07-21',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-07-21 00:00:00'),
  'non_owner_visits': 14,
  'cume_non_owner_visits': 14,
  'non_owner_visits_percent_of_max': 1.658606628265974e-05,
  'visits_daily_delta': inf},
 {'_id': 'A Memoir Blue_2021-07-22',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-07-22 00:00:00'),
  'non_owner_visits': 1,
  'cume_non_owner_visits': 15,
  'non_owner_visits_percent_of_max': 1.7770785302849724e-05,
  'visits_daily_delta': -0.9285714285714286},
 {'_id': 'A Memoir Blue_2021-07-26',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-07-26 00:00:00'),
  'non_owner_visits': 0,
  'cume_non_owner_visits': 15,
  'non_owner_visits_percent_of_max': 1.7770785302849724e-05,
  'visits_daily_delta': -1.0},
 {'_id': 'A Memoir Blue_2021-07-29',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-07-29 00:00:00'),
  'non_owner_visits': 1924,
  'cume_non_owner_visits': 1939,
  'non_owner_visits_percent_of_max': 0.0022971701801483744,
  'visits_daily_delta': inf},
 {'_id': 'A Memoir Blue_2021-07-30',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-07-30 00:00:00'),
  'non_owner_visits': 2409,
  'cume_non_owner_visits': 4348,
  'non_owner_visits_percent_of_max': 0.00515115829978604,
  'visits_daily_delta': 0.252079002079002},
 {'_id': 'A Memoir Blue_2021-07-31',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-07-31 00:00:00'),
  'non_owner_visits': 968,
  'cume_non_owner_visits': 5316,
  'non_owner_visits_percent_of_max': 0.006297966311329942,
  'visits_daily_delta': -0.5981735159817352},
 {'_id': 'A Memoir Blue_2021-08-01',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-01 00:00:00'),
  'non_owner_visits': 574,
  'cume_non_owner_visits': 5890,
  'non_owner_visits_percent_of_max': 0.006977995028918991,
  'visits_daily_delta': -0.4070247933884298},
 {'_id': 'A Memoir Blue_2021-08-02',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-02 00:00:00'),
  'non_owner_visits': 581,
  'cume_non_owner_visits': 6471,
  'non_owner_visits_percent_of_max': 0.0076663167796493705,
  'visits_daily_delta': 0.012195121951219523},
 {'_id': 'A Memoir Blue_2021-08-03',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-03 00:00:00'),
  'non_owner_visits': 388,
  'cume_non_owner_visits': 6859,
  'non_owner_visits_percent_of_max': 0.008125987759483084,
  'visits_daily_delta': -0.3321858864027539},
 {'_id': 'A Memoir Blue_2021-08-04',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-04 00:00:00'),
  'non_owner_visits': 275,
  'cume_non_owner_visits': 7134,
  'non_owner_visits_percent_of_max': 0.008451785490035328,
  'visits_daily_delta': -0.2912371134020618},
 {'_id': 'A Memoir Blue_2021-08-05',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-05 00:00:00'),
  'non_owner_visits': 300,
  'cume_non_owner_visits': 7434,
  'non_owner_visits_percent_of_max': 0.008807201196092324,
  'visits_daily_delta': 0.09090909090909083},
 {'_id': 'A Memoir Blue_2021-08-06',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-06 00:00:00'),
  'non_owner_visits': 236,
  'cume_non_owner_visits': 7670,
  'non_owner_visits_percent_of_max': 0.009086794884857158,
  'visits_daily_delta': -0.21333333333333337},
 {'_id': 'A Memoir Blue_2021-08-07',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-07 00:00:00'),
  'non_owner_visits': 216,
  'cume_non_owner_visits': 7886,
  'non_owner_visits_percent_of_max': 0.009342694193218195,
  'visits_daily_delta': -0.0847457627118644},
 {'_id': 'A Memoir Blue_2021-08-08',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-08 00:00:00'),
  'non_owner_visits': 219,
  'cume_non_owner_visits': 8105,
  'non_owner_visits_percent_of_max': 0.0096021476586398,
  'visits_daily_delta': 0.01388888888888884},
 {'_id': 'A Memoir Blue_2021-08-09',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-09 00:00:00'),
  'non_owner_visits': 236,
  'cume_non_owner_visits': 8341,
  'non_owner_visits_percent_of_max': 0.009881741347404636,
  'visits_daily_delta': 0.07762557077625565},
 {'_id': 'A Memoir Blue_2021-08-10',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-10 00:00:00'),
  'non_owner_visits': 224,
  'cume_non_owner_visits': 8565,
  'non_owner_visits_percent_of_max': 0.010147118407927192,
  'visits_daily_delta': -0.05084745762711862},
 {'_id': 'A Memoir Blue_2021-08-11',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-11 00:00:00'),
  'non_owner_visits': 240,
  'cume_non_owner_visits': 8805,
  'non_owner_visits_percent_of_max': 0.010431450972772788,
  'visits_daily_delta': 0.0714285714285714},
 {'_id': 'A Memoir Blue_2021-08-12',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-12 00:00:00'),
  'non_owner_visits': 172,
  'cume_non_owner_visits': 8977,
  'non_owner_visits_percent_of_max': 0.010635222644245464,
  'visits_daily_delta': -0.2833333333333333},
 {'_id': 'A Memoir Blue_2021-08-13',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-13 00:00:00'),
  'non_owner_visits': 150,
  'cume_non_owner_visits': 9127,
  'non_owner_visits_percent_of_max': 0.010812930497273962,
  'visits_daily_delta': -0.12790697674418605},
 {'_id': 'A Memoir Blue_2021-08-14',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-14 00:00:00'),
  'non_owner_visits': 140,
  'cume_non_owner_visits': 9267,
  'non_owner_visits_percent_of_max': 0.01097879116010056,
  'visits_daily_delta': -0.06666666666666665},
 {'_id': 'A Memoir Blue_2021-08-15',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-15 00:00:00'),
  'non_owner_visits': 127,
  'cume_non_owner_visits': 9394,
  'non_owner_visits_percent_of_max': 0.011129250475664687,
  'visits_daily_delta': -0.09285714285714286},
 {'_id': 'A Memoir Blue_2021-08-16',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-16 00:00:00'),
  'non_owner_visits': 155,
  'cume_non_owner_visits': 9549,
  'non_owner_visits_percent_of_max': 0.011312881923794134,
  'visits_daily_delta': 0.22047244094488194},
 {'_id': 'A Memoir Blue_2021-08-17',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-17 00:00:00'),
  'non_owner_visits': 165,
  'cume_non_owner_visits': 9714,
  'non_owner_visits_percent_of_max': 0.01150836056212548,
  'visits_daily_delta': 0.06451612903225801},
 {'_id': 'A Memoir Blue_2021-08-18',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-18 00:00:00'),
  'non_owner_visits': 145,
  'cume_non_owner_visits': 9859,
  'non_owner_visits_percent_of_max': 0.011680144820053027,
  'visits_daily_delta': -0.12121212121212122},
 {'_id': 'A Memoir Blue_2021-08-19',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-19 00:00:00'),
  'non_owner_visits': 185,
  'cume_non_owner_visits': 10044,
  'non_owner_visits_percent_of_max': 0.011899317838788174,
  'visits_daily_delta': 0.27586206896551735},
 {'_id': 'A Memoir Blue_2021-08-20',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-20 00:00:00'),
  'non_owner_visits': 174,
  'cume_non_owner_visits': 10218,
  'non_owner_visits_percent_of_max': 0.012105458948301232,
  'visits_daily_delta': -0.05945945945945941},
 {'_id': 'A Memoir Blue_2021-08-21',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-21 00:00:00'),
  'non_owner_visits': 156,
  'cume_non_owner_visits': 10374,
  'non_owner_visits_percent_of_max': 0.01229027511545087,
  'visits_daily_delta': -0.10344827586206895},
 {'_id': 'A Memoir Blue_2021-08-22',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-22 00:00:00'),
  'non_owner_visits': 156,
  'cume_non_owner_visits': 10530,
  'non_owner_visits_percent_of_max': 0.012475091282600506,
  'visits_daily_delta': 0.0},
 {'_id': 'A Memoir Blue_2021-08-23',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-23 00:00:00'),
  'non_owner_visits': 173,
  'cume_non_owner_visits': 10703,
  'non_owner_visits_percent_of_max': 0.012680047673093373,
  'visits_daily_delta': 0.10897435897435903},
 {'_id': 'A Memoir Blue_2021-08-24',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-24 00:00:00'),
  'non_owner_visits': 187,
  'cume_non_owner_visits': 10890,
  'non_owner_visits_percent_of_max': 0.0129015901298689,
  'visits_daily_delta': 0.08092485549132955},
 {'_id': 'A Memoir Blue_2021-08-25',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-25 00:00:00'),
  'non_owner_visits': 129,
  'cume_non_owner_visits': 11019,
  'non_owner_visits_percent_of_max': 0.013054418883473407,
  'visits_daily_delta': -0.31016042780748665},
 {'_id': 'A Memoir Blue_2021-08-26',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-26 00:00:00'),
  'non_owner_visits': 179,
  'cume_non_owner_visits': 11198,
  'non_owner_visits_percent_of_max': 0.013266483588087413,
  'visits_daily_delta': 0.3875968992248062},
 {'_id': 'A Memoir Blue_2021-08-27',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-27 00:00:00'),
  'non_owner_visits': 174,
  'cume_non_owner_visits': 11372,
  'non_owner_visits_percent_of_max': 0.01347262469760047,
  'visits_daily_delta': -0.027932960893854775},
 {'_id': 'A Memoir Blue_2021-08-28',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-28 00:00:00'),
  'non_owner_visits': 140,
  'cume_non_owner_visits': 11512,
  'non_owner_visits_percent_of_max': 0.013638485360427067,
  'visits_daily_delta': -0.1954022988505747},
 {'_id': 'A Memoir Blue_2021-08-29',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-29 00:00:00'),
  'non_owner_visits': 145,
  'cume_non_owner_visits': 11657,
  'non_owner_visits_percent_of_max': 0.013810269618354614,
  'visits_daily_delta': 0.03571428571428581},
 {'_id': 'A Memoir Blue_2021-08-30',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-30 00:00:00'),
  'non_owner_visits': 124,
  'cume_non_owner_visits': 11781,
  'non_owner_visits_percent_of_max': 0.013957174776858173,
  'visits_daily_delta': -0.1448275862068965},
 {'_id': 'A Memoir Blue_2021-08-31',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-08-31 00:00:00'),
  'non_owner_visits': 137,
  'cume_non_owner_visits': 11918,
  'non_owner_visits_percent_of_max': 0.0141194812826242,
  'visits_daily_delta': 0.10483870967741926},
 {'_id': 'A Memoir Blue_2021-09-01',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-01 00:00:00'),
  'non_owner_visits': 146,
  'cume_non_owner_visits': 12064,
  'non_owner_visits_percent_of_max': 0.014292450259571937,
  'visits_daily_delta': 0.06569343065693434},
 {'_id': 'A Memoir Blue_2021-09-02',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-02 00:00:00'),
  'non_owner_visits': 144,
  'cume_non_owner_visits': 12208,
  'non_owner_visits_percent_of_max': 0.014463049798479295,
  'visits_daily_delta': -0.013698630136986356},
 {'_id': 'A Memoir Blue_2021-09-03',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-03 00:00:00'),
  'non_owner_visits': 138,
  'cume_non_owner_visits': 12346,
  'non_owner_visits_percent_of_max': 0.014626541023265513,
  'visits_daily_delta': -0.04166666666666663},
 {'_id': 'A Memoir Blue_2021-09-04',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-04 00:00:00'),
  'non_owner_visits': 140,
  'cume_non_owner_visits': 12486,
  'non_owner_visits_percent_of_max': 0.01479240168609211,
  'visits_daily_delta': 0.01449275362318847},
 {'_id': 'A Memoir Blue_2021-09-05',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-05 00:00:00'),
  'non_owner_visits': 127,
  'cume_non_owner_visits': 12613,
  'non_owner_visits_percent_of_max': 0.014942861001656238,
  'visits_daily_delta': -0.09285714285714286},
 {'_id': 'A Memoir Blue_2021-09-06',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-06 00:00:00'),
  'non_owner_visits': 124,
  'cume_non_owner_visits': 12737,
  'non_owner_visits_percent_of_max': 0.015089766160159794,
  'visits_daily_delta': -0.023622047244094446},
 {'_id': 'A Memoir Blue_2021-09-07',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-07 00:00:00'),
  'non_owner_visits': 128,
  'cume_non_owner_visits': 12865,
  'non_owner_visits_percent_of_max': 0.015241410194744112,
  'visits_daily_delta': 0.032258064516129004},
 {'_id': 'A Memoir Blue_2021-09-08',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-08 00:00:00'),
  'non_owner_visits': 135,
  'cume_non_owner_visits': 13000,
  'non_owner_visits_percent_of_max': 0.01540134726246976,
  'visits_daily_delta': 0.0546875},
 {'_id': 'A Memoir Blue_2021-09-09',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-09 00:00:00'),
  'non_owner_visits': 160,
  'cume_non_owner_visits': 13160,
  'non_owner_visits_percent_of_max': 0.015590902305700156,
  'visits_daily_delta': 0.18518518518518512},
 {'_id': 'A Memoir Blue_2021-09-10',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-10 00:00:00'),
  'non_owner_visits': 189,
  'cume_non_owner_visits': 13349,
  'non_owner_visits_percent_of_max': 0.015814814200516062,
  'visits_daily_delta': 0.1812499999999999},
 {'_id': 'A Memoir Blue_2021-09-11',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-11 00:00:00'),
  'non_owner_visits': 167,
  'cume_non_owner_visits': 13516,
  'non_owner_visits_percent_of_max': 0.01601266227688779,
  'visits_daily_delta': -0.1164021164021164},
 {'_id': 'A Memoir Blue_2021-09-12',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-12 00:00:00'),
  'non_owner_visits': 183,
  'cume_non_owner_visits': 13699,
  'non_owner_visits_percent_of_max': 0.016229465857582556,
  'visits_daily_delta': 0.09580838323353302},
 {'_id': 'A Memoir Blue_2021-09-13',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-13 00:00:00'),
  'non_owner_visits': 178,
  'cume_non_owner_visits': 13877,
  'non_owner_visits_percent_of_max': 0.016440345843176375,
  'visits_daily_delta': -0.02732240437158473},
 {'_id': 'A Memoir Blue_2021-09-14',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-14 00:00:00'),
  'non_owner_visits': 158,
  'cume_non_owner_visits': 14035,
  'non_owner_visits_percent_of_max': 0.01662753144836639,
  'visits_daily_delta': -0.1123595505617978},
 {'_id': 'A Memoir Blue_2021-09-15',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-15 00:00:00'),
  'non_owner_visits': 156,
  'cume_non_owner_visits': 14191,
  'non_owner_visits_percent_of_max': 0.01681234761551603,
  'visits_daily_delta': -0.012658227848101222},
 {'_id': 'A Memoir Blue_2021-09-16',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-16 00:00:00'),
  'non_owner_visits': 158,
  'cume_non_owner_visits': 14349,
  'non_owner_visits_percent_of_max': 0.016999533220706044,
  'visits_daily_delta': 0.012820512820512775},
 {'_id': 'A Memoir Blue_2021-09-17',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-17 00:00:00'),
  'non_owner_visits': 130,
  'cume_non_owner_visits': 14479,
  'non_owner_visits_percent_of_max': 0.017153546693330742,
  'visits_daily_delta': -0.17721518987341767},
 {'_id': 'A Memoir Blue_2021-09-18',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-18 00:00:00'),
  'non_owner_visits': 146,
  'cume_non_owner_visits': 14625,
  'non_owner_visits_percent_of_max': 0.01732651567027848,
  'visits_daily_delta': 0.12307692307692308},
 {'_id': 'A Memoir Blue_2021-09-19',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-19 00:00:00'),
  'non_owner_visits': 123,
  'cume_non_owner_visits': 14748,
  'non_owner_visits_percent_of_max': 0.017472236109761848,
  'visits_daily_delta': -0.15753424657534243},
 {'_id': 'A Memoir Blue_2021-09-20',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-20 00:00:00'),
  'non_owner_visits': 125,
  'cume_non_owner_visits': 14873,
  'non_owner_visits_percent_of_max': 0.017620325987285596,
  'visits_daily_delta': 0.016260162601626105},
 {'_id': 'A Memoir Blue_2021-09-21',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-21 00:00:00'),
  'non_owner_visits': 127,
  'cume_non_owner_visits': 15000,
  'non_owner_visits_percent_of_max': 0.017770785302849722,
  'visits_daily_delta': 0.016000000000000014},
 {'_id': 'A Memoir Blue_2021-09-22',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-22 00:00:00'),
  'non_owner_visits': 142,
  'cume_non_owner_visits': 15142,
  'non_owner_visits_percent_of_max': 0.0179390154037167,
  'visits_daily_delta': 0.11811023622047245},
 {'_id': 'A Memoir Blue_2021-09-23',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-23 00:00:00'),
  'non_owner_visits': 122,
  'cume_non_owner_visits': 15264,
  'non_owner_visits_percent_of_max': 0.018083551124179878,
  'visits_daily_delta': -0.14084507042253525},
 {'_id': 'A Memoir Blue_2021-09-24',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-24 00:00:00'),
  'non_owner_visits': 115,
  'cume_non_owner_visits': 15379,
  'non_owner_visits_percent_of_max': 0.018219793811501725,
  'visits_daily_delta': -0.05737704918032782},
 {'_id': 'A Memoir Blue_2021-09-25',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-25 00:00:00'),
  'non_owner_visits': 149,
  'cume_non_owner_visits': 15528,
  'non_owner_visits_percent_of_max': 0.018396316945510034,
  'visits_daily_delta': 0.29565217391304355},
 {'_id': 'A Memoir Blue_2021-09-26',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-26 00:00:00'),
  'non_owner_visits': 103,
  'cume_non_owner_visits': 15631,
  'non_owner_visits_percent_of_max': 0.018518343004589603,
  'visits_daily_delta': -0.3087248322147651},
 {'_id': 'A Memoir Blue_2021-09-27',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-27 00:00:00'),
  'non_owner_visits': 142,
  'cume_non_owner_visits': 15773,
  'non_owner_visits_percent_of_max': 0.01868657310545658,
  'visits_daily_delta': 0.3786407766990292},
 {'_id': 'A Memoir Blue_2021-09-28',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-28 00:00:00'),
  'non_owner_visits': 172,
  'cume_non_owner_visits': 15945,
  'non_owner_visits_percent_of_max': 0.018890344776929257,
  'visits_daily_delta': 0.21126760563380276},
 {'_id': 'A Memoir Blue_2021-09-29',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-29 00:00:00'),
  'non_owner_visits': 156,
  'cume_non_owner_visits': 16101,
  'non_owner_visits_percent_of_max': 0.019075160944078892,
  'visits_daily_delta': -0.09302325581395354},
 {'_id': 'A Memoir Blue_2021-09-30',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-09-30 00:00:00'),
  'non_owner_visits': 239,
  'cume_non_owner_visits': 16340,
  'non_owner_visits_percent_of_max': 0.0193583087899043,
  'visits_daily_delta': 0.5320512820512822},
 {'_id': 'A Memoir Blue_2021-10-01',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-01 00:00:00'),
  'non_owner_visits': 198,
  'cume_non_owner_visits': 16538,
  'non_owner_visits_percent_of_max': 0.019592883155901915,
  'visits_daily_delta': -0.17154811715481166},
 {'_id': 'A Memoir Blue_2021-10-02',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-02 00:00:00'),
  'non_owner_visits': 119,
  'cume_non_owner_visits': 16657,
  'non_owner_visits_percent_of_max': 0.019733864719304522,
  'visits_daily_delta': -0.398989898989899},
 {'_id': 'A Memoir Blue_2021-10-03',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-03 00:00:00'),
  'non_owner_visits': 157,
  'cume_non_owner_visits': 16814,
  'non_owner_visits_percent_of_max': 0.01991986560547435,
  'visits_daily_delta': 0.31932773109243695},
 {'_id': 'A Memoir Blue_2021-10-04',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-04 00:00:00'),
  'non_owner_visits': 152,
  'cume_non_owner_visits': 16966,
  'non_owner_visits_percent_of_max': 0.020099942896543228,
  'visits_daily_delta': -0.031847133757961776},
 {'_id': 'A Memoir Blue_2021-10-05',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-05 00:00:00'),
  'non_owner_visits': 170,
  'cume_non_owner_visits': 17136,
  'non_owner_visits_percent_of_max': 0.020301345129975525,
  'visits_daily_delta': 0.11842105263157898},
 {'_id': 'A Memoir Blue_2021-10-06',
  'product': 'A Memoir Blue',
  'day': Timestamp('2021-10-06 00:00:00'),
  'non_owner_visits': 215,
  'cume_non_owner_visits': 17351,

requests

In [29]:
stop

NameError: name 'stop' is not defined

folder_path = "units/cume_revenues.xlsx"


revs  = pd.read_excel(folder_path, skiprows=2)

In [30]:
from pymongo import UpdateOne

## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [31]:
from datetime import datetime
date_string = datetime.today().strftime('%Y-%m-%d')

In [32]:
db = client['ai_sales_data']
collection = db['units']

unique_products = collection.distinct("product", {"date": {"$gte": 2025-01-01}})

unique_products

In [33]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]




collection.update_many(
    {},
    {
        "$unset": {
            "wishlist_adds": "",
            "cume_wishlists": "",
            "wishlists_percent_of_max": "",
            "wl_daily_delta": ""
        }
    }
)

In [34]:
#####
for batch in batchify(records, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 4000, Inserted: 0, Modified: 0
Matched: 2084, Inserted: 0, Modified: 0

collection.update_many({}, {"$unset": {"percent_of_max": ""}})

In [35]:
client.close()