In [1]:
## Download from IndieBI, details by product, All Games No Soundtrack, daily units

#TEST Data is using EXPORT function and seems to be working.

import pandas as pd
import glob
import os

# Define folder path
folder_path = "DB_Update/units/"

# Get all Excel files in the folder
excel_files = glob.glob(os.path.join(folder_path, "*.xlsx"))

# Read and combine all files, skipping first 2 rows
df_list = [pd.read_excel(f, skiprows=2).assign(filename=os.path.basename(f)) for f in excel_files]
combined_df = pd.concat(df_list, ignore_index=True)

combined_df

df = combined_df.drop_duplicates(subset=['Day', 'product'])
df

import pandas as pd
import glob
import os

# Define folder path
folder_path = "DB_Update/revs/"

# Get all Excel files in the folder
excel_files = glob.glob(os.path.join(folder_path, "*.xlsx"))

# Read and combine all files, skipping first 2 rows
df_list = [pd.read_excel(f, skiprows=2).assign(filename=os.path.basename(f)) for f in excel_files]
combined_df_revs = pd.concat(df_list, ignore_index=True)

revs = combined_df_revs.drop_duplicates(subset=['Day', 'product'])
revs

import pandas as pd
import glob
import os

# Define folder path
folder_path = "DB_Update/wishlists/"

# Get all Excel files in the folder
excel_files = glob.glob(os.path.join(folder_path, "*.xlsx"))

# Read and combine all files, skipping first 2 rows
df_list = [pd.read_excel(f, skiprows=2).assign(filename=os.path.basename(f)) for f in excel_files]
combined_df_wl = pd.concat(df_list, ignore_index=True)

wishlists = combined_df_wl.drop_duplicates(subset=['Day', 'product'])
wishlists

df = df.rename({"Selected Measure":"units"}, axis=1)
revs = revs.rename({"Selected Measure":"revenue"}, axis=1)
#wishlists = wishlists.rename({"Selected Measure":"wishlist_adds"}, axis=1)

df = df.drop("Blank Measure", axis=1)
revs = revs.drop("Blank Measure", axis=1)
#wishlists = wishlists.drop("Blank Measure", axis=1)

df = df.drop("filename", axis=1)
revs = revs.drop("filename", axis=1)
#wishlists = wishlists.drop("filename", axis=1)

df

revs

df['cume_units'] = df.groupby('product')['units'].cumsum()
revs['cume_revs'] = revs.groupby('product')['revenue'].cumsum()
#wishlists['cume_wishlists'] = wishlists.groupby('product')['wishlist_adds'].cumsum()

df = df.merge(revs,on=['product', 'Day'], how='left')
#df = df.merge(wishlists,on=['product', 'Day'], how='left')

## Export Test

for f in excel_files:
    try:
        df = pd.read_excel(f, skipfooter=2, engine='openpyxl')
        print(f"✔ Loaded: {f}")
    except Exception as e:
        print(f"❌ Failed to load: {f} — {e}")

In [3]:
import pandas as pd
import glob
import os

# Define folder path
folder_path = "DB_Update/test"

# Get all Excel files in the folder
excel_files = glob.glob(os.path.join(folder_path, "*.xlsx"))

# Read and combine all files, skipping first 2 rows
df_list = [pd.read_excel(f, skipfooter=2).assign(filename=os.path.basename(f)) for f in excel_files]
combined_test = pd.concat(df_list, ignore_index=True)

In [4]:
import pandas as pd
import glob
import os
import warnings

warnings.filterwarnings("ignore")

In [5]:
combined_test_test = pd.read_csv("DB_Update/API/bulkAPI_Export.csv")

In [6]:
product_name = "LEGO Voyagers - Friend’s Pass"
combined_test_test.query("Date == '2025-09-29' & Product == @product_name")

,Date,Product,Revenue (excl. refunds),Units (excl. refunds),units_excl_refunds_incl_free,Free units,Wishlist adds,Non-owner visits,Non-owner impressions,Refunded units,wl_deletes,wl_activations
89400,2025-09-29,LEGO Voyagers - Friend’s Pass,0.0,0,269,269,2.0,3.0,25.0,0,1.0,1.0

combined_test

In [7]:
rename_dict = {
'Date':'Day', 
    'Product':'product', 
    'Revenue (excl. refunds)':'revenue', 
    'Units (excl. refunds)':'units',
       'Free units':'free_units', 
    'Wishlist adds':'wishlist_adds', 
    'Non-owner visits':'visits',
       'Non-owner impressions':'impressions', 
    'Refunded units': 'refunded_units'
    
}

In [8]:
combined_test_test.rename(rename_dict, axis=1, inplace=True)

combined_test_test

In [9]:
test = combined_test_test.drop_duplicates(subset=['Day', 'product'])

In [10]:
test['Day'] = pd.to_datetime(test['Day'] )

In [11]:
test = test.sort_values(by='Day')

In [12]:
test.query("Day=='2025-09-22' & product ==@product_name")

,Day,product,revenue,units,units_excl_refunds_incl_free,free_units,wishlist_adds,visits,impressions,refunded_units,wl_deletes,wl_activations
89018,2025-09-22,LEGO Voyagers - Friend’s Pass,0.0,0,2715,2715,3.0,47.0,544.0,0,0.0,0.0

In [13]:
test['cume_units'] = test.groupby('product')['units'].cumsum()
test['cume_revs'] = test.groupby('product')['revenue'].cumsum()

test['cume_free_units'] = test.groupby('product')['free_units'].cumsum()
test['cume_wishlist_adds'] = test.groupby('product')['wishlist_adds'].cumsum()
test['cume_visits'] = test.groupby('product')['visits'].cumsum()
test['cume_impressions'] = test.groupby('product')['impressions'].cumsum()
test['cume_refunded_units'] = test.groupby('product')['refunded_units'].cumsum()
test['cume_wishlist_deletes'] = test.groupby('product')['wl_deletes'].cumsum()
test['cume_wishlist_activations'] = test.groupby('product')['wl_activations'].cumsum()
test['cume_combined_units'] = test.groupby('product')['units_excl_refunds_incl_free'].cumsum()

In [14]:
cols_ = ['Day',
         'product',
         'units',
         'cume_units',
         'revenue',
         'cume_revs',
         'free_units',
         'cume_free_units',
         'units_excl_refunds_incl_free',
         'cume_combined_units',
         'wishlist_adds',
         'cume_wishlist_adds',
         'wl_deletes',
         'cume_wishlist_deletes',
         'wl_activations',
         'cume_wishlist_activations',
        # 'activation_rate',
       #  'cume_activation_rate',
         'visits',
         'cume_visits',
         'impressions',
         'cume_impressions',
         'refunded_units',
         'cume_refunded_units']

In [15]:
df = test[cols_]

In [70]:
test[cols_].query("product=='LEGO Voyagers' & Day =='2025-09-29'")['cume_wishlist_adds']

89427    275786.0
Name: cume_wishlist_adds, dtype: float64

In [17]:
df['product'].unique()

array(['What Remains of Edith Finch',
       'What Remains of Edith Finch - Original Soundtrack', 'Gorogoa',
       'Telling Lies', 'Gorogoa - Original Soundtrack', 'Ashen',
       'Florence', 'Maquette', 'Outer Wilds', 'Journey', 'Donut County',
       'No Goblin Game 3', 'Donut County - Original Soundtrack',
       'Gone Home', 'Mundaun', 'Wattam', 'I Am Dead', 'Flower',
       'If Found...', 'Telling Lies - Original Soundtrack',
       'Ashen - Nightstorm Isle DLC', 'Sayonara Wild Hearts',
       'Ashen - Original Soundtrack',
       'Sayonara Wild Hearts - Original Soundtrack',
       'Kentucky Route Zero: TV Edition',
       'Florence - Original Soundtrack', 'Last Stop',
       'The Unfinished Swan', 'Hindsight',
       'If Found... - Original Soundtrack', 'Twelve Minutes',
       'Outer Wilds - Original Soundtrack', 'Due Process',
       'The Artful Escape', 'I Am Dead - Original Soundtrack',
       'The Pathless', 'Flock', 'Due Process - Original Soundtrack',
       'Wattam - Original Soundtrack', 'LEGO Voyagers', 'Neon White',
       'Wheel World', 'Outer Wilds - Echoes of the Eye DLC', 'Stray',
       'Storyteller', 'Thirsty Suitors',
       'Last Stop - Original Soundtrack', 'A Memoir Blue',
       'Twelve Minutes - Original Soundtrack', 'Demi',
       'The Artful Escape - Original Soundtrack',
       'Outer Wilds - Archaeologist Edition BUNDLE', 'Heron',
       'Open Roads', 'First Ascent', 'The Pathless - Original Soundtrack',
       'Solar Ash', 'Bounty Star', 'Forever Ago', 'Hohokum', 'Wanderstop',
       'A Memoir Blue - Original Soundtrack', 'Ashen Definitive Edition',
       'Morsels', 'Big Hops', 'Skin Deep',
       'Neon White - Original Soundtrack', 'Cocoon',
       'Stray - Original Soundtrack', 'People of Note',
       'Hindsight - Original Soundtrack', 'We Kill Monsters',
       'Lushfoil Photography Sim', 'Solar Ash - Original Soundtrack',
       'Blade Runner 2033: Labyrinth',
       'Storyteller - Original Soundtrack', 'to a T', 'The Lost Wild',
       'Lorelei and the Laser Eyes', 'D-topia',
       'Thirsty Suitors - Original Soundtrack', 'Cocoon - Soundtrack',
       'REV', 'Lorelei and the Laser Eyes - Original Soundtrack',
       'A Person A Problem', 'Flock - Original Soundtrack', 'Faraway',
       'Project Insomnia', 'Mixtape', 'Big Maze',
       'Wanderstop - Soundtrack', 'Skin Deep Soundtrack',
       'Skin Deep - Soundtrack Edition', 'BattleSage', 'Saru',
       'Wheel World - Soundtrack', 'to a T - Soundtrack',
       'Wheel World + Soundtrack Bundle', 'LEGO Voyagers - Friend’s Pass',
       'LEGO Voyagers - Soundtrack', 'LEGO Voyagers - Soundtrack Bundle'],
      dtype=object)

stop

In [18]:
folder_path = "wishlists/Annapurna Interactive Historical Revenues - releases_dates.csv"
dates  = pd.read_csv(folder_path)
dates = dates.dropna(subset='pc_release_date')
dates['pc_release_date'] = pd.to_datetime(dates['pc_release_date'])
release_date_dict = dates.groupby('product')['pc_release_date'].min().to_dict()

In [19]:
release_date_dict.get('LEGO Voyagers - Friend’s Pass')

Timestamp('2025-09-15 00:00:00')

In [20]:
release_date_dict.get('Morsels')

Timestamp('2025-11-18 00:00:00')

In [21]:
df['release_date'] = pd.to_datetime(df['Day'])


df["units_percent_of_max"] = df["cume_units"] / df.groupby("product")["cume_units"].transform("max")
df["revs_percent_of_max"] = df["cume_revs"] / df.groupby("product")["cume_revs"].transform("max")

In [22]:
df['release_date'] = pd.to_datetime(df['Day'])
df['Day'] = pd.to_datetime(df['Day']).dt.to_pydatetime()
df['release_date'] = df.groupby('product')['release_date'].transform('min')
df['release_date'] = df['product'].map(release_date_dict)
df["DAR"] = (df["Day"] - df["release_date"]).dt.days
#df["DAR"] = df.groupby("product")["DAR"].transform(lambda x: x.clip(lower=0))

df["Weeks_from_Release"] = (df["DAR"] // 7) + 1  # Week 1 starts at 0-7 days

In [23]:
df["avg_price"] = df["revenue"] / df["units"]


df['activation_rate'] =df['wl_activations'] / df['wishlist_adds']
df['cume_activation_rate'] =df['cume_wishlist_activations'] / df['cume_wishlist_adds']

In [24]:
value_cols = [

'units',
         'cume_units',
'units_percent_of_max',
         'revenue',
         'cume_revs',
'revs_percent_of_max',
'avg_price',
         'free_units',
         'cume_free_units',
             'units_excl_refunds_incl_free',
         'cume_combined_units',
         'wishlist_adds',
         'cume_wishlist_adds',
             'wl_deletes',
         'cume_wishlist_deletes',
         'wl_activations',
         'cume_wishlist_activations',
         'activation_rate',
         'cume_activation_rate',
         'visits',
         'cume_visits',
         'impressions',
         'cume_impressions',
         'refunded_units',
         'cume_refunded_units'

]

In [25]:
df = df.groupby(["product", "Weeks_from_Release",'DAR','Day','release_date'], as_index=False)[value_cols].max()

In [26]:
df.columns = [col.strip().replace(" ", "_").lower() for col in df.columns]
#df['date'] = pd.to_datetime(df['date'], format="%d %B, %Y")

In [27]:
df['product_day'] = df['product'].astype(str) + '_' + df['day'].astype(str)
#df.set_index('product_day', inplace=True)

In [28]:
df['unit_daily_delta']  = df.groupby('product')['units'].pct_change()
df['rev_daily_delta']  = df.groupby('product')['revenue'].pct_change()

df.query("product =='Stray'")

In [29]:
records = df.to_dict(orient="records")
records

[{'product': 'A Memoir Blue',
  'weeks_from_release': -31.0,
  'dar': -224.0,
  'day': Timestamp('2021-08-12 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 0,
  'cume_units': 0,
  'units_percent_of_max': 0.0,
  'revenue': 0.0,
  'cume_revs': 0.0,
  'revs_percent_of_max': 0.0,
  'avg_price': nan,
  'free_units': 0,
  'cume_free_units': 0,
  'units_excl_refunds_incl_free': 1,
  'cume_combined_units': 1,
  'wishlist_adds': 33.0,
  'cume_wishlist_adds': 33.0,
  'wl_deletes': 3.0,
  'cume_wishlist_deletes': 3.0,
  'wl_activations': 0.0,
  'cume_wishlist_activations': 0.0,
  'activation_rate': 0.0,
  'cume_activation_rate': 0.0,
  'visits': 172.0,
  'cume_visits': 172.0,
  'impressions': 3593.0,
  'cume_impressions': 3593.0,
  'refunded_units': 0,
  'cume_refunded_units': 0,
  'product_day': 'A Memoir Blue_2021-08-12',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -31.0,
  'dar': -223.0,
  'day': Timestamp('2021-08-13 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 0,
  'cume_units': 0,
  'units_percent_of_max': 0.0,
  'revenue': 0.0,
  'cume_revs': 0.0,
  'revs_percent_of_max': 0.0,
  'avg_price': nan,
  'free_units': 0,
  'cume_free_units': 0,
  'units_excl_refunds_incl_free': 1,
  'cume_combined_units': 2,
  'wishlist_adds': 26.0,
  'cume_wishlist_adds': 59.0,
  'wl_deletes': 2.0,
  'cume_wishlist_deletes': 5.0,
  'wl_activations': 0.0,
  'cume_wishlist_activations': 0.0,
  'activation_rate': 0.0,
  'cume_activation_rate': 0.0,
  'visits': 150.0,
  'cume_visits': 322.0,
  'impressions': 5220.0,
  'cume_impressions': 8813.0,
  'refunded_units': 0,
  'cume_refunded_units': 0,
  'product_day': 'A Memoir Blue_2021-08-13',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -31.0,
  'dar': -219.0,
  'day': Timestamp('2021-08-17 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 0,
  'cume_units': 0,
  'units_percent_of_max': 0.0,
  'revenue': 0.0,
  'cume_revs': 0.0,
  'revs_percent_of_max': 0.0,
  'avg_price': nan,
  'free_units': 0,
  'cume_free_units': 0,
  'units_excl_refunds_incl_free': 1,
  'cume_combined_units': 3,
  'wishlist_adds': 28.0,
  'cume_wishlist_adds': 87.0,
  'wl_deletes': 0.0,
  'cume_wishlist_deletes': 5.0,
  'wl_activations': 0.0,
  'cume_wishlist_activations': 0.0,
  'activation_rate': 0.0,
  'cume_activation_rate': 0.0,
  'visits': 165.0,
  'cume_visits': 487.0,
  'impressions': 3433.0,
  'cume_impressions': 12246.0,
  'refunded_units': 0,
  'cume_refunded_units': 0,
  'product_day': 'A Memoir Blue_2021-08-17',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -31.0,
  'dar': -218.0,
  'day': Timestamp('2021-08-18 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 0,
  'cume_units': 0,
  'units_percent_of_max': 0.0,
  'revenue': 0.0,
  'cume_revs': 0.0,
  'revs_percent_of_max': 0.0,
  'avg_price': nan,
  'free_units': 0,
  'cume_free_units': 0,
  'units_excl_refunds_incl_free': 2,
  'cume_combined_units': 5,
  'wishlist_adds': 29.0,
  'cume_wishlist_adds': 116.0,
  'wl_deletes': 1.0,
  'cume_wishlist_deletes': 6.0,
  'wl_activations': 0.0,
  'cume_wishlist_activations': 0.0,
  'activation_rate': 0.0,
  'cume_activation_rate': 0.0,
  'visits': 145.0,
  'cume_visits': 632.0,
  'impressions': 4042.0,
  'cume_impressions': 16288.0,
  'refunded_units': 0,
  'cume_refunded_units': 0,
  'product_day': 'A Memoir Blue_2021-08-18',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -30.0,
  'dar': -213.0,
  'day': Timestamp('2021-08-23 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 0,
  'cume_units': 0,
  'units_percent_of_max': 0.0,
  'revenue': 0.0,
  'cume_revs': 0.0,
  'revs_percent_of_max': 0.0,
  'avg_price': nan,
  'free_units': 0,
  'cume_free_units': 0,
  'units_excl_refunds_incl_free': 1,
  'cume_combined_units': 6,
  'wishlist_adds': 40.0,
  'cume_wishlist_adds': 156.0,
  'wl_deletes': 1.0,
  'cume_wishlist_deletes': 7.0,
  'wl_activations': 0.0,
  'cume_wishlist_activations': 0.0,
  'activation_rate': 0.0,
  'cume_activation_rate': 0.0,
  'visits': 173.0,
  'cume_visits': 805.0,
  'impressions': 6071.0,
  'cume_impressions': 22359.0,
  'refunded_units': 0,
  'cume_refunded_units': 0,
  'product_day': 'A Memoir Blue_2021-08-23',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -29.0,
  'dar': -209.0,
  'day': Timestamp('2021-08-27 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 0,
  'cume_units': 0,
  'units_percent_of_max': 0.0,
  'revenue': 0.0,
  'cume_revs': 0.0,
  'revs_percent_of_max': 0.0,
  'avg_price': nan,
  'free_units': 0,
  'cume_free_units': 0,
  'units_excl_refunds_incl_free': 1,
  'cume_combined_units': 7,
  'wishlist_adds': 26.0,
  'cume_wishlist_adds': 182.0,
  'wl_deletes': 2.0,
  'cume_wishlist_deletes': 9.0,
  'wl_activations': 0.0,
  'cume_wishlist_activations': 0.0,
  'activation_rate': 0.0,
  'cume_activation_rate': 0.0,
  'visits': 174.0,
  'cume_visits': 979.0,
  'impressions': 3455.0,
  'cume_impressions': 25814.0,
  'refunded_units': 0,
  'cume_refunded_units': 0,
  'product_day': 'A Memoir Blue_2021-08-27',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -29.0,
  'dar': -205.0,
  'day': Timestamp('2021-08-31 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 0,
  'cume_units': 0,
  'units_percent_of_max': 0.0,
  'revenue': 0.0,
  'cume_revs': 0.0,
  'revs_percent_of_max': 0.0,
  'avg_price': nan,
  'free_units': 0,
  'cume_free_units': 0,
  'units_excl_refunds_incl_free': 1,
  'cume_combined_units': 8,
  'wishlist_adds': 17.0,
  'cume_wishlist_adds': 199.0,
  'wl_deletes': 0.0,
  'cume_wishlist_deletes': 9.0,
  'wl_activations': 0.0,
  'cume_wishlist_activations': 0.0,
  'activation_rate': 0.0,
  'cume_activation_rate': 0.0,
  'visits': 137.0,
  'cume_visits': 1116.0,
  'impressions': 2919.0,
  'cume_impressions': 28733.0,
  'refunded_units': 0,
  'cume_refunded_units': 0,
  'product_day': 'A Memoir Blue_2021-08-31',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -29.0,
  'dar': -204.0,
  'day': Timestamp('2021-09-01 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 0,
  'cume_units': 0,
  'units_percent_of_max': 0.0,
  'revenue': 0.0,
  'cume_revs': 0.0,
  'revs_percent_of_max': 0.0,
  'avg_price': nan,
  'free_units': 0,
  'cume_free_units': 0,
  'units_excl_refunds_incl_free': 3,
  'cume_combined_units': 11,
  'wishlist_adds': 14.0,
  'cume_wishlist_adds': 213.0,
  'wl_deletes': 2.0,
  'cume_wishlist_deletes': 11.0,
  'wl_activations': 0.0,
  'cume_wishlist_activations': 0.0,
  'activation_rate': 0.0,
  'cume_activation_rate': 0.0,
  'visits': 146.0,
  'cume_visits': 1262.0,
  'impressions': 2416.0,
  'cume_impressions': 31149.0,
  'refunded_units': 0,
  'cume_refunded_units': 0,
  'product_day': 'A Memoir Blue_2021-09-01',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -27.0,
  'dar': -192.0,
  'day': Timestamp('2021-09-13 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 0,
  'cume_units': 0,
  'units_percent_of_max': 0.0,
  'revenue': 0.0,
  'cume_revs': 0.0,
  'revs_percent_of_max': 0.0,
  'avg_price': nan,
  'free_units': 0,
  'cume_free_units': 0,
  'units_excl_refunds_incl_free': 2,
  'cume_combined_units': 13,
  'wishlist_adds': 25.0,
  'cume_wishlist_adds': 238.0,
  'wl_deletes': 0.0,
  'cume_wishlist_deletes': 11.0,
  'wl_activations': 0.0,
  'cume_wishlist_activations': 0.0,
  'activation_rate': 0.0,
  'cume_activation_rate': 0.0,
  'visits': 178.0,
  'cume_visits': 1440.0,
  'impressions': 4125.0,
  'cume_impressions': 35274.0,
  'refunded_units': 0,
  'cume_refunded_units': 0,
  'product_day': 'A Memoir Blue_2021-09-13',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -26.0,
  'dar': -184.0,
  'day': Timestamp('2021-09-21 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 0,
  'cume_units': 0,
  'units_percent_of_max': 0.0,
  'revenue': 0.0,
  'cume_revs': 0.0,
  'revs_percent_of_max': 0.0,
  'avg_price': nan,
  'free_units': 0,
  'cume_free_units': 0,
  'units_excl_refunds_incl_free': 1,
  'cume_combined_units': 14,
  'wishlist_adds': 20.0,
  'cume_wishlist_adds': 258.0,
  'wl_deletes': 2.0,
  'cume_wishlist_deletes': 13.0,
  'wl_activations': 0.0,
  'cume_wishlist_activations': 0.0,
  'activation_rate': 0.0,
  'cume_activation_rate': 0.0,
  'visits': 127.0,
  'cume_visits': 1567.0,
  'impressions': 2257.0,
  'cume_impressions': 37531.0,
  'refunded_units': 0,
  'cume_refunded_units': 0,
  'product_day': 'A Memoir Blue_2021-09-21',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -23.0,
  'dar': -163.0,
  'day': Timestamp('2021-10-12 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 0,
  'cume_units': 0,
  'units_percent_of_max': 0.0,
  'revenue': 0.0,
  'cume_revs': 0.0,
  'revs_percent_of_max': 0.0,
  'avg_price': nan,
  'free_units': 0,
  'cume_free_units': 0,
  'units_excl_refunds_incl_free': 9,
  'cume_combined_units': 23,
  'wishlist_adds': 102.0,
  'cume_wishlist_adds': 360.0,
  'wl_deletes': 0.0,
  'cume_wishlist_deletes': 13.0,
  'wl_activations': 0.0,
  'cume_wishlist_activations': 0.0,
  'activation_rate': 0.0,
  'cume_activation_rate': 0.0,
  'visits': 825.0,
  'cume_visits': 2392.0,
  'impressions': 19902.0,
  'cume_impressions': 57433.0,
  'refunded_units': 0,
  'cume_refunded_units': 0,
  'product_day': 'A Memoir Blue_2021-10-12',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -20.0,
  'dar': -142.0,
  'day': Timestamp('2021-11-02 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 0,
  'cume_units': 0,
  'units_percent_of_max': 0.0,
  'revenue': 0.0,
  'cume_revs': 0.0,
  'revs_percent_of_max': 0.0,
  'avg_price': nan,
  'free_units': 0,
  'cume_free_units': 0,
  'units_excl_refunds_incl_free': 2,
  'cume_combined_units': 25,
  'wishlist_adds': 36.0,
  'cume_wishlist_adds': 396.0,
  'wl_deletes': 2.0,
  'cume_wishlist_deletes': 15.0,
  'wl_activations': 0.0,
  'cume_wishlist_activations': 0.0,
  'activation_rate': 0.0,
  'cume_activation_rate': 0.0,
  'visits': 243.0,
  'cume_visits': 2635.0,
  'impressions': 9948.0,
  'cume_impressions': 67381.0,
  'refunded_units': 0,
  'cume_refunded_units': 0,
  'product_day': 'A Memoir Blue_2021-11-02',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': 0.0,
  'dar': -3.0,
  'day': Timestamp('2022-03-21 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 0,
  'cume_units': 0,
  'units_percent_of_max': 0.0,
  'revenue': 0.0,
  'cume_revs': 0.0,
  'revs_percent_of_max': 0.0,
  'avg_price': nan,
  'free_units': 2,
  'cume_free_units': 2,
  'units_excl_refunds_incl_free': 3,
  'cume_combined_units': 28,
  'wishlist_adds': 368.0,
  'cume_wishlist_adds': 764.0,
  'wl_deletes': 13.0,
  'cume_wishlist_deletes': 28.0,
  'wl_activations': 0.0,
  'cume_wishlist_activations': 0.0,
  'activation_rate': 0.0,
  'cume_activation_rate': 0.0,
  'visits': 1200.0,
  'cume_visits': 3835.0,
  'impressions': 64527.0,
  'cume_impressions': 131908.0,
  'refunded_units': 0,
  'cume_refunded_units': 0,
  'product_day': 'A Memoir Blue_2022-03-21',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': 0.0,
  'dar': -2.0,
  'day': Timestamp('2022-03-22 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 0,
  'cume_units': 0,
  'units_percent_of_max': 0.0,
  'revenue': 0.0,
  'cume_revs': 0.0,
  'revs_percent_of_max': 0.0,
  'avg_price': nan,
  'free_units': 11,
  'cume_free_units': 13,
  'units_excl_refunds_incl_free': 15,
  'cume_combined_units': 43,
  'wishlist_adds': 369.0,
  'cume_wishlist_adds': 1133.0,
  'wl_deletes': 17.0,
  'cume_wishlist_deletes': 45.0,
  'wl_activations': 0.0,
  'cume_wishlist_activations': 0.0,
  'activation_rate': 0.0,
  'cume_activation_rate': 0.0,
  'visits': 2215.0,
  'cume_visits': 6050.0,
  'impressions': 178845.0,
  'cume_impressions': 310753.0,
  'refunded_units': 0,
  'cume_refunded_units': 0,
  'product_day': 'A Memoir Blue_2022-03-22',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': 0.0,
  'dar': -1.0,
  'day': Timestamp('2022-03-23 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 0,
  'cume_units': 0,
  'units_percent_of_max': 0.0,
  'revenue': 0.0,
  'cume_revs': 0.0,
  'revs_percent_of_max': 0.0,
  'avg_price': nan,
  'free_units': 15,
  'cume_free_units': 28,
  'units_excl_refunds_incl_free': 17,
  'cume_combined_units': 60,
  'wishlist_adds': 626.0,
  'cume_wishlist_adds': 1759.0,
  'wl_deletes': 16.0,
  'cume_wishlist_deletes': 61.0,
  'wl_activations': 0.0,
  'cume_wishlist_activations': 0.0,
  'activation_rate': 0.0,
  'cume_activation_rate': 0.0,
  'visits': 3127.0,
  'cume_visits': 9177.0,
  'impressions': 285618.0,
  'cume_impressions': 596371.0,
  'refunded_units': 0,
  'cume_refunded_units': 0,
  'product_day': 'A Memoir Blue_2022-03-23',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': 1.0,
  'dar': 0.0,
  'day': Timestamp('2022-03-24 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 659,
  'cume_units': 659,
  'units_percent_of_max': 0.017059721970540266,
  'revenue': 4543.219999999999,
  'cume_revs': 4543.219999999999,
  'revs_percent_of_max': 0.023094282736377824,
  'avg_price': 6.89411229135053,
  'free_units': 73,
  'cume_free_units': 101,
  'units_excl_refunds_incl_free': 767,
  'cume_combined_units': 827,
  'wishlist_adds': 1842.0,
  'cume_wishlist_adds': 3601.0,
  'wl_deletes': 178.0,
  'cume_wishlist_deletes': 239.0,
  'wl_activations': 425.0,
  'cume_wishlist_activations': 425.0,
  'activation_rate': 0.23072747014115091,
  'cume_activation_rate': 0.11802277145237434,
  'visits': 14965.0,
  'cume_visits': 24142.0,
  'impressions': 448509.0,
  'cume_impressions': 1044880.0,
  'refunded_units': 11,
  'cume_refunded_units': 11,
  'product_day': 'A Memoir Blue_2022-03-24',
  'unit_daily_delta': inf,
  'rev_daily_delta': inf},
 {'product': 'A Memoir Blue',
  'weeks_from_release': 1.0,
  'dar': 1.0,
  'day': Timestamp('2022-03-25 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 519,
  'cume_units': 1178,
  'units_percent_of_max': 0.030495223795593985,
  'revenue': 3782.9,
  'cume_revs': 8326.119999999999,
  'revs_percent_of_max': 0.042323675581858275,
  'avg_price': 7.288824662813102,
  'free_units': 151,
  'cume_free_units': 252,
  'units_excl_refunds_incl_free': 687,
  'cume_combined_units': 1514,
  'wishlist_adds': 2305.0,
  'cume_wishlist_adds': 5906.0,
  'wl_deletes': 142.0,
  'cume_wishlist_deletes': 381.0,
  'wl_activations': 204.0,
  'cume_wishlist_activations': 629.0,
  'activation_rate': 0.08850325379609544,
  'cume_activation_rate': 0.10650186251269896,
  'visits': 30827.0,
  'cume_visits': 54969.0,
  'impressions': 602651.0,
  'cume_impressions': 1647531.0,
  'refunded_units': 12,
  'cume_refunded_units': 23,
  'product_day': 'A Memoir Blue_2022-03-25',
  'unit_daily_delta': -0.212443095599393,
  'rev_daily_delta': -0.16735267057285352},
 {'product': 'A Memoir Blue',
  'weeks_from_release': 1.0,
  'dar': 2.0,
  'day': Timestamp('2022-03-26 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 337,
  'cume_units': 1515,
  'units_percent_of_max': 0.03921923943151518,
  'revenue': 2491.75,
  'cume_revs': 10817.869999999999,
  'revs_percent_of_max': 0.05498984165093911,
  'avg_price': 7.393916913946588,
  'free_units': 6,
  'cume_free_units': 258,
  'units_excl_refunds_incl_free': 352,
  'cume_combined_units': 1866,
  'wishlist_adds': 1580.0,
  'cume_wishlist_adds': 7486.0,
  'wl_deletes': 95.0,
  'cume_wishlist_deletes': 476.0,
  'wl_activations': 88.0,
  'cume_wishlist_activations': 717.0,
  'activation_rate': 0.05569620253164557,
  'cume_activation_rate': 0.09577878706919583,
  'visits': 15222.0,
  'cume_visits': 70191.0,
  'impressions': 330483.0,
  'cume_impressions': 1978014.0,
  'refunded_units': 6,
  'cume_refunded_units': 29,
  'product_day': 'A Memoir Blue_2022-03-26',
  'unit_daily_delta': -0.35067437379576105,
  'rev_daily_delta': -0.34131222078299717},
 {'product': 'A Memoir Blue',
  'weeks_from_release': 1.0,
  'dar': 3.0,
  'day': Timestamp('2022-03-27 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 300,
  'cume_units': 1815,
  'units_percent_of_max': 0.046985425457557795,
  'revenue': 2196.8,
  'cume_revs': 13014.67,
  'revs_percent_of_max': 0.06615670575069102,
  'avg_price': 7.3226666666666675,
  'free_units': 7,
  'cume_free_units': 265,
  'units_excl_refunds_incl_free': 312,
  'cume_combined_units': 2178,
  'wishlist_adds': 1482.0,
  'cume_wishlist_adds': 8968.0,
  'wl_deletes': 82.0,
  'cume_wishlist_deletes': 558.0,
  'wl_activations': 63.0,
  'cume_wishlist_activations': 780.0,
  'activation_rate': 0.04251012145748988,
  'cume_activation_rate': 0.08697591436217662,
  'visits': 10630.0,
  'cume_visits': 80821.0,
  'impressions': 240615.0,
  'cume_impressions': 2218629.0,
  'refunded_units': 10,
  'cume_refunded_units': 39,
  'product_day': 'A Memoir Blue_2022-03-27',
  'unit_daily_delta': -0.10979228486646886,
  'rev_daily_delta': -0.11837062305608503},
 {'product': 'A Memoir Blue',
  'weeks_from_release': 1.0,
  'dar': 4.0,
  'day': Timestamp('2022-03-28 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 203,
  'cume_units': 2018,
  'units_percent_of_max': 0.05224054466851329,
  'revenue': 1537.02,
  'cume_revs': 14551.689999999999,
  'revs_percent_of_max': 0.07396974902208607,
  'avg_price': 7.5715270935960595,
  'free_units': 34,
  'cume_free_units': 299,
  'units_excl_refunds_incl_free': 243,
  'cume_combined_units': 2421,
  'wishlist_adds': 1048.0,
  'cume_wishlist_adds': 10016.0,
  'wl_deletes': 64.0,
  'cume_wishlist_deletes': 622.0,
  'wl_activations': 54.0,
  'cume_wishlist_activations': 834.0,
  'activation_rate': 0.05152671755725191,
  'cume_activation_rate': 0.0832667731629393,
  'visits': 7740.0,
  'cume_visits': 88561.0,
  'impressions': 188784.0,
  'cume_impressions': 2407413.0,
  'refunded_units': 9,
  'cume_refunded_units': 48,
  'product_day': 'A Memoir Blue_2022-03-28',
  'unit_daily_delta': -0.32333333333333336,
  'rev_daily_delta': -0.3003368536052441},
 {'product': 'A Memoir Blue',
  'weeks_from_release': 1.0,
  'dar': 5.0,
  'day': Timestamp('2022-03-29 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': 189,
  'cume_units': 2207,
  'units_percent_of_max': 0.05713324186492014,
  'revenue': 1388.51,
  'cume_revs': 15940.199999999999,
  'revs_percent_of_max': 0.081027880154254,
  'avg_price': 7.346613756613756,
  'free_units': 10,
  'cume_free_units': 309,
  'units_excl_refunds_incl_free': 204,
  'cume_combined_units': 2625,
  'wishlist_adds': 968.0,
  'cume_wishlist_adds': 10984.0,
  'wl_deletes': 76.0,
  'cume_wishlist_deletes': 698.0,
  'wl_activations': 45.0,
  'cume_wishlist_activations': 879.0,
  'activation_rate': 0.04648760330578512,
  'cume_activation_rate': 0.08002549162418063,
  'visits': 6161.0,
  'cume_visits': 94722.0,
  'impressions': 114805.0,
  'cume_impressions': 2522218.0,
  'refunded_units': 3,
  'cume_refunded_units': 51,
  'product_day': 'A Memoir Blue_2022-03-29',
  'unit_daily_delta': -0.06896551724137934,

requests

In [30]:
df.query("product == 'Stray'").sort_values(by='cume_wishlist_adds',ascending=False)

,product,weeks_from_release,dar,day,release_date,units,cume_units,units_percent_of_max,revenue,cume_revs,...,cume_activation_rate,visits,cume_visits,impressions,cume_impressions,refunded_units,cume_refunded_units,product_day,unit_daily_delta,rev_daily_delta
46599,Stray,168.0,1169.0,2025-09-30,2022-07-19,10,6918228,1.000000,190.26,1.570983e+08,...,0.267519,0.0,86317112.0,0.0,2.604677e+09,0,258223,Stray_2025-09-30,-0.995428,-0.994544
46598,Stray,167.0,1168.0,2025-09-29,2022-07-19,2187,6918218,0.999999,34870.44,1.570981e+08,...,0.267510,29012.0,86317112.0,1602179.0,2.604677e+09,31,258223,Stray_2025-09-29,0.542313,-0.045507
46597,Stray,167.0,1167.0,2025-09-28,2022-07-19,1418,6916031,0.999682,36532.95,1.570632e+08,...,0.267487,17367.0,86288100.0,531885.0,2.603074e+09,20,258192,Stray_2025-09-28,0.002829,0.005746
46596,Stray,167.0,1166.0,2025-09-27,2022-07-19,1414,6914613,0.999477,36324.23,1.570267e+08,...,0.267571,16107.0,86270733.0,487049.0,2.602543e+09,24,258172,Stray_2025-09-27,0.383562,0.377133
46595,Stray,167.0,1165.0,2025-09-26,2022-07-19,1022,6913199,0.999273,26376.71,1.569904e+08,...,0.267659,14085.0,86254626.0,458376.0,2.602056e+09,21,258148,Stray_2025-09-26,0.252451,0.260082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45363,Stray,-56.0,-398.0,2021-06-16,2022-07-19,0,0,0.000000,0.00,0.000000e+00,...,0.000000,1486.0,7955.0,4431.0,2.292900e+04,0,0,Stray_2021-06-16,NaN,NaN
45362,Stray,-56.0,-399.0,2021-06-15,2022-07-19,0,0,0.000000,0.00,0.000000e+00,...,0.000000,1668.0,6469.0,4406.0,1.849800e+04,0,0,Stray_2021-06-15,NaN,NaN
45361,Stray,-57.0,-404.0,2021-06-10,2022-07-19,0,0,0.000000,0.00,0.000000e+00,...,0.000000,2043.0,4801.0,4844.0,1.409200e+04,0,0,Stray_2021-06-10,NaN,NaN
45360,Stray,-57.0,-406.0,2021-06-08,2022-07-19,0,0,0.000000,0.00,0.000000e+00,...,0.000000,1275.0,2758.0,4866.0,9.248000e+03,0,0,Stray_2021-06-08,NaN,NaN
45359,Stray,-63.0,-445.0,2021-04-30,2022-07-19,0,0,0.000000,0.00,0.000000e+00,...,0.000000,1483.0,1483.0,4382.0,4.382000e+03,0,0,Stray_2021-04-30,NaN,NaN

In [31]:
df.tail()

,product,weeks_from_release,dar,day,release_date,units,cume_units,units_percent_of_max,revenue,cume_revs,...,cume_activation_rate,visits,cume_visits,impressions,cume_impressions,refunded_units,cume_refunded_units,product_day,unit_daily_delta,rev_daily_delta
62377,to a T,18.0,120.0,2025-09-25,2025-05-28,3,9679,0.995475,65.34,160133.81,...,0.114923,696.0,467930.0,12881.0,11038031.0,0,250,to a T_2025-09-25,0.000000,0.588235
62378,to a T,18.0,121.0,2025-09-26,2025-05-28,5,9684,0.995989,100.57,160234.38,...,0.114842,663.0,468593.0,11870.0,11049901.0,0,250,to a T_2025-09-26,0.666667,0.539180
62379,to a T,18.0,122.0,2025-09-27,2025-05-28,8,9692,0.996812,142.91,160377.29,...,0.114774,640.0,469233.0,12488.0,11062389.0,1,251,to a T_2025-09-27,0.600000,0.421000
62380,to a T,18.0,123.0,2025-09-28,2025-05-28,8,9700,0.997634,158.57,160535.86,...,0.114737,683.0,469916.0,12842.0,11075231.0,0,251,to a T_2025-09-28,0.000000,0.109579
62381,to a T,18.0,124.0,2025-09-29,2025-05-28,23,9723,1.000000,358.47,160894.33,...,0.115186,933.0,470849.0,21866.0,11097097.0,0,251,to a T_2025-09-29,1.875000,1.260642

In [32]:
df.query("product ==@product_name")[['cume_combined_units']]

       cume_combined_units
27300                    1
27301                    3
27302                 3811
27303                 9265
27304                13632
27305                17342
27306                21037
27307                25775
27308                30302
27309                33017
27310                35752
27311                37848
27312                40006
27313                42209
27314                45565
27315                48661
27316                48930

In [33]:
stop

NameError: name 'stop' is not defined

folder_path = "units/cume_revenues.xlsx"


revs  = pd.read_excel(folder_path, skiprows=2)

In [45]:
from pymongo import UpdateOne

## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [46]:
from datetime import datetime
date_string = datetime.today().strftime('%Y-%m-%d')

In [47]:
db = client['ai_sales_data']
collection = db['units']

unique_products = collection.distinct("product", {"date": {"$gte": 2025-01-01}})

unique_products

In [48]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

In [49]:
#####
for batch in batchify(records, 7500):
    operations = [
        UpdateOne(
            {"_id": doc["product_day"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 7500, Inserted: 0, Modified: 0
Matched: 7500, Inserted: 0, Modified: 0
Matched: 7500, Inserted: 0, Modified: 0
Matched: 7500, Inserted: 0, Modified: 0
Matched: 7500, Inserted: 0, Modified: 0
Matched: 7500, Inserted: 0, Modified: 0
Matched: 7500, Inserted: 0, Modified: 0
Matched: 7500, Inserted: 0, Modified: 0
Matched: 2382, Inserted: 0, Modified: 0

collection.update_many({}, {"$unset": {"percent_of_max": ""}})

In [50]:
client.close()