In [1]:
## Download from IndieBI, details by product, All Games No Soundtrack, daily units

#TEST Data is using EXPORT function and seems to be working.

import pandas as pd
import glob
import os

# Define folder path
folder_path = "DB_Update/units/"

# Get all Excel files in the folder
excel_files = glob.glob(os.path.join(folder_path, "*.xlsx"))

# Read and combine all files, skipping first 2 rows
df_list = [pd.read_excel(f, skiprows=2).assign(filename=os.path.basename(f)) for f in excel_files]
combined_df = pd.concat(df_list, ignore_index=True)

combined_df

df = combined_df.drop_duplicates(subset=['Day', 'product'])
df

import pandas as pd
import glob
import os

# Define folder path
folder_path = "DB_Update/revs/"

# Get all Excel files in the folder
excel_files = glob.glob(os.path.join(folder_path, "*.xlsx"))

# Read and combine all files, skipping first 2 rows
df_list = [pd.read_excel(f, skiprows=2).assign(filename=os.path.basename(f)) for f in excel_files]
combined_df_revs = pd.concat(df_list, ignore_index=True)

revs = combined_df_revs.drop_duplicates(subset=['Day', 'product'])
revs

import pandas as pd
import glob
import os

# Define folder path
folder_path = "DB_Update/wishlists/"

# Get all Excel files in the folder
excel_files = glob.glob(os.path.join(folder_path, "*.xlsx"))

# Read and combine all files, skipping first 2 rows
df_list = [pd.read_excel(f, skiprows=2).assign(filename=os.path.basename(f)) for f in excel_files]
combined_df_wl = pd.concat(df_list, ignore_index=True)

wishlists = combined_df_wl.drop_duplicates(subset=['Day', 'product'])
wishlists

df = df.rename({"Selected Measure":"units"}, axis=1)
revs = revs.rename({"Selected Measure":"revenue"}, axis=1)
#wishlists = wishlists.rename({"Selected Measure":"wishlist_adds"}, axis=1)

df = df.drop("Blank Measure", axis=1)
revs = revs.drop("Blank Measure", axis=1)
#wishlists = wishlists.drop("Blank Measure", axis=1)

df = df.drop("filename", axis=1)
revs = revs.drop("filename", axis=1)
#wishlists = wishlists.drop("filename", axis=1)

df

revs

df['cume_units'] = df.groupby('product')['units'].cumsum()
revs['cume_revs'] = revs.groupby('product')['revenue'].cumsum()
#wishlists['cume_wishlists'] = wishlists.groupby('product')['wishlist_adds'].cumsum()

df = df.merge(revs,on=['product', 'Day'], how='left')
#df = df.merge(wishlists,on=['product', 'Day'], how='left')

## Export Test

for f in excel_files:
    try:
        df = pd.read_excel(f, skipfooter=2, engine='openpyxl')
        print(f"✔ Loaded: {f}")
    except Exception as e:
        print(f"❌ Failed to load: {f} — {e}")

In [3]:
import pandas as pd
import glob
import os

# Define folder path
folder_path = "DB_Update/test"

# Get all Excel files in the folder
excel_files = glob.glob(os.path.join(folder_path, "*.xlsx"))

# Read and combine all files, skipping first 2 rows
df_list = [pd.read_excel(f, skipfooter=2).assign(filename=os.path.basename(f)) for f in excel_files]
combined_test = pd.concat(df_list, ignore_index=True)

/opt/anaconda3/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/opt/anaconda3/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/opt/anaconda3/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [4]:
import pandas as pd
import glob
import os
import warnings

warnings.filterwarnings("ignore")

In [5]:
combined_test_test = pd.read_csv("DB_Update/API/bulkAPI_Export.csv")

In [6]:
combined_test_test.query("Date=='2025-04-23' & Product =='Wheel World'")

,Date,Product,Revenue (excl. refunds),Units (excl. refunds),Free units,Wishlist adds,Non-owner visits,Non-owner impressions,Refunded units
431710,2025-04-23,Wheel World,NaN,NaN,NaN,47.0,813.0,11027.0,NaN

combined_test

In [7]:
rename_dict = {
'Date':'Day', 
    'Product':'product', 
    'Revenue (excl. refunds)':'revenue', 
    'Units (excl. refunds)':'units',
       'Free units':'free_units', 
    'Wishlist adds':'wishlist_adds', 
    'Non-owner visits':'visits',
       'Non-owner impressions':'impressions', 
    'Refunded units': 'refunded_units'
    
}

In [8]:
combined_test_test.rename(rename_dict, axis=1, inplace=True)

combined_test_test

In [9]:
test = combined_test_test.drop_duplicates(subset=['Day', 'product'])

In [10]:
test['Day'] = pd.to_datetime(test['Day'] )

In [11]:
test = test.sort_values(by='Day')

In [12]:
test.query("Day=='2025-04-23' & product =='Wheel World'")

,Day,product,revenue,units,free_units,wishlist_adds,visits,impressions,refunded_units
431710,2025-04-23,Wheel World,NaN,NaN,NaN,47.0,813.0,11027.0,NaN

In [13]:
test['cume_units'] = test.groupby('product')['units'].cumsum()
test['cume_revs'] = test.groupby('product')['revenue'].cumsum()

test['cume_free_units'] = test.groupby('product')['free_units'].cumsum()
test['cume_wishlist_adds'] = test.groupby('product')['wishlist_adds'].cumsum()
test['cume_visits'] = test.groupby('product')['visits'].cumsum()
test['cume_impressions'] = test.groupby('product')['impressions'].cumsum()
test['cume_refunded_units'] = test.groupby('product')['refunded_units'].cumsum()

In [14]:
cols_ = ['Day',
         'product',
         'units',
         'cume_units',
         'revenue',
         'cume_revs',
         'free_units',
         'cume_free_units',
         'wishlist_adds',
         'cume_wishlist_adds',
         'visits',
         'cume_visits',
         'impressions',
         'cume_impressions',
         'refunded_units',
         'cume_refunded_units']

In [15]:
df = test[cols_]

In [16]:
test[cols_].query("product=='Wheel World' & Day =='2025-04-23'")

,Day,product,units,cume_units,revenue,cume_revs,free_units,cume_free_units,wishlist_adds,cume_wishlist_adds,visits,cume_visits,impressions,cume_impressions,refunded_units,cume_refunded_units
431710,2025-04-23,Wheel World,NaN,NaN,NaN,NaN,NaN,NaN,47.0,85211.0,813.0,445518.0,11027.0,12156481.0,NaN,NaN

In [17]:
df

,Day,product,units,cume_units,revenue,cume_revs,free_units,cume_free_units,wishlist_adds,cume_wishlist_adds,visits,cume_visits,impressions,cume_impressions,refunded_units,cume_refunded_units
0,2010-01-01,A Memoir Blue,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
54,2010-01-01,Stray,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
53,2010-01-01,Storyteller - Original Soundtrack,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
52,2010-01-01,Storyteller,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
51,2010-01-01,Solar Ash - Original Soundtrack,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443341,2025-09-05,Gorogoa,3.0,1162341.0,26.62,6580803.57,0.0,5661.0,13.0,983232.0,0.0,4311658.0,0.0,207790431.0,0.0,53370.0
443340,2025-09-05,If Found... - Original Soundtrack,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1113.0,0.0,128826.0,0.0,7228990.0,NaN,NaN
443339,2025-09-05,Faraway,NaN,NaN,NaN,NaN,NaN,NaN,0.0,5611.0,0.0,49855.0,0.0,1819007.0,NaN,NaN
443347,2025-09-05,I Am Dead - Original Soundtrack,NaN,NaN,NaN,NaN,NaN,NaN,0.0,840.0,0.0,131160.0,0.0,7022117.0,NaN,NaN
443400,2025-09-05,to a T - Soundtrack,NaN,NaN,NaN,NaN,NaN,NaN,0.0,57.0,0.0,4917.0,0.0,131190.0,NaN,NaN

stop

In [18]:
folder_path = "wishlists/Annapurna Interactive Historical Revenues - releases_dates.csv"
dates  = pd.read_csv(folder_path)
dates = dates.dropna(subset='pc_release_date')
dates['pc_release_date'] = pd.to_datetime(dates['pc_release_date'])
release_date_dict = dates.groupby('product')['pc_release_date'].min().to_dict()

In [19]:
release_date_dict.get("Donut County")

Timestamp('2018-08-28 00:00:00')

In [20]:
df['release_date'] = pd.to_datetime(df['Day'])


df["units_percent_of_max"] = df["cume_units"] / df.groupby("product")["cume_units"].transform("max")
df["revs_percent_of_max"] = df["cume_revs"] / df.groupby("product")["cume_revs"].transform("max")

In [21]:
df['release_date'] = pd.to_datetime(df['Day'])
df['Day'] = pd.to_datetime(df['Day']).dt.to_pydatetime()
df['release_date'] = df.groupby('product')['release_date'].transform('min')
df['release_date'] = df['product'].map(release_date_dict)
df["DAR"] = (df["Day"] - df["release_date"]).dt.days
#df["DAR"] = df.groupby("product")["DAR"].transform(lambda x: x.clip(lower=0))

df["Weeks_from_Release"] = (df["DAR"] // 7) + 1  # Week 1 starts at 0-7 days

In [22]:
df["avg_price"] = df["revenue"] / df["units"]

In [23]:
value_cols = [

'units',
         'cume_units',
'units_percent_of_max',
         'revenue',
         'cume_revs',
'revs_percent_of_max',
'avg_price',
         'free_units',
         'cume_free_units',
         'wishlist_adds',
         'cume_wishlist_adds',
         'visits',
         'cume_visits',
         'impressions',
         'cume_impressions',
         'refunded_units',
         'cume_refunded_units'

]

In [24]:
df = df.groupby(["product", "Weeks_from_Release",'DAR','Day','release_date'], as_index=False)[value_cols].max()

In [25]:
df.columns = [col.strip().replace(" ", "_").lower() for col in df.columns]
#df['date'] = pd.to_datetime(df['date'], format="%d %B, %Y")

In [26]:
df['product_day'] = df['product'].astype(str) + '_' + df['day'].astype(str)
#df.set_index('product_day', inplace=True)

In [27]:
df['unit_daily_delta']  = df.groupby('product')['units'].pct_change()
df['rev_daily_delta']  = df.groupby('product')['revenue'].pct_change()

df.query("product =='Stray'")

In [28]:
records = df.to_dict(orient="records")
records

[{'product': 'A Memoir Blue',
  'weeks_from_release': -637.0,
  'dar': -4465.0,
  'day': Timestamp('2010-01-01 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-01',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -637.0,
  'dar': -4464.0,
  'day': Timestamp('2010-01-02 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-02',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -637.0,
  'dar': -4463.0,
  'day': Timestamp('2010-01-03 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-03',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -637.0,
  'dar': -4462.0,
  'day': Timestamp('2010-01-04 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-04',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -637.0,
  'dar': -4461.0,
  'day': Timestamp('2010-01-05 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-05',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -637.0,
  'dar': -4460.0,
  'day': Timestamp('2010-01-06 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-06',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -636.0,
  'dar': -4459.0,
  'day': Timestamp('2010-01-07 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-07',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -636.0,
  'dar': -4458.0,
  'day': Timestamp('2010-01-08 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-08',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -636.0,
  'dar': -4457.0,
  'day': Timestamp('2010-01-09 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-09',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -636.0,
  'dar': -4456.0,
  'day': Timestamp('2010-01-10 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-10',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -636.0,
  'dar': -4455.0,
  'day': Timestamp('2010-01-11 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-11',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -636.0,
  'dar': -4454.0,
  'day': Timestamp('2010-01-12 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-12',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -636.0,
  'dar': -4453.0,
  'day': Timestamp('2010-01-13 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-13',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -635.0,
  'dar': -4452.0,
  'day': Timestamp('2010-01-14 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-14',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -635.0,
  'dar': -4451.0,
  'day': Timestamp('2010-01-15 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-15',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -635.0,
  'dar': -4450.0,
  'day': Timestamp('2010-01-16 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-16',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -635.0,
  'dar': -4449.0,
  'day': Timestamp('2010-01-17 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-17',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -635.0,
  'dar': -4448.0,
  'day': Timestamp('2010-01-18 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-18',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -635.0,
  'dar': -4447.0,
  'day': Timestamp('2010-01-19 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-19',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -635.0,
  'dar': -4446.0,
  'day': Timestamp('2010-01-20 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-20',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -634.0,
  'dar': -4445.0,
  'day': Timestamp('2010-01-21 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-21',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -634.0,
  'dar': -4444.0,
  'day': Timestamp('2010-01-22 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-22',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -634.0,
  'dar': -4443.0,
  'day': Timestamp('2010-01-23 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-23',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -634.0,
  'dar': -4442.0,
  'day': Timestamp('2010-01-24 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-24',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -634.0,
  'dar': -4441.0,
  'day': Timestamp('2010-01-25 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-25',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -634.0,
  'dar': -4440.0,
  'day': Timestamp('2010-01-26 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-26',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -634.0,
  'dar': -4439.0,
  'day': Timestamp('2010-01-27 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-27',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -633.0,
  'dar': -4438.0,
  'day': Timestamp('2010-01-28 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-28',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -633.0,
  'dar': -4437.0,
  'day': Timestamp('2010-01-29 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,
  'impressions': 0.0,
  'cume_impressions': 0.0,
  'refunded_units': nan,
  'cume_refunded_units': nan,
  'product_day': 'A Memoir Blue_2010-01-29',
  'unit_daily_delta': nan,
  'rev_daily_delta': nan},
 {'product': 'A Memoir Blue',
  'weeks_from_release': -633.0,
  'dar': -4436.0,
  'day': Timestamp('2010-01-30 00:00:00'),
  'release_date': Timestamp('2022-03-24 00:00:00'),
  'units': nan,
  'cume_units': nan,
  'units_percent_of_max': nan,
  'revenue': nan,
  'cume_revs': nan,
  'revs_percent_of_max': nan,
  'avg_price': nan,
  'free_units': nan,
  'cume_free_units': nan,
  'wishlist_adds': 0.0,
  'cume_wishlist_adds': 0.0,
  'visits': 0.0,
  'cume_visits': 0.0,

requests

In [29]:
df.query("product == 'to a T'").sort_values(by='cume_units',ascending=False)

,product,weeks_from_release,dar,day,release_date,units,cume_units,units_percent_of_max,revenue,cume_revs,...,cume_wishlist_adds,visits,cume_visits,impressions,cume_impressions,refunded_units,cume_refunded_units,product_day,unit_daily_delta,rev_daily_delta
256702,to a T,15.0,99.0,2025-09-04,2025-05-28,23.0,9527.0,1.000000,377.54,157503.02,...,67278.0,1028.0,719355.0,58550.0,15269284.0,0.0,246.0,to a T_2025-09-04,0.277778,0.289280
256701,to a T,15.0,98.0,2025-09-03,2025-05-28,18.0,9504.0,0.997586,292.83,157125.48,...,67227.0,934.0,718327.0,44880.0,15210734.0,1.0,246.0,to a T_2025-09-03,-0.100000,0.014411
256700,to a T,14.0,97.0,2025-09-02,2025-05-28,20.0,9486.0,0.995696,288.67,156832.65,...,67167.0,963.0,717393.0,47101.0,15165854.0,1.0,245.0,to a T_2025-09-02,-0.230769,-0.280322
256699,to a T,14.0,96.0,2025-09-01,2025-05-28,26.0,9466.0,0.993597,401.11,156543.98,...,67111.0,976.0,716430.0,43886.0,15118753.0,0.0,244.0,to a T_2025-09-01,0.368421,0.474344
256698,to a T,14.0,95.0,2025-08-31,2025-05-28,19.0,9440.0,0.990868,272.06,156142.87,...,67047.0,987.0,715454.0,39313.0,15074867.0,0.0,244.0,to a T_2025-08-31,-0.050000,-0.092982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256585,to a T,-2.0,-18.0,2025-05-10,2025-05-28,NaN,NaN,NaN,NaN,NaN,...,30641.0,485.0,289605.0,7919.0,5305457.0,NaN,NaN,to a T_2025-05-10,NaN,NaN
256586,to a T,-2.0,-17.0,2025-05-11,2025-05-28,NaN,NaN,NaN,NaN,NaN,...,30724.0,529.0,290134.0,8039.0,5313496.0,NaN,NaN,to a T_2025-05-11,NaN,NaN
256589,to a T,-1.0,-14.0,2025-05-14,2025-05-28,NaN,NaN,NaN,NaN,NaN,...,30963.0,487.0,291716.0,7527.0,5336838.0,NaN,NaN,to a T_2025-05-14,NaN,NaN
256591,to a T,-1.0,-12.0,2025-05-16,2025-05-28,NaN,NaN,NaN,NaN,NaN,...,31176.0,761.0,293027.0,8701.0,5353188.0,NaN,NaN,to a T_2025-05-16,NaN,NaN
256703,to a T,15.0,100.0,2025-09-05,2025-05-28,NaN,NaN,NaN,NaN,NaN,...,67283.0,0.0,719355.0,0.0,15269284.0,NaN,NaN,to a T_2025-09-05,0.000000,0.000000

In [30]:
df.head()

,product,weeks_from_release,dar,day,release_date,units,cume_units,units_percent_of_max,revenue,cume_revs,...,cume_wishlist_adds,visits,cume_visits,impressions,cume_impressions,refunded_units,cume_refunded_units,product_day,unit_daily_delta,rev_daily_delta
0,A Memoir Blue,-637.0,-4465.0,2010-01-01,2022-03-24,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,A Memoir Blue_2010-01-01,NaN,NaN
1,A Memoir Blue,-637.0,-4464.0,2010-01-02,2022-03-24,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,A Memoir Blue_2010-01-02,NaN,NaN
2,A Memoir Blue,-637.0,-4463.0,2010-01-03,2022-03-24,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,A Memoir Blue_2010-01-03,NaN,NaN
3,A Memoir Blue,-637.0,-4462.0,2010-01-04,2022-03-24,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,A Memoir Blue_2010-01-04,NaN,NaN
4,A Memoir Blue,-637.0,-4461.0,2010-01-05,2022-03-24,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,A Memoir Blue_2010-01-05,NaN,NaN

In [31]:
stop

NameError: name 'stop' is not defined

folder_path = "units/cume_revenues.xlsx"


revs  = pd.read_excel(folder_path, skiprows=2)

In [32]:
from pymongo import UpdateOne

## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [33]:
from datetime import datetime
date_string = datetime.today().strftime('%Y-%m-%d')

In [34]:
db = client['ai_sales_data']
collection = db['units']

unique_products = collection.distinct("product", {"date": {"$gte": 2025-01-01}})

unique_products

In [35]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

In [36]:
#####
for batch in batchify(records, 7500):
    operations = [
        UpdateOne(
            {"_id": doc["product_day"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 7500, Inserted: 0, Modified: 1261
Matched: 7500, Inserted: 0, Modified: 2465
Matched: 7498, Inserted: 2, Modified: 1
Matched: 7498, Inserted: 2, Modified: 737
Matched: 7500, Inserted: 0, Modified: 2594
Matched: 7497, Inserted: 3, Modified: 316
Matched: 7499, Inserted: 1, Modified: 3149
Matched: 7499, Inserted: 1, Modified: 2395
Matched: 7500, Inserted: 0, Modified: 2823
Matched: 7498, Inserted: 2, Modified: 2135
Matched: 7500, Inserted: 0, Modified: 1798
Matched: 7499, Inserted: 1, Modified: 2316
Matched: 7497, Inserted: 3, Modified: 3976
Matched: 7499, Inserted: 1, Modified: 1494
Matched: 7499, Inserted: 1, Modified: 621
Matched: 7499, Inserted: 1, Modified: 1641
Matched: 7498, Inserted: 2, Modified: 1
Matched: 7497, Inserted: 3, Modified: 1635
Matched: 7498, Inserted: 2, Modified: 1200
Matched: 7499, Inserted: 1, Modified: 734
Matched: 7500, Inserted: 0, Modified: 3530
Matched: 7500, Inserted: 0, Modified: 3618
Matched: 7498, Inserted: 2, Modified: 129
Matched: 7499, Inserted: 1, Modified: 1385
Matched: 7500, Inserted: 0, Modified: 1610
Matched: 7500, Inserted: 0, Modified: 2686
Matched: 7500, Inserted: 0, Modified: 1458
Matched: 7498, Inserted: 2, Modified: 887
Matched: 7498, Inserted: 2, Modified: 2706
Matched: 7499, Inserted: 1, Modified: 662
Matched: 7500, Inserted: 0, Modified: 1486
Matched: 7498, Inserted: 2, Modified: 2289
Matched: 7500, Inserted: 0, Modified: 3098
Matched: 7499, Inserted: 1, Modified: 44
Matched: 1703, Inserted: 1, Modified: 100

collection.update_many({}, {"$unset": {"percent_of_max": ""}})

In [37]:
client.close()