In [1]:
import pandas as pd
import glob
import os
import warnings

warnings.filterwarnings("ignore")

In [2]:


# Define folder path
folder_path = "/Users/dougs/Annapurna Dropbox/Doug Sack/Interactive/IndieBI/sales_curve_data/units/"

# Get all .xlsx files in the folder
files = glob.glob(f"{folder_path}/*.xlsx")

# Read all files into DataFrames and add filename column
dfs = [pd.read_excel(file, skiprows=2).assign(Source=os.path.basename(file)) for file in files]

In [3]:
df = pd.concat(dfs, ignore_index=True)

In [4]:
df.head()

        Date product  Cumulative Selected Measure           Source
0 2018-12-07   Ashen                         2290  epic_units.xlsx
1 2018-12-08   Ashen                         4713  epic_units.xlsx
2 2018-12-09   Ashen                         7038  epic_units.xlsx
3 2018-12-10   Ashen                         8702  epic_units.xlsx
4 2018-12-11   Ashen                        10125  epic_units.xlsx

In [5]:
df.Source.unique()

array(['epic_units.xlsx', 'xbox_units.xlsx', 'nintendo_units.xlsx',
       'steam_units.xlsx', 'PS_units.xlsx'], dtype=object)

In [6]:
file_name = 'xbox_units'

In [7]:
release_dict = {'The Lost Wild': '2025-12-31',
 'Wattam': '2019-12-17',
 'Storyteller: Devilish Update': '2023-09-26',
 'The Artful Escape': '2021-09-09',
 'Annapurna Interactive Deluxe Limited Edition Collection': '2023-12-22',
 'Annapurna Interactive: Ultimate Collection': '2020-12-08',
 'Annapurna Interactive Deluxe Limited Edition': '2020-12-15',
 'I Am Dead': '2020-10-08',
 'Outer Wilds: Archaeologist Edition': '2021-09-28',
 'The Pathless': '2020-11-12',
 'If Found...': '2020-05-19',
 'Telling Lies': '2019-08-23',
 'A Memoir Blue': '2022-03-24',
 'Stray': '2022-07-19',
 'Last Stop': '2021-07-22',
 'To a T': '2025-05-28',
 'Mundaun': '2021-03-16',
 'Solar Ash': '2021-12-02',
 'What Remains of Edith Finch': '2017-04-24',
 'Sayonara Wild Hearts': '2019-9-19',
 'Lushfoil Photography Sim': '2025-04-15',
 'Storyteller': '2023-03-23',
 'Gorogoa': '2017-12-13',
 'Wanderstop': '2025-03-11',
 'Journey': '2012-03-13',
 'Mixtape': '2025-12-31',
 'Open Roads': '2024-03-28',
 'Neon White': '2022-06-16',
 'Flower': '2009-02-12',
 'Twelve Minutes': '2021-08-19',
 'Outer Wilds: Echoes of the Eye': '2021-09-28',
 'Flock': '2024-07-16',
 'Maquette': '2021-03-02',
 'Cocoon': '2023-09-29',
 'Gone Home': '2013-08-15',
 'Outer Wilds': '2019-05-28',
 'Ashen: Nightstorm Isle': '2019-09-06',
 'Florence': '2018-02-13',
 'Thirsty Suitors': '2023-11-02',
 'Lorelei and the Laser Eyes': '2024-05-16',
 'Donut County': '2018-08-28',
 'Skin Deep': '2025-04-30',
 'Wheel World': '2025-06-30',
 'Hohokum': '2014-08-12',
 'Ashen: Definitive Edition': '2019-11-18',
 'Morsels': '2025-12-31',
 'Kentucky Route Zero: TV Edition': '2020-01-28',
 'The Unfinished Swan': '2012-10-23',
 'Hindsight': '2022-08-04',
 'Ashen': '2018-12-07'}

In [8]:
df_combined = df.query(f"Source =='{file_name}.xlsx'")
#df_combined['release_date'] = df_combined['product'].map(release_dict)

In [9]:
df_combined

,Date,product,Cumulative Selected Measure,Source
28785,2017-03-14,What Remains of Edith Finch,165,xbox_units.xlsx
28786,2017-03-15,What Remains of Edith Finch,438,xbox_units.xlsx
28787,2017-03-16,What Remains of Edith Finch,614,xbox_units.xlsx
28788,2017-03-17,What Remains of Edith Finch,726,xbox_units.xlsx
28789,2017-03-18,What Remains of Edith Finch,871,xbox_units.xlsx
...,...,...,...,...
125684,2025-04-16,Wanderstop - Soundtrack,1991,xbox_units.xlsx
125685,2025-04-16,Wattam,92303,xbox_units.xlsx
125686,2025-04-16,Wattam - Original Soundtrack,1023,xbox_units.xlsx
125687,2025-04-16,What Remains of Edith Finch,2488076,xbox_units.xlsx
125688,2025-04-16,What Remains of Edith Finch - Original Soundtrack,40103,xbox_units.xlsx

In [10]:
df_combined['release_date'] = pd.to_datetime(df_combined['Date'])

In [11]:
df_combined['release_date'] = df_combined.groupby('product')['release_date'].transform('min')

In [12]:
df_combined["DAR"] = (df_combined["Date"] - df_combined["release_date"]).dt.days
#df_combined["DAR"] = df_combined["DAR"].clip(lower=0)

df_combined["Weeks_from_Release"] = (df_combined["DAR"] // 30) + 1  # Week 1 starts at 0-7 days

df_combined = df_combined.query("0 <= Weeks_from_Release <=52")

df_combined = df_combined.query("'1/1/2015' <= release_date <='1/1/2025'")

df_combined = df_combined.groupby(["product", "Weeks_from_Release"], as_index=False)["Cumulative Selected Measure"].max()

In [13]:
title_exclusion = [
'Stray','Outer Wilds'
    

]

In [14]:
df_combined['product'].unique()

array(['A Memoir Blue', 'A Memoir Blue - Original Soundtrack', 'Ashen',
       'Ashen - Nightstorm Isle DLC', 'Ashen - Original Soundtrack',
       'Ashen Definitive Edition', 'Cocoon', 'Cocoon - Soundtrack',
       'Donut County', 'Donut County - Original Soundtrack',
       'Due Process', 'Due Process - Original Soundtrack', 'Flock',
       'Flock - Original Soundtrack', 'Florence',
       'Florence - Original Soundtrack', 'Flower', 'Gone Home', 'Gorogoa',
       'Gorogoa - Original Soundtrack', 'Hindsight',
       'Hindsight - Original Soundtrack', 'Hohokum', 'I Am Dead',
       'I Am Dead - Original Soundtrack', 'If Found...',
       'If Found... - Original Soundtrack', 'Journey',
       'Kentucky Route Zero: TV Edition', 'Last Stop',
       'Last Stop - Original Soundtrack', 'Lorelei and the Laser Eyes',
       'Lorelei and the Laser Eyes - Original Soundtrack', 'Maquette',
       'Mundaun', 'Neon White', 'Neon White - Original Soundtrack',
       'Open Roads', 'Outer Wilds',
       'Outer Wilds - Archaeologist Edition BUNDLE',
       'Outer Wilds - Echoes of the Eye DLC',
       'Outer Wilds - Original Soundtrack', 'Sayonara Wild Hearts',
       'Sayonara Wild Hearts - Original Soundtrack', 'Solar Ash',
       'Solar Ash - Original Soundtrack', 'Storyteller',
       'Storyteller - Original Soundtrack', 'Stray',
       'Stray - Original Soundtrack', 'Telling Lies',
       'Telling Lies - Original Soundtrack', 'The Artful Escape',
       'The Artful Escape - Original Soundtrack', 'The Pathless',
       'The Pathless - Original Soundtrack', 'The Unfinished Swan',
       'Thirsty Suitors', 'Thirsty Suitors - Original Soundtrack',
       'Twelve Minutes', 'Twelve Minutes - Original Soundtrack', 'Wattam',
       'Wattam - Original Soundtrack', 'What Remains of Edith Finch',
       'What Remains of Edith Finch - Original Soundtrack'], dtype=object)

In [15]:
df_combined

,product,Weeks_from_Release,Cumulative Selected Measure
0,A Memoir Blue,1,3977
1,A Memoir Blue,2,5046
2,A Memoir Blue,3,7948
3,A Memoir Blue,4,9367
4,A Memoir Blue,5,10277
...,...,...,...
2715,What Remains of Edith Finch - Original Soundtrack,48,30502
2716,What Remains of Edith Finch - Original Soundtrack,49,30526
2717,What Remains of Edith Finch - Original Soundtrack,50,30708
2718,What Remains of Edith Finch - Original Soundtrack,51,30835
2719,What Remains of Edith Finch - Original Soundtrack,52,30914

In [16]:
df_combined = df_combined.query("product !=@title_exclusion")

In [17]:
#pd.set_option("display.max_rows", None)


df_combined["CUME_total"] = df_combined.groupby(["product"])["Cumulative Selected Measure"].transform("max")
df_combined["prop_of_total"] = df_combined["Cumulative Selected Measure"] / df_combined["CUME_total"]
df_combined["daily_delta"] = df_combined.groupby(["product"])["Cumulative Selected Measure"].pct_change().fillna(0)
df_combined.query("product=='Maquette'")

,product,Weeks_from_Release,Cumulative Selected Measure,CUME_total,prop_of_total,daily_delta
1375,Maquette,1,8384,43043,0.194782,0.000000
1376,Maquette,2,10486,43043,0.243617,0.250716
1377,Maquette,3,12260,43043,0.284831,0.169178
1378,Maquette,4,13456,43043,0.312618,0.097553
1379,Maquette,5,14461,43043,0.335966,0.074688
1380,Maquette,6,15271,43043,0.354785,0.056013
1381,Maquette,7,15905,43043,0.369514,0.041517
1382,Maquette,8,16460,43043,0.382408,0.034895
1383,Maquette,9,17424,43043,0.404804,0.058566
1384,Maquette,10,18384,43043,0.427108,0.055096
1385,Maquette,11,19571,43043,0.454685,0.064567
1386,Maquette,12,20482,43043,0.475850,0.046548
1387,Maquette,13,20981,43043,0.487443,0.024363
1388,Maquette,14,22086,43043,0.513115,0.052667
1389,Maquette,15,22640,43043,0.525986,0.025084
1390,Maquette,16,24614,43043,0.571847,0.087191
1391,Maquette,17,25398,43043,0.590061,0.031852
1392,Maquette,18,25962,43043,0.603164,0.022206
1393,Maquette,19,26429,43043,0.614014,0.017988
1394,Maquette,20,26597,43043,0.617917,0.006357
1395,Maquette,21,27268,43043,0.633506,0.025228
1396,Maquette,22,27663,43043,0.642683,0.014486
1397,Maquette,23,28510,43043,0.662361,0.030619
1398,Maquette,24,28767,43043,0.668332,0.009014
1399,Maquette,25,29150,43043,0.677230,0.013314
1400,Maquette,26,29542,43043,0.686337,0.013448
1401,Maquette,27,29925,43043,0.695235,0.012965
1402,Maquette,28,30956,43043,0.719188,0.034453
1403,Maquette,29,31672,43043,0.735822,0.023130
1404,Maquette,30,32759,43043,0.761076,0.034321
1405,Maquette,31,33088,43043,0.768720,0.010043
1406,Maquette,32,33715,43043,0.783286,0.018949
1407,Maquette,33,34492,43043,0.801338,0.023046
1408,Maquette,34,35035,43043,0.813953,0.015743
1409,Maquette,35,35909,43043,0.834259,0.024946
1410,Maquette,36,36345,43043,0.844388,0.012142
1411,Maquette,37,37060,43043,0.860999,0.019673
1412,Maquette,38,37517,43043,0.871617,0.012331
1413,Maquette,39,38001,43043,0.882861,0.012901
1414,Maquette,40,38584,43043,0.896406,0.015342
1415,Maquette,41,39173,43043,0.910090,0.015265
1416,Maquette,42,39583,43043,0.919615,0.010466
1417,Maquette,43,39984,43043,0.928932,0.010131
1418,Maquette,44,40056,43043,0.930604,0.001801
1419,Maquette,45,40280,43043,0.935808,0.005592
1420,Maquette,46,40890,43043,0.949980,0.015144
1421,Maquette,47,41775,43043,0.970541,0.021643
1422,Maquette,48,42094,43043,0.977952,0.007636
1423,Maquette,49,42507,43043,0.987547,0.009811
1424,Maquette,50,42773,43043,0.993727,0.006258
1425,Maquette,51,43043,43043,1.000000,0.006312

In [18]:
df_combined.query("Weeks_from_Release==1")

,product,Weeks_from_Release,Cumulative Selected Measure,CUME_total,prop_of_total,daily_delta
0,A Memoir Blue,1,3977,35479,0.112094,0.0
38,A Memoir Blue - Original Soundtrack,1,113,610,0.185246,0.0
76,Ashen,1,28633,425803,0.067245,0.0
128,Ashen - Nightstorm Isle DLC,1,699,130049,0.005375,0.0
180,Ashen - Original Soundtrack,1,312,1760,0.177273,0.0
...,...,...,...,...,...,...
2467,Twelve Minutes - Original Soundtrack,1,1307,3365,0.388410,0.0
2512,Wattam,1,1547,83878,0.018443,0.0
2564,Wattam - Original Soundtrack,1,223,1018,0.219057,0.0
2616,What Remains of Edith Finch,1,2888,1020277,0.002831,0.0
2668,What Remains of Edith Finch - Original Soundtrack,1,1693,30914,0.054765,0.0

In [19]:
platform_df = df_combined.groupby("Weeks_from_Release")[['daily_delta']].mean()
platform_df['platform'] = 'epic'

In [20]:
platform_df

                    daily_delta platform
Weeks_from_Release
1                      0.000000     epic
2                      0.864807     epic
3                      0.248416     epic
4                      0.314078     epic
5                      0.165668     epic
6                      0.101504     epic
7                      0.107327     epic
8                      0.100959     epic
9                      0.063791     epic
10                     0.062193     epic
11                     0.046877     epic
12                     0.052153     epic
13                     0.078001     epic
14                     0.050334     epic
15                     0.038336     epic
16                     0.057065     epic
17                     0.040590     epic
18                     0.035304     epic
19                     0.033345     epic
20                     0.031273     epic
21                     0.040044     epic
22                     0.033699     epic
23                     0.031252     epic
24                     0.025279     epic
25                     0.027823     epic
26                     0.035737     epic
27                     0.026892     epic
28                     0.031993     epic
29                     0.030218     epic
30                     0.027185     epic
31                     0.018519     epic
32                     0.025847     epic
33                     0.017310     epic
34                     0.025654     epic
35                     0.017604     epic
36                     0.016918     epic
37                     0.019481     epic
38                     0.018624     epic
39                     0.015287     epic
40                     0.017900     epic
41                     0.024872     epic
42                     0.017110     epic
43                     0.014983     epic
44                     0.013497     epic
45                     0.009743     epic
46                     0.015800     epic
47                     0.014531     epic
48                     0.010817     epic
49                     0.011211     epic
50                     0.011273     epic
51                     0.010625     epic
52                     0.010246     epic

stop

In [21]:
platform_df.to_csv(f"units/{file_name}_average.csv")

In [22]:
stop

NameError: name 'stop' is not defined

In [ ]:
### Fit the Curve to a model and use this to predict



# Define folder path
folder_path = "/Users/dougs/Documents/GitHub/IndieBI-Sales-EDA/units/"

# Get all .xlsx files in the folder
files = glob.glob(f"{folder_path}/*.csv")

# Read all files into DataFrames and add filename column
dfs = [pd.read_csv(file).assign(Source=os.path.basename(file)) for file in files]

In [ ]:
files

In [ ]:
av_df = pd.concat(dfs, ignore_index=True)

In [ ]:
platforms = av_df.pivot_table(columns='platform', index='Weeks_from_Release', values='daily_delta').reset_index()

In [ ]:
platforms.to_clipboard()

In [ ]:
platforms.columns[1:]

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))  # Adjust figure size for better visibility

# Loop through unique platforms and plot each separately
for platform in ['steam', 'PS']:
    pdf = av_df.query("platform == @platform")
    sns.lineplot(data=pdf, x='Weeks_from_Release', y='daily_delta', label=platform)

# Improve aesthetics
plt.xlabel("Weeks After Release (DAR)")
plt.ylabel("Daily Average New Units Sold")
plt.title("Sales Curve by Platform")
plt.legend(title="Platform", loc="best")  # Set legend title
plt.grid(True)  # Add grid for readability

plt.show()

In [ ]:
platforms.query("Weeks_from_Release <=12")

In [ ]:
starting_val = 31_200

In [ ]:
current_week  = 1

In [ ]:
platforms.loc[current_week-1,'steam_projected'] = starting_val

In [ ]:
platforms.loc[current_week-1,'steam_projected'] = starting_val

In [ ]:
# Apply cumulative product starting from the specified index
platforms.loc[current_week:, 'steam_projected'] = (
    starting_val * (1 + platforms.loc[current_week:, 'steam']).cumprod()
)

In [ ]:
platforms['steam_projected'] = platforms['steam_projected'].fillna(starting_val)
platforms['steam_projected'] = platforms['steam_projected'].astype(int)

In [ ]:
platforms.to_clipboard()
platforms

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))  # Adjust figure size for better visibility


sns.lineplot(data=platforms.query("Weeks_from_Release <=12"), x='Weeks_from_Release', y='steam_projected', label='steam_projected')

# Improve aesthetics
plt.xlabel("Weeks After Release (DAR)")
plt.ylabel("Daily Average New Units Sold")
plt.title("Sales Curve by Platform")
plt.legend(title="Platform", loc="best")  # Set legend title
plt.grid(True)  # Add grid for readability

plt.show()