In [1]:
import pandas as pd
import glob
import os
import warnings

warnings.filterwarnings("ignore")

In [2]:


# Define folder path
folder_path = "/Users/dougs/Annapurna Dropbox/Doug Sack/Interactive/IndieBI/sales_curve_data/yearly/"

# Get all .xlsx files in the folder
files = glob.glob(f"{folder_path}/*.xlsx")

# Read all files into DataFrames and add filename column
dfs = [pd.read_excel(file, skiprows=2).assign(Source=os.path.basename(file)) for file in files]

In [3]:
df = pd.concat(dfs, ignore_index=True)

In [4]:
df.head()

        Date product  Cumulative Selected Measure            Source
0 2018-12-07   Ashen                       2290.0  epic_yearly.xlsx
1 2018-12-08   Ashen                       4713.0  epic_yearly.xlsx
2 2018-12-09   Ashen                       7038.0  epic_yearly.xlsx
3 2018-12-10   Ashen                       8702.0  epic_yearly.xlsx
4 2018-12-11   Ashen                      10125.0  epic_yearly.xlsx

In [5]:
df.Source.unique()

array(['epic_yearly.xlsx', 'ps_yearly.xlsx', 'all_platforms.xlsx',
       'xbox_yearly.xlsx', 'all_platforms_rev.xlsx', 'steam_yearly.xlsx',
       'nintendo_yearly.xlsx'], dtype=object)

In [6]:
file_name = 'all_platforms_rev'

In [7]:
release_dict = {'The Lost Wild': '2025-12-31',
 'Wattam': '2019-12-17',
 'Storyteller: Devilish Update': '2023-09-26',
 'The Artful Escape': '2021-09-09',
 'Annapurna Interactive Deluxe Limited Edition Collection': '2023-12-22',
 'Annapurna Interactive: Ultimate Collection': '2020-12-08',
 'Annapurna Interactive Deluxe Limited Edition': '2020-12-15',
 'I Am Dead': '2020-10-08',
 'Outer Wilds: Archaeologist Edition': '2021-09-28',
 'The Pathless': '2020-11-12',
 'If Found...': '2020-05-19',
 'Telling Lies': '2019-08-23',
 'A Memoir Blue': '2022-03-24',
 'Stray': '2022-07-19',
 'Last Stop': '2021-07-22',
 'To a T': '2025-05-28',
 'Mundaun': '2021-03-16',
 'Solar Ash': '2021-12-02',
 'What Remains of Edith Finch': '2017-04-24',
 'Sayonara Wild Hearts': '2019-9-19',
 'Lushfoil Photography Sim': '2025-04-15',
 'Storyteller': '2023-03-23',
 'Gorogoa': '2017-12-13',
 'Wanderstop': '2025-03-11',
 'Journey': '2012-03-13',
 'Mixtape': '2025-12-31',
 'Open Roads': '2024-03-28',
 'Neon White': '2022-06-16',
 'Flower': '2009-02-12',
 'Twelve Minutes': '2021-08-19',
 'Outer Wilds: Echoes of the Eye': '2021-09-28',
 'Flock': '2024-07-16',
 'Maquette': '2021-03-02',
 'Cocoon': '2023-09-29',
 'Gone Home': '2013-08-15',
 'Outer Wilds': '2019-05-28',
 'Ashen: Nightstorm Isle': '2019-09-06',
 'Florence': '2018-02-13',
 'Thirsty Suitors': '2023-11-02',
 'Lorelei and the Laser Eyes': '2024-05-16',
 'Donut County': '2018-08-28',
 'Skin Deep': '2025-04-30',
 'Wheel World': '2025-06-30',
 'Hohokum': '2014-08-12',
 'Ashen: Definitive Edition': '2019-11-18',
 'Morsels': '2025-12-31',
 'Kentucky Route Zero: TV Edition': '2020-01-28',
 'The Unfinished Swan': '2012-10-23',
 'Hindsight': '2022-08-04',
 'Ashen': '2018-12-07'}

In [8]:
df_combined = df.query(f"Source =='{file_name}.xlsx'")

In [9]:
df_combined

,Date,product,Cumulative Selected Measure,Source
190582,2017-03-14,What Remains of Edith Finch,2673.49,all_platforms_rev.xlsx
190583,2017-03-15,What Remains of Edith Finch,7086.67,all_platforms_rev.xlsx
190584,2017-03-16,What Remains of Edith Finch,9976.77,all_platforms_rev.xlsx
190585,2017-03-17,What Remains of Edith Finch,11789.20,all_platforms_rev.xlsx
190586,2017-03-18,What Remains of Edith Finch,14156.59,all_platforms_rev.xlsx
...,...,...,...,...
287012,2025-04-09,Wanderstop - Soundtrack,14294.01,all_platforms_rev.xlsx
287013,2025-04-09,Wattam,1063741.76,all_platforms_rev.xlsx
287014,2025-04-09,Wattam - Original Soundtrack,4821.02,all_platforms_rev.xlsx
287015,2025-04-09,What Remains of Edith Finch,19411728.70,all_platforms_rev.xlsx
287016,2025-04-09,What Remains of Edith Finch - Original Soundtrack,95073.94,all_platforms_rev.xlsx

In [10]:
df_combined['release_date'] = pd.to_datetime(df_combined['Date'])

In [11]:
df_combined['release_date'] = df_combined.groupby('product')['release_date'].transform('min')

In [12]:
df_combined['release_date'] = df_combined['product'].map(release_dict)
df_combined['release_date'] = pd.to_datetime(df_combined['release_date'])

In [13]:
df_combined.query("product=='Cocoon'")

,Date,product,Cumulative Selected Measure,Source,release_date
250375,2023-09-01,Cocoon,8466.91,all_platforms_rev.xlsx,2023-09-29
250432,2023-09-02,Cocoon,11734.56,all_platforms_rev.xlsx,2023-09-29
250489,2023-09-03,Cocoon,13677.87,all_platforms_rev.xlsx,2023-09-29
250546,2023-09-04,Cocoon,15273.97,all_platforms_rev.xlsx,2023-09-29
250603,2023-09-05,Cocoon,16123.41,all_platforms_rev.xlsx,2023-09-29
...,...,...,...,...,...
286688,2025-04-05,Cocoon,4599714.47,all_platforms_rev.xlsx,2023-09-29
286755,2025-04-06,Cocoon,4600610.91,all_platforms_rev.xlsx,2023-09-29
286822,2025-04-07,Cocoon,4601246.24,all_platforms_rev.xlsx,2023-09-29
286889,2025-04-08,Cocoon,4601671.05,all_platforms_rev.xlsx,2023-09-29
286956,2025-04-09,Cocoon,4601700.09,all_platforms_rev.xlsx,2023-09-29

In [14]:
df_combined["DAR"] = (df_combined["Date"] - df_combined["release_date"]).dt.days
df_combined["DAR"] = df_combined["DAR"].clip(lower=0)

df_combined["Weeks_from_Release"] = (df_combined["DAR"] // 7) + 1  # Week 1 starts at 0-7 days
df_combined["years_from_release"] = (df_combined["DAR"] // 365) + 1

#df_combined = df_combined.query("0 <= Weeks_from_Release <=52")

df_combined = df_combined.query("'1/1/2015' <= release_date <='1/1/2025'")

df_combined = df_combined.groupby(["product", "years_from_release"], as_index=False)["Cumulative Selected Measure"].max()

In [15]:
df_combined['product'].unique()

array(['A Memoir Blue', 'Ashen', 'Cocoon', 'Donut County', 'Flock',
       'Florence', 'Gorogoa', 'Hindsight', 'I Am Dead', 'If Found...',
       'Kentucky Route Zero: TV Edition', 'Last Stop',
       'Lorelei and the Laser Eyes', 'Maquette', 'Mundaun', 'Neon White',
       'Open Roads', 'Outer Wilds', 'Sayonara Wild Hearts', 'Solar Ash',
       'Storyteller', 'Stray', 'Telling Lies', 'The Artful Escape',
       'The Pathless', 'Thirsty Suitors', 'Twelve Minutes', 'Wattam',
       'What Remains of Edith Finch'], dtype=object)

In [16]:
df_combined.query("product=='Stray'")
#df_combined.loc[df_combined["product"] == "Cocoon", ["DAR", "years_from_release"]]

   product  years_from_release  Cumulative Selected Measure
93   Stray                 1.0                 9.367176e+07
94   Stray                 2.0                 1.267232e+08
95   Stray                 3.0                 1.463963e+08

stop

In [17]:
title_exclusion = [
'Stray','Outer Wilds'
    

]

In [18]:
df_combined

,product,years_from_release,Cumulative Selected Measure
0,A Memoir Blue,1.0,102922.97
1,A Memoir Blue,2.0,143061.83
2,A Memoir Blue,3.0,181257.61
3,A Memoir Blue,4.0,181755.40
4,Ashen,1.0,2562433.31
...,...,...,...
126,What Remains of Edith Finch,4.0,11035830.27
127,What Remains of Edith Finch,5.0,13282081.51
128,What Remains of Edith Finch,6.0,15614056.48
129,What Remains of Edith Finch,7.0,17460157.09
130,What Remains of Edith Finch,8.0,19411728.70

df_combined = df_combined.query("product !=@title_exclusion")

In [19]:
#pd.set_option("display.max_rows", None)


df_combined["CUME_total"] = df_combined.groupby(["product"])["Cumulative Selected Measure"].transform("max")
df_combined["prop_of_total"] = df_combined["Cumulative Selected Measure"] / df_combined["CUME_total"]
df_combined["daily_delta"] = df_combined.groupby(["product"])["Cumulative Selected Measure"].pct_change().fillna(0)
df_combined.query("product=='Stray'")

,product,years_from_release,Cumulative Selected Measure,CUME_total,prop_of_total,daily_delta
93,Stray,1.0,9.367176e+07,1.463963e+08,0.639851,0.000000
94,Stray,2.0,1.267232e+08,1.463963e+08,0.865618,0.352843
95,Stray,3.0,1.463963e+08,1.463963e+08,1.000000,0.155244

In [20]:
df_combined.query("years_from_release==5").prop_of_total.mean()

0.9128942129666799

In [21]:
df_combined.pivot(index='product', columns='years_from_release', values='prop_of_total').fillna('').to_clipboard()

In [26]:
df_combined.pivot(index='product', columns='years_from_release', values='Cumulative Selected Measure').fillna('').to_clipboard()

In [28]:
pivot = df_combined.pivot(index='product', columns='years_from_release', values='Cumulative Selected Measure')
diffed = pivot.diff(axis=1)
diffed.iloc[:, 0] = pivot.iloc[:, 0]  # restore the first column
result = diffed.fillna('')
result.to_clipboard()

In [24]:
df_combined.to_clipboard()

platform_df = df_combined.groupby("Weeks_from_Release")[['daily_delta']].mean()
platform_df['platform'] = 'epic'

platform_df

platform_df.to_csv(f"units/{file_name}_average.csv")

In [25]:
stop

NameError: name 'stop' is not defined

In [ ]:
### Fit the Curve to a model and use this to predict



# Define folder path
folder_path = "/Users/dougs/Documents/GitHub/IndieBI-Sales-EDA/units/"

# Get all .xlsx files in the folder
files = glob.glob(f"{folder_path}/*.csv")

# Read all files into DataFrames and add filename column
dfs = [pd.read_csv(file).assign(Source=os.path.basename(file)) for file in files]

In [ ]:
files

In [ ]:
av_df = pd.concat(dfs, ignore_index=True)

In [ ]:
platforms = av_df.pivot_table(columns='platform', index='Weeks_from_Release', values='daily_delta').reset_index()

In [ ]:
platforms.to_clipboard()

In [ ]:
platforms.columns[1:]

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))  # Adjust figure size for better visibility

# Loop through unique platforms and plot each separately
for platform in ['steam', 'PS']:
    pdf = av_df.query("platform == @platform")
    sns.lineplot(data=pdf, x='Weeks_from_Release', y='daily_delta', label=platform)

# Improve aesthetics
plt.xlabel("Weeks After Release (DAR)")
plt.ylabel("Daily Average New Units Sold")
plt.title("Sales Curve by Platform")
plt.legend(title="Platform", loc="best")  # Set legend title
plt.grid(True)  # Add grid for readability

plt.show()

In [ ]:
platforms.query("Weeks_from_Release <=12")

In [ ]:
starting_val = 31_200

In [ ]:
current_week  = 1

In [ ]:
platforms.loc[current_week-1,'steam_projected'] = starting_val

In [ ]:
platforms.loc[current_week-1,'steam_projected'] = starting_val

In [ ]:
# Apply cumulative product starting from the specified index
platforms.loc[current_week:, 'steam_projected'] = (
    starting_val * (1 + platforms.loc[current_week:, 'steam']).cumprod()
)

In [ ]:
platforms['steam_projected'] = platforms['steam_projected'].fillna(starting_val)
platforms['steam_projected'] = platforms['steam_projected'].astype(int)

In [ ]:
platforms.to_clipboard()
platforms

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))  # Adjust figure size for better visibility


sns.lineplot(data=platforms.query("Weeks_from_Release <=12"), x='Weeks_from_Release', y='steam_projected', label='steam_projected')

# Improve aesthetics
plt.xlabel("Weeks After Release (DAR)")
plt.ylabel("Daily Average New Units Sold")
plt.title("Sales Curve by Platform")
plt.legend(title="Platform", loc="best")  # Set legend title
plt.grid(True)  # Add grid for readability

plt.show()